# GENERATED by scripts/deploy/generate_provider_configs.py — edit architecture/deploy_topology.json, then re-run; do not hand-edit
# Cloudflare plane rendered from architecture/deploy_topology.json — the SAME single source as fly/ + compose
# (no magic values). Provisioning ONLY (DNS + R2); per-request compute stays in the dispatch layer. Inert
# until `tofu apply`; run `tofu plan` first as the gate. Switch/extend providers = add another emitter, never
# a second source of truth.

terraform {
  required_version = ">= 1.6"  # OpenTofu
  required_providers {
    cloudflare = { source = "cloudflare/cloudflare", version = "~> 5" }
  }
  # Remote state on R2 (uncomment AFTER a state bucket exists; S3-compatible creds via env):
  # backend "s3" { /* R2 endpoint + bucket; see README.generated.md */ }
}

provider "cloudflare" {
  api_token = var.cloudflare_api_token
}

# ---- inputs (set via TF_VAR_* env or a gitignored *.tfvars — the token is a SecretRef, never committed) ----
variable "cloudflare_api_token" {
  type        = string
  sensitive   = true
  description = "Cloudflare API token (Zone:DNS:Edit + Workers R2 Storage:Edit). Set TF_VAR_cloudflare_api_token."
}
variable "account_id" {
  type        = string
  description = "Cloudflare account id"
}
variable "zone_id" {
  type        = string
  description = "Cloudflare DNS zone id for the public domain"
}
variable "fly_app_domain" {
  type        = string
  default     = "fly.dev"
  description = "CNAME target suffix; a public app routes to <app>.<domain>"
}

# ---- public surfaces: a proxied CNAME per public service (the DNS step the Fly runbook leaves manual) ----
resource "cloudflare_dns_record" "web_openhubforai" {
  zone_id = var.zone_id
  name    = "web-openhubforai"
  type    = "CNAME"
  content = "aidr-web-openhubforai.${var.fly_app_domain}"
  proxied = true
  ttl     = 1  # automatic (required when proxied)
}

resource "cloudflare_dns_record" "web_baltor" {
  zone_id = var.zone_id
  name    = "web-baltor"
  type    = "CNAME"
  content = "aidr-web-baltor.${var.fly_app_domain}"
  proxied = true
  ttl     = 1  # automatic (required when proxied)
}

resource "cloudflare_dns_record" "web_context" {
  zone_id = var.zone_id
  name    = "web-context"
  type    = "CNAME"
  content = "aidr-web-context.${var.fly_app_domain}"
  proxied = true
  ttl     = 1  # automatic (required when proxied)
}

resource "cloudflare_dns_record" "web_teleon" {
  zone_id = var.zone_id
  name    = "web-teleon"
  type    = "CNAME"
  content = "aidr-web-teleon.${var.fly_app_domain}"
  proxied = true
  ttl     = 1  # automatic (required when proxied)
}

resource "cloudflare_dns_record" "web_aidevobserver" {
  zone_id = var.zone_id
  name    = "web-aidevobserver"
  type    = "CNAME"
  content = "aidr-web-aidevobserver.${var.fly_app_domain}"
  proxied = true
  ttl     = 1  # automatic (required when proxied)
}

# ---- off-provider state backup: one R2 bucket per single-writer stateful service ----
resource "cloudflare_r2_bucket" "identity_state_backup" {
  account_id = var.account_id
  name       = "aidr-identity-state-backup"
}

resource "cloudflare_r2_bucket" "registry_state_backup" {
  account_id = var.account_id
  name       = "aidr-registry-state-backup"
}

resource "cloudflare_r2_bucket" "events_state_backup" {
  account_id = var.account_id
  name       = "aidr-events-state-backup"
}

resource "cloudflare_r2_bucket" "receipt_state_backup" {
  account_id = var.account_id
  name       = "aidr-receipt-state-backup"
}

resource "cloudflare_r2_bucket" "state_state_backup" {
  account_id = var.account_id
  name       = "aidr-state-state-backup"
}

resource "cloudflare_r2_bucket" "mailbox_state_backup" {
  account_id = var.account_id
  name       = "aidr-mailbox-state-backup"
}

resource "cloudflare_r2_bucket" "teleon_runtime_state_backup" {
  account_id = var.account_id
  name       = "aidr-teleon-runtime-state-backup"
}

resource "cloudflare_r2_bucket" "baltor_backend_state_backup" {
  account_id = var.account_id
  name       = "aidr-baltor-backend-state-backup"
}

resource "cloudflare_r2_bucket" "observer_state_backup" {
  account_id = var.account_id
  name       = "aidr-observer-state-backup"
}

resource "cloudflare_r2_bucket" "redis_state_backup" {
  account_id = var.account_id
  name       = "aidr-redis-state-backup"
}

resource "cloudflare_r2_bucket" "postgres_state_backup" {
  account_id = var.account_id
  name       = "aidr-postgres-state-backup"
}

output "public_hostnames" {
  value = {
    web_openhubforai = cloudflare_dns_record.web_openhubforai.name
    web_baltor = cloudflare_dns_record.web_baltor.name
    web_context = cloudflare_dns_record.web_context.name
    web_teleon = cloudflare_dns_record.web_teleon.name
    web_aidevobserver = cloudflare_dns_record.web_aidevobserver.name
  }
}
