"""src.teleon.compiler.emit — render a CompiledRuntimeUnit into the concrete deployable text.

Mirrors the topology generator's emitter pattern (one declarative source → many provider configs;
``scripts/deploy/generate_provider_configs.py`` emits fly + compose + cross-checks k8s). Here ONE compiled unit
emits ALL THREE concrete shapes so a capability is never cloud-locked:

  * ``fly_machine``   → a Fly Machines config dict (what ``fly machine run --config <file>`` consumes), serialized
                        as JSON. Sourced from the unit's image/command/env-refs/resources/budgets.
  * ``k8s_job``       → a Kubernetes ``batch/v1`` Job manifest, serialized as YAML. A Job (not a Deployment): a
                        capability run is an ephemeral, bounded unit of work (matches the kubernetes-job runtime
                        class). Resources + activeDeadlineSeconds + backoffLimit come from the unit's
                        resources/budgets — no magic values.
  * ``local_process`` → a local process spec (argv + env-ref names + the resolved budgets/timeout) for the
                        always-available offline path, serialized as JSON.

EVERY emitter stamps the OTel attrs onto its env/labels/annotations so trace correlation survives into the
runtime, and NEVER writes a secret VALUE — only the secret-ref NAMES the unit declares.

Pure + deterministic: a unit always renders to byte-identical text (json.dumps + a deterministic YAML writer,
both with sorted keys). stdlib + PyYAML only; no ``src.baltor`` / ``src.openhubforai`` import (dependency law).
"""
from __future__ import annotations

import json
import math
import re
from typing import Any

import yaml

#: Kubernetes object names must be DNS-1123 labels (lowercase alphanumeric + '-', start/end alphanumeric, ≤63).
_K8S_NAME_MAX = 63
_DNS1123_SUB = re.compile(r"[^a-z0-9-]+")

#: Fly guest cpu presets are INTEGER vCPU counts; a Kubernetes cpu quantity ("500m","2","250m","1") — the shape the
#: resource class carries — must be translated to a whole-core count for the fly_machine ``guest.cpus`` field. One
#: definition of the conversion (1 core = 1000 millicores), CEIL so we never UNDER-provision, floor at MIN_FLY_CPUS.
#: CANONICAL TRANSLATION — kept byte-identical with scripts/deploy/teleon_machines_runner.py::_cpu_to_fly_cpus
#: (MILLICORES_PER_CORE / MIN_FLY_CPUS / the parse + ceil + floor). The emitter is the LOWER layer (the runner imports
#: emit_fly_machine FROM here; emit imports nothing back — dependency law), so this is the single source the runner
#: should adopt. FOLLOW-UP: have the runner import _cpu_to_fly_cpus from this module and delete its private copy, so
#: there is exactly ONE definition; until that one-line runner edit lands, the runner reads the SAME resource-class
#: string (unit.resources.cpu) and applies the SAME formula, so emitter and runner can never disagree on the result.
_MILLICORES_PER_CORE = 1000          # 1 vCPU = 1000 millicores (Kubernetes cpu unit) — one definition, no parallel literal
_MIN_FLY_CPUS = 1                    # a Fly machine guest has at least 1 vCPU (floor)
_CPU_QUANTITY_RE = re.compile(r"([0-9]*\.?[0-9]+)(m?)")  # a Kubernetes cpu quantity: a number with an optional 'm' (milli) suffix


def _cpu_to_fly_cpus(cpu_quantity: str) -> int:
    """Translate a Kubernetes CPU quantity ('500m','2','250m','1') from the resource class into a whole Fly guest
    vCPU count (Fly's ``guest.cpus`` is an integer preset, not a millicore string). CEIL millicores to a core (never
    under-provision) and floor at ``_MIN_FLY_CPUS``. Deterministic; one millicores-per-core definition.

    Kept byte-identical with ``scripts/deploy/teleon_machines_runner.py::_cpu_to_fly_cpus`` (its canonical sibling) —
    see the constant comment above for the single-source plan."""
    s = str(cpu_quantity).strip()
    m = _CPU_QUANTITY_RE.fullmatch(s)
    if not m:
        # honest fallback: an unexpected CPU shape gets the minimum guest (matches the runner's same fallback).
        return _MIN_FLY_CPUS
    value = float(m.group(1))
    millicores = value if m.group(2) == "m" else value * _MILLICORES_PER_CORE
    return max(_MIN_FLY_CPUS, int(math.ceil(millicores / _MILLICORES_PER_CORE)))


def _k8s_name(capability_id: str) -> str:
    """A deterministic, valid DNS-1123 Job name for a capability ('teleon-' + the sanitized id)."""
    base = "teleon-" + _DNS1123_SUB.sub("-", str(capability_id).lower())
    return base.strip("-")[:_K8S_NAME_MAX].strip("-")

GENERATED_MARK = ("GENERATED by src/teleon/compiler (teleon capability runtime compiler) from a PROMOTED "
                  "capability — recompile, do not hand-edit")

#: OTel attr keys carry dots; Kubernetes label/annotation keys constrain the value-side charset, so OTel attrs ride
#: as ANNOTATIONS (free-form) not labels. ONE prefix definition (no parallel literals).
_K8S_ANNOTATION_PREFIX = "teleon.dev/"
#: Fly env keys are upper-snake; we expose the unit id + a fixed marker so a running machine self-identifies.
_FLY_UNIT_ENV_KEY = "TELEON_UNIT_ID"


def _require_exec_target(unit: dict, exec_target: str) -> None:
    if unit.get("exec_target") != exec_target:
        raise ValueError(f"unit.exec_target is {unit.get('exec_target')!r} but emit was asked for {exec_target!r} "
                         "— recompile the capability for this exec_target (units are PORTABLE: compile per target)")


# ── fly machine config ───────────────────────────────────────────────────────────────────────────────────────
def emit_fly_machine(unit: dict) -> str:
    """A Fly Machines config (JSON) for ``fly machine run --config <file>``. env carries ONLY ref names (the
    machine's real secrets are injected by ``fly secrets set`` out of band — never in this file)."""
    _require_exec_target(unit, "fly_machine")
    res = unit["resources"]
    budgets = unit["budgets"]
    env = {ref: f"${{{ref}}}" for ref in unit["container"]["env_refs"]}  # placeholder refs — fly injects real values
    env[_FLY_UNIT_ENV_KEY] = unit["unit_id"]
    config = {
        "init": {"cmd": unit["container"]["command"]},
        "image": unit["container"]["image"],
        "env": env,
        "guest": {
            # Fly guests are sized by named presets; memory_mb comes straight from the resource class. ``cpus`` MUST be
            # a whole-vCPU INTEGER (a Fly create rejects a millicore string like '500m'), so we translate the
            # resource-class cpu quantity here — the config is VALID at the source, not only after a launcher fixes it.
            # The raw resource-class cpu STRING is preserved losslessly in metadata.teleon_cpu_request below.
            "cpu_kind": "shared",
            "cpus": _cpu_to_fly_cpus(res["cpu"]),
            "memory_mb": res["memory_mb"],
        },
        "metadata": {
            "teleon_unit_id": unit["unit_id"],
            "capability_id": unit["capability_id"],
            "capability_version": str(unit["capability_version"]),
            "runtime_class": unit["runtime_class"],
            "backend": unit["backend"],
            # lossless: keep the EXACT resource-class cpu request (the Kubernetes quantity, e.g. '500m') alongside the
            # translated integer guest.cpus, so the millicore intent is never lost in the fly_machine shape.
            "teleon_cpu_request": res["cpu"],
            "otel": unit["logging"]["otel_attrs"],
            "generated": GENERATED_MARK,
        },
        # a capability run is bounded work — restart never, deadline from the budget (Fly stops the machine).
        "restart": {"policy": "no"},
        "stop_config": {"timeout": f"{int(budgets['timeout_s'])}s"},
    }
    return json.dumps(config, indent=2, sort_keys=True, ensure_ascii=False)


# ── k8s Job manifest ─────────────────────────────────────────────────────────────────────────────────────────
def build_k8s_job(unit: dict) -> dict:
    """The Kubernetes batch/v1 Job manifest as a dict (validate/inspect before YAML serialization)."""
    _require_exec_target(unit, "k8s_job")
    res = unit["resources"]
    budgets = unit["budgets"]
    otel = unit["logging"]["otel_attrs"]
    name = _k8s_name(unit["capability_id"])
    annotations = {f"{_K8S_ANNOTATION_PREFIX}{k.replace('.', '-')}": str(v) for k, v in otel.items()}
    annotations[f"{_K8S_ANNOTATION_PREFIX}generated"] = GENERATED_MARK
    resources: dict[str, Any] = {"requests": {"cpu": res["cpu"], "memory": f"{int(res['memory_mb'])}Mi"}}
    if res.get("gpu_required"):
        # GPUs are a scheduled LIMIT, not a request — declare it so a gpu capability lands on a gpu node.
        resources["limits"] = {"nvidia.com/gpu": 1}
    container = {
        "name": name,
        "image": unit["container"]["image"],
        "command": unit["container"]["command"],
        # env carries ONLY ref names via secretKeyRef — never an inline value (defense in depth).
        "env": [{"name": ref, "valueFrom": {"secretKeyRef": {"name": "teleon-model-plane", "key": ref}}}
                for ref in unit["container"]["env_refs"]],
        "resources": resources,
    }
    return {
        "apiVersion": "batch/v1",
        "kind": "Job",
        "metadata": {"name": name, "labels": {"app": name, "managed-by": "teleon-capability-compiler"},
                     "annotations": annotations},
        "spec": {
            # bounded work: backoffLimit from the gate's retry ceiling, activeDeadlineSeconds from the budget.
            "backoffLimit": int(budgets["max_attempts"]),
            "activeDeadlineSeconds": int(budgets["timeout_s"]),
            "ttlSecondsAfterFinished": int(budgets["timeout_s"]),
            "template": {
                "metadata": {"labels": {"app": name}, "annotations": annotations},
                "spec": {"restartPolicy": "Never", "containers": [container]},
            },
        },
    }


def emit_k8s_job(unit: dict) -> str:
    """The k8s Job manifest serialized as deterministic YAML (sorted keys, block style)."""
    return yaml.safe_dump(build_k8s_job(unit), sort_keys=True, default_flow_style=False)


# ── local process spec ───────────────────────────────────────────────────────────────────────────────────────
def emit_local_process(unit: dict) -> str:
    """A local process spec (JSON): argv + env-ref names + resolved budgets/timeout — the always-available offline
    path. No container runtime required; the same capability runs as a plain subprocess."""
    _require_exec_target(unit, "local_process")
    budgets = unit["budgets"]
    spec = {
        "kind": "TeleonLocalProcessSpec",
        "teleon_unit_id": unit["unit_id"],
        "capability_id": unit["capability_id"],
        "capability_version": unit["capability_version"],
        "argv": unit["container"]["command"],
        "env_refs": unit["container"]["env_refs"],  # names only — the operator's shell provides the values
        "timeout_s": int(budgets["timeout_s"]),
        "max_attempts": int(budgets["max_attempts"]),
        "max_tokens": int(budgets["max_tokens"]),
        "otel_attrs": unit["logging"]["otel_attrs"],
        "generated": GENERATED_MARK,
    }
    return json.dumps(spec, indent=2, sort_keys=True, ensure_ascii=False)


# ── customer repo (GitOps) — the "we don't run it, YOU run it in your own CI/CD" output ───────────────────────
_REPO_SCMS = ("github", "gitlab")


def emit_repo(unit: dict, *, scm: str = "github") -> dict[str, str]:
    """Emit a self-contained, GitOps-ready REPOSITORY for a compiled capability so the CUSTOMER runs it through THEIR
    OWN dev → test → prod pipeline + CI/CD. The ultimate 'compute external' output: Teleon emits the repo (the
    descended path, the runner, the eval gate, the CI) + keeps tracking the metadata/receipts (the descent brain stays
    the moat); the customer's pipeline runs the unit. No vendor lock-in — they own the code. Returns {path: content}.

    serves_truth=false: the emitted capability output is a candidate for the customer's own verification rail."""
    if scm not in _REPO_SCMS:
        raise ValueError(f"unknown scm {scm!r} (one of {_REPO_SCMS})")
    cap = unit["capability_id"]
    ver = unit["capability_version"]
    cmd = unit["container"]["command"]
    env_refs = list(unit["container"]["env_refs"])
    image = unit["container"]["image"]
    b = unit["budgets"]
    contract = {
        "schema_version": "TeleonCapabilityRepo", "capability_id": cap, "capability_version": ver,
        "runtime_class": unit["runtime_class"], "command": cmd, "env_refs": env_refs, "image": image,
        "budgets": {"timeout_s": int(b["timeout_s"]), "max_attempts": int(b["max_attempts"]), "max_tokens": int(b["max_tokens"])},
        "otel_attrs": unit["logging"]["otel_attrs"], "serves_truth": False, "generated": GENERATED_MARK,
    }
    files: dict[str, str] = {}
    files["capability.json"] = json.dumps(contract, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    files[".env.example"] = "# secret REFS the capability declares — set these in your CI/CD secrets, never commit values\n" + "".join(f"{r}=\n" for r in env_refs)
    files["run.sh"] = "#!/usr/bin/env bash\n# run the capability (the descended cheapest-bounded path)\nset -euo pipefail\nexec " + " ".join(cmd) + "\n"
    files["Dockerfile"] = (f"# {GENERATED_MARK}\nFROM {image}\nWORKDIR /app\nCOPY . /app\n"
                           + "".join(f"# requires secret: {r}\n" for r in env_refs)
                           + 'ENTRYPOINT ["bash", "run.sh"]\n')
    files["tests/test_capability_contract.py"] = (
        '"""Contract + smoke test for the emitted capability (runs in YOUR CI). Extend with your acceptance evals."""\n'
        "import json, pathlib\n\n"
        "C = json.loads(pathlib.Path('capability.json').read_text())\n\n"
        "def test_contract_is_intact():\n"
        f"    assert C['capability_id'] == {cap!r} and C['capability_version'] == {ver!r}\n"
        "    assert C['command'] and C['budgets']['timeout_s'] > 0\n\n"
        "def test_governed_not_truth():\n"
        "    assert C['serves_truth'] is False  # capability output is a candidate for YOUR verification rail\n")
    files["GOVERNANCE.md"] = (
        f"# Governance — {cap} v{ver}\n\nGenerated by Teleon as a GitOps capability repo. Teleon **descended** this "
        "capability to the cheapest bounded path that met the requirement; you now own + run it.\n\n"
        "- `serves_truth = false` — the capability's output is a CANDIDATE; gate it through your own verification rail.\n"
        f"- Budgets (enforced in your pipeline): timeout {int(b['timeout_s'])}s · max_attempts {int(b['max_attempts'])} · max_tokens {int(b['max_tokens'])}.\n"
        "- Secrets are REFS only (`.env.example`); set real values in your CI/CD secrets.\n"
        "- Teleon keeps tracking run metadata/receipts you report back (the descent brain) to suggest improvements.\n")
    files["README.md"] = (
        f"# {cap} — a Teleon capability repo (run it in YOUR pipeline)\n\n"
        "Teleon emitted this repository instead of running a worker, so you run the capability through your own "
        "**dev → test → prod** pipeline and CI/CD. No lock-in — the code is yours.\n\n"
        "## Run\n```bash\ncp .env.example .env   # set your secret values\nbash run.sh\n# or: docker build -t cap . && docker run --env-file .env cap\n```\n\n"
        "## CI/CD\nThe included pipeline runs the tests (the eval gate), builds the image, and promotes dev → test → "
        "prod. Add your acceptance evals to `tests/`. Contract: `capability.json`. Governance: `GOVERNANCE.md`.\n")
    if scm == "github":
        files[".github/workflows/ci.yml"] = (
            f"# {GENERATED_MARK}\nname: capability\non: [push, pull_request]\n"
            "jobs:\n"
            "  test:\n    runs-on: ubuntu-latest\n    steps:\n"
            "      - uses: actions/checkout@v4\n      - uses: actions/setup-python@v5\n        with: { python-version: '3.11' }\n"
            "      - run: pip install pytest && pytest -q\n"
            "  build:\n    needs: test\n    runs-on: ubuntu-latest\n    steps:\n"
            "      - uses: actions/checkout@v4\n      - run: docker build -t capability:${{ github.sha }} .\n"
            "  deploy-dev:\n    needs: build\n    if: github.ref == 'refs/heads/develop'\n    runs-on: ubuntu-latest\n    environment: dev\n    steps:\n      - run: echo 'deploy to DEV (wire your target)'\n"
            "  deploy-prod:\n    needs: build\n    if: github.ref == 'refs/heads/main'\n    runs-on: ubuntu-latest\n    environment: prod\n    steps:\n      - run: echo 'deploy to PROD (wire your target; requires environment approval)'\n")
    else:
        files[".gitlab-ci.yml"] = (
            f"# {GENERATED_MARK}\nstages: [test, build, deploy]\n"
            "test:\n  stage: test\n  image: python:3.11\n  script: [pip install pytest, pytest -q]\n"
            "build:\n  stage: build\n  image: docker:latest\n  services: [docker:dind]\n  script: [docker build -t capability:$CI_COMMIT_SHA .]\n"
            "deploy-dev:\n  stage: deploy\n  environment: dev\n  rules: [{ if: '$CI_COMMIT_BRANCH == \"develop\"' }]\n  script: [echo 'deploy to DEV (wire your target)']\n"
            "deploy-prod:\n  stage: deploy\n  environment: prod\n  when: manual\n  rules: [{ if: '$CI_COMMIT_BRANCH == \"main\"' }]\n  script: [echo 'deploy to PROD (manual approval)']\n")
    return files


_EMITTERS = {
    "fly_machine": emit_fly_machine,
    "k8s_job": emit_k8s_job,
    "local_process": emit_local_process,
}


def emit(unit: dict, exec_target: str | None = None) -> str:
    """Render ``unit`` to its concrete deployable text. ``exec_target`` defaults to the unit's own; passing a
    different one is an error (units are portable by RECOMPILE — one unit pins one target)."""
    target = exec_target or unit.get("exec_target")
    if target not in _EMITTERS:
        raise ValueError(f"unknown exec_target {target!r} (one of {tuple(_EMITTERS)})")
    return _EMITTERS[target](unit)


__all__ = ["emit", "emit_fly_machine", "emit_k8s_job", "emit_local_process", "emit_repo", "build_k8s_job", "GENERATED_MARK"]
