"""src.teleon.compiler.emit — render a CompiledRuntimeUnit into the concrete deployable text.

Mirrors the topology generator's emitter pattern (one declarative source → many provider configs;
``scripts/deploy/generate_provider_configs.py`` emits fly + compose + cross-checks k8s). Here ONE compiled unit
emits ALL THREE concrete shapes so a capability is never cloud-locked:

  * ``fly_machine``   → a Fly Machines config dict (what ``fly machine run --config <file>`` consumes), serialized
                        as JSON. Sourced from the unit's image/command/env-refs/resources/budgets.
  * ``k8s_job``       → a Kubernetes ``batch/v1`` Job manifest, serialized as YAML. A Job (not a Deployment): a
                        capability run is an ephemeral, bounded unit of work (matches the kubernetes-job runtime
                        class). Resources + activeDeadlineSeconds + backoffLimit come from the unit's
                        resources/budgets — no magic values.
  * ``local_process`` → a local process spec (argv + env-ref names + the resolved budgets/timeout) for the
                        always-available offline path, serialized as JSON.

EVERY emitter stamps the OTel attrs onto its env/labels/annotations so trace correlation survives into the
runtime, and NEVER writes a secret VALUE — only the secret-ref NAMES the unit declares.

Pure + deterministic: a unit always renders to byte-identical text (json.dumps + a deterministic YAML writer,
both with sorted keys). stdlib + PyYAML only; no ``src.baltor`` / ``src.openharnesshub`` import (dependency law).
"""
from __future__ import annotations

import json
import re
from typing import Any

import yaml

#: Kubernetes object names must be DNS-1123 labels (lowercase alphanumeric + '-', start/end alphanumeric, ≤63).
_K8S_NAME_MAX = 63
_DNS1123_SUB = re.compile(r"[^a-z0-9-]+")


def _k8s_name(capability_id: str) -> str:
    """A deterministic, valid DNS-1123 Job name for a capability ('teleon-' + the sanitized id)."""
    base = "teleon-" + _DNS1123_SUB.sub("-", str(capability_id).lower())
    return base.strip("-")[:_K8S_NAME_MAX].strip("-")

GENERATED_MARK = ("GENERATED by src/teleon/compiler (teleon capability runtime compiler) from a PROMOTED "
                  "capability — recompile, do not hand-edit")

#: OTel attr keys carry dots; Kubernetes label/annotation keys constrain the value-side charset, so OTel attrs ride
#: as ANNOTATIONS (free-form) not labels. ONE prefix definition (no parallel literals).
_K8S_ANNOTATION_PREFIX = "teleon.dev/"
#: Fly env keys are upper-snake; we expose the unit id + a fixed marker so a running machine self-identifies.
_FLY_UNIT_ENV_KEY = "TELEON_UNIT_ID"


def _require_exec_target(unit: dict, exec_target: str) -> None:
    if unit.get("exec_target") != exec_target:
        raise ValueError(f"unit.exec_target is {unit.get('exec_target')!r} but emit was asked for {exec_target!r} "
                         "— recompile the capability for this exec_target (units are PORTABLE: compile per target)")


# ── fly machine config ───────────────────────────────────────────────────────────────────────────────────────
def emit_fly_machine(unit: dict) -> str:
    """A Fly Machines config (JSON) for ``fly machine run --config <file>``. env carries ONLY ref names (the
    machine's real secrets are injected by ``fly secrets set`` out of band — never in this file)."""
    _require_exec_target(unit, "fly_machine")
    res = unit["resources"]
    budgets = unit["budgets"]
    env = {ref: f"${{{ref}}}" for ref in unit["container"]["env_refs"]}  # placeholder refs — fly injects real values
    env[_FLY_UNIT_ENV_KEY] = unit["unit_id"]
    config = {
        "init": {"cmd": unit["container"]["command"]},
        "image": unit["container"]["image"],
        "env": env,
        "guest": {
            # Fly guests are sized by named presets; we carry the resolved cpu/memory from the resource class so the
            # operator picks a matching preset (cpu string + memory_mb come straight from worker_resource_classes).
            "cpu_kind": "shared",
            "cpus": res["cpu"],
            "memory_mb": res["memory_mb"],
        },
        "metadata": {
            "teleon_unit_id": unit["unit_id"],
            "capability_id": unit["capability_id"],
            "capability_version": str(unit["capability_version"]),
            "runtime_class": unit["runtime_class"],
            "backend": unit["backend"],
            "otel": unit["logging"]["otel_attrs"],
            "generated": GENERATED_MARK,
        },
        # a capability run is bounded work — restart never, deadline from the budget (Fly stops the machine).
        "restart": {"policy": "no"},
        "stop_config": {"timeout": f"{int(budgets['timeout_s'])}s"},
    }
    return json.dumps(config, indent=2, sort_keys=True, ensure_ascii=False)


# ── k8s Job manifest ─────────────────────────────────────────────────────────────────────────────────────────
def build_k8s_job(unit: dict) -> dict:
    """The Kubernetes batch/v1 Job manifest as a dict (validate/inspect before YAML serialization)."""
    _require_exec_target(unit, "k8s_job")
    res = unit["resources"]
    budgets = unit["budgets"]
    otel = unit["logging"]["otel_attrs"]
    name = _k8s_name(unit["capability_id"])
    annotations = {f"{_K8S_ANNOTATION_PREFIX}{k.replace('.', '-')}": str(v) for k, v in otel.items()}
    annotations[f"{_K8S_ANNOTATION_PREFIX}generated"] = GENERATED_MARK
    resources: dict[str, Any] = {"requests": {"cpu": res["cpu"], "memory": f"{int(res['memory_mb'])}Mi"}}
    if res.get("gpu_required"):
        # GPUs are a scheduled LIMIT, not a request — declare it so a gpu capability lands on a gpu node.
        resources["limits"] = {"nvidia.com/gpu": 1}
    container = {
        "name": name,
        "image": unit["container"]["image"],
        "command": unit["container"]["command"],
        # env carries ONLY ref names via secretKeyRef — never an inline value (defense in depth).
        "env": [{"name": ref, "valueFrom": {"secretKeyRef": {"name": "teleon-model-plane", "key": ref}}}
                for ref in unit["container"]["env_refs"]],
        "resources": resources,
    }
    return {
        "apiVersion": "batch/v1",
        "kind": "Job",
        "metadata": {"name": name, "labels": {"app": name, "managed-by": "teleon-capability-compiler"},
                     "annotations": annotations},
        "spec": {
            # bounded work: backoffLimit from the gate's retry ceiling, activeDeadlineSeconds from the budget.
            "backoffLimit": int(budgets["max_attempts"]),
            "activeDeadlineSeconds": int(budgets["timeout_s"]),
            "ttlSecondsAfterFinished": int(budgets["timeout_s"]),
            "template": {
                "metadata": {"labels": {"app": name}, "annotations": annotations},
                "spec": {"restartPolicy": "Never", "containers": [container]},
            },
        },
    }


def emit_k8s_job(unit: dict) -> str:
    """The k8s Job manifest serialized as deterministic YAML (sorted keys, block style)."""
    return yaml.safe_dump(build_k8s_job(unit), sort_keys=True, default_flow_style=False)


# ── local process spec ───────────────────────────────────────────────────────────────────────────────────────
def emit_local_process(unit: dict) -> str:
    """A local process spec (JSON): argv + env-ref names + resolved budgets/timeout — the always-available offline
    path. No container runtime required; the same capability runs as a plain subprocess."""
    _require_exec_target(unit, "local_process")
    budgets = unit["budgets"]
    spec = {
        "kind": "TeleonLocalProcessSpec",
        "teleon_unit_id": unit["unit_id"],
        "capability_id": unit["capability_id"],
        "capability_version": unit["capability_version"],
        "argv": unit["container"]["command"],
        "env_refs": unit["container"]["env_refs"],  # names only — the operator's shell provides the values
        "timeout_s": int(budgets["timeout_s"]),
        "max_attempts": int(budgets["max_attempts"]),
        "max_tokens": int(budgets["max_tokens"]),
        "otel_attrs": unit["logging"]["otel_attrs"],
        "generated": GENERATED_MARK,
    }
    return json.dumps(spec, indent=2, sort_keys=True, ensure_ascii=False)


_EMITTERS = {
    "fly_machine": emit_fly_machine,
    "k8s_job": emit_k8s_job,
    "local_process": emit_local_process,
}


def emit(unit: dict, exec_target: str | None = None) -> str:
    """Render ``unit`` to its concrete deployable text. ``exec_target`` defaults to the unit's own; passing a
    different one is an error (units are portable by RECOMPILE — one unit pins one target)."""
    target = exec_target or unit.get("exec_target")
    if target not in _EMITTERS:
        raise ValueError(f"unknown exec_target {target!r} (one of {tuple(_EMITTERS)})")
    return _EMITTERS[target](unit)


__all__ = ["emit", "emit_fly_machine", "emit_k8s_job", "emit_local_process", "build_k8s_job", "GENERATED_MARK"]
