#!/usr/bin/env python3
"""Provider-config generator — one topology, many providers (the switch-cost killer).

`architecture/deploy_topology.json` is the single source for the cloud service plane
(services, commands, resources, seams, scaling). This script renders it into:

  * `fly/<app>.fly.toml`            — one Fly app per service (current target provider)
  * `fly/README.generated.md`       — exact deploy order + commands (no secrets, placeholders)
  * `deploy/docker-compose.deploy.yml` — the same plane on plain Docker (parity proof + any-VPS path)

and CROSS-CHECKS the hand-maintained K8s manifests (`infra/k8s/service-plane.yaml`,
`infra/k8s/worker.yaml`) against the same topology, so KEDA scaling numbers and the Fly
worker-controller numbers can never drift apart. Ports are never typed in the topology —
they are joined from `architecture/local_service_registry.json` (no magic values).

Switching providers later = add an emitter here (or run the compose file on any VPS/k3s);
the services themselves are provider-blind: they read OH_BIND_HOST, OH_SEAM_*_BASE and
AIDR_IDENTITY_BASE from env, defaulting to the local 127.0.0.1 plane.

Modes:
  python3 scripts/deploy/generate_provider_configs.py              # (re)generate
  python3 scripts/deploy/generate_provider_configs.py --check      # fail if outputs drift / k8s mismatch
  python3 scripts/deploy/generate_provider_configs.py --self-test  # offline invariants
"""
from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from scripts.foundry.queues import DEFAULT_QUEUE_KEY  # noqa: E402  (single source of the queue key)

TOPOLOGY_PATH = REPO / "architecture" / "deploy_topology.json"
SERVICE_REGISTRY_PATH = REPO / "architecture" / "local_service_registry.json"
FLY_DIR = REPO / "fly"
COMPOSE_PATH = REPO / "deploy" / "docker-compose.deploy.yml"
GENERATED_MARK = "GENERATED by scripts/deploy/generate_provider_configs.py — edit architecture/deploy_topology.json, then re-run; do not hand-edit"


# ---------------------------------------------------------------- topology load + join

def load_topology(topology_path: Path = TOPOLOGY_PATH,
                  registry_path: Path = SERVICE_REGISTRY_PATH) -> dict:
    topo = json.loads(topology_path.read_text(encoding="utf-8"))
    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    ports = {svc["service_id"]: svc["port"] for svc in registry["services"]}
    for svc in topo["services"]:
        rid = svc.get("registry_service_id")
        if rid is not None:
            if rid not in ports:
                raise SystemExit(f"deploy_topology: service '{svc['name']}' references unknown "
                                 f"registry_service_id '{rid}' (not in {registry_path.name})")
            svc["port"] = ports[rid]
        elif svc.get("kind") in ("backend", "web", "data") and "port" not in svc:
            raise SystemExit(f"deploy_topology: service '{svc['name']}' has neither "
                             f"registry_service_id nor an explicit port")
    scaling = next(s for s in topo["services"] if s["name"] == "worker")["scaling"]
    if scaling["queue_key"] != DEFAULT_QUEUE_KEY:
        raise SystemExit(f"deploy_topology: worker scaling.queue_key={scaling['queue_key']!r} but "
                         f"scripts.foundry.queues.DEFAULT_QUEUE_KEY={DEFAULT_QUEUE_KEY!r} — one source only")
    return topo


def fly_app_name(topo: dict, service_name: str) -> str:
    return f"{topo['fly']['app_prefix']}-{service_name}"


def resolve_ref(topo: dict, value: str, provider: str) -> str:
    """'@<service>' → that service's base URL on the given provider's private network."""
    if not value.startswith("@"):
        return value
    ref = value[1:]
    if ref.startswith("app:"):  # '@app:worker' → the provider-level app name
        return fly_app_name(topo, ref[4:]) if provider == "fly" else ref[4:]
    target = next((s for s in topo["services"] if s["name"] == ref), None)
    if target is None:
        raise SystemExit(f"deploy_topology: env reference '@{ref}' matches no service")
    if provider == "fly":
        suffix = topo["fly"]["internal_domain_suffix"]
        return f"http://{fly_app_name(topo, ref)}{suffix}:{target['port']}"
    return f"http://{ref}:{target['port']}"  # k8s Service / compose service DNS


def service_env(topo: dict, svc: dict, provider: str) -> dict[str, str]:
    env = {"OH_BIND_HOST": "0.0.0.0"}
    for key, value in (svc.get("env") or {}).items():
        env[key] = resolve_ref(topo, value, provider)
    return env


def secret_keys(topo: dict, svc: dict) -> list[str]:
    keys: list[str] = []
    for group in svc.get("secret_groups") or []:
        keys.extend(topo["secret_group_contents"][group])
    return keys


# ---------------------------------------------------------------- fly emitter

def fly_toml(topo: dict, svc: dict) -> str:
    app = fly_app_name(topo, svc["name"])
    lines = [
        f"# {GENERATED_MARK}",
        f"# service: {svc['name']} (kind={svc['kind']})" + (f" — {svc['phase']}" if svc.get("phase") else ""),
        f'app = "{app}"',
        f'primary_region = "{topo["fly"]["primary_region"]}"',
        "",
        "[build]",
    ]
    if svc.get("image"):
        lines.append(f'  image = "{svc["image"]}"')
    else:
        lines.append(f'  dockerfile = "{topo["image"]["dockerfile"]}"  # deploy from repo root: fly deploy -c fly/{app}.fly.toml')
    lines += ["", "[processes]", f'  app = "{" ".join(svc["command"])}"'] if svc.get("command") else []
    env = service_env(topo, svc, "fly")
    if env:
        lines += ["", "[env]"]
        lines += [f'  {k} = "{v}"' for k, v in sorted(env.items())]
    secrets = secret_keys(topo, svc)
    if secrets:
        lines += ["", f"# secrets (never in this file): fly secrets set -a {app} " + " ".join(f"{k}=…" for k in secrets)]
    if svc.get("state_mount"):
        volume = re.sub(r"[^a-z0-9_]", "_", f"{svc['name']}_state")
        lines += ["", "[[mounts]]", f'  source = "{volume}"', f'  destination = "{svc["state_mount"]}"',
                  f'  initial_size = "{svc.get("volume_gb", 1)}gb"']
    if svc.get("public"):
        lines += ["", "[http_service]", f"  internal_port = {svc['port']}", "  force_https = true",
                  '  auto_stop_machines = "stop"', "  auto_start_machines = true", "  min_machines_running = 1",
                  "", "  [[http_service.checks]]", '    interval = "30s"', '    timeout = "5s"',
                  '    grace_period = "20s"', '    method = "GET"', f'    path = "{svc.get("health_path", "/")}"']
    elif svc.get("health_path") and svc.get("port"):
        lines += ["", "[checks.health]", '  type = "http"', f"  port = {svc['port']}",
                  f'  path = "{svc["health_path"]}"', '  interval = "30s"', '  timeout = "5s"',
                  '  grace_period = "20s"']
    if svc["kind"] == "burst":
        scaling = svc["scaling"]
        lines += ["", f"# burst fleet: machines are managed by the worker-controller (scale "
                      f"{scaling['min_workers']}→{scaling['max_workers']['fly']} on redis list "
                      f"'{scaling['queue_key']}', {scaling['jobs_per_worker']} jobs/worker). "
                      f"After 'fly deploy --ha=false', stop the seed machine; the controller owns the fleet."]
    lines += ["", "[[vm]]", f'  cpu_kind = "{svc.get("cpu_kind", "shared")}"', f"  cpus = {svc.get('cpus', 1)}",
              f"  memory_mb = {svc.get('memory_mb', 512)}", ""]
    return "\n".join(lines)


def fly_readme(topo: dict, order: list[dict]) -> str:
    prefix = topo["fly"]["app_prefix"]
    region = topo["fly"]["primary_region"]
    out = [f"<!-- {GENERATED_MARK} -->", "", "# Fly.io deploy — generated plan",
           "", f"Region: `{region}` (fallback `{topo['fly']['fallback_region']}`). One Fly app per service; "
               "internal services have NO public proxy and talk over the private 6PN network "
               "(`<app>.internal:<port>`). Full owner/agent runbook: `docs/architecture/fly-deploy-runbook.md`.",
           "", "Deploy order (dependencies first):", ""]
    for svc in order:
        app = f"{prefix}-{svc['name']}"
        if svc.get("providers") and "fly" not in svc["providers"]:
            continue
        steps = [f"fly apps create {app}"]
        if svc.get("state_mount"):
            volume = re.sub(r"[^a-z0-9_]", "_", f"{svc['name']}_state")
            steps.append(f"fly volumes create {volume} -a {app} -r {region} -s {svc.get('volume_gb', 1)}")
        secrets = secret_keys(topo, svc)
        if secrets:
            steps.append(f"fly secrets set -a {app} --stage " + " ".join(f"{k}=<value>" for k in secrets))
        steps.append(f"fly deploy -c fly/{app}.fly.toml --ha=false")
        if svc["kind"] == "burst":
            steps.append(f"fly machine list -a {app} -q | xargs -r -n1 fly machine stop -a {app}  "
                         f"# controller owns the fleet from here")
        out.append(f"## {len(out)}. {app}" + (f" — {svc['phase']}" if svc.get("phase") else ""))
        out += ["", "```bash", *steps, "```", ""]
    out += ["After deploys: point Cloudflare DNS at the public apps (CNAME → <app>.fly.dev, proxied), "
            "then run the public gates (e2e/ohh_public_gate.mjs, e2e/teleon_gate.mjs) against the domains.", ""]
    return "\n".join(out)


# ---------------------------------------------------------------- compose emitter

def compose_yaml(topo: dict) -> str:
    """The same plane as plain docker-compose — parity proof and the any-VPS escape hatch."""
    lines = [f"# {GENERATED_MARK}",
             "# Run from repo root: docker compose -f deploy/docker-compose.deploy.yml up",
             "# Worker fleet: --profile workers (scaled manually here; KEDA on k8s / controller on Fly).",
             "name: aidoneright", "services:"]
    volumes: list[str] = []
    for svc in topo["services"]:
        if svc.get("providers") and set(svc["providers"]) == {"fly"}:
            continue  # fly-only roles (worker-controller) have no compose analog
        lines.append(f"  {svc['name']}:")
        if svc.get("image"):
            lines.append(f"    image: {svc['image']}")
        else:
            lines.append("    build: { context: .., dockerfile: Dockerfile }")
        if svc.get("command"):
            lines.append("    command: " + json.dumps(svc["command"]))
        env = service_env(topo, svc, "compose")
        for group in svc.get("secret_groups") or []:
            if group in ("queue-stores", "baltor-stores"):
                env.setdefault("REDIS_URL", "redis://redis:6379/0")
        if svc["name"] == "postgres":
            env.setdefault("POSTGRES_PASSWORD", "${POSTGRES_PASSWORD:?set in .env}")
        if env:
            lines.append("    environment:")
            lines += [f"      {k}: {json.dumps(v)}" for k, v in sorted(env.items())]
        if svc.get("public"):
            lines.append(f'    ports: ["{svc["port"]}:{svc["port"]}"]')
        if svc.get("state_mount"):
            volume = re.sub(r"[^a-z0-9_]", "_", f"{svc['name']}_state")
            volumes.append(volume)
            lines.append(f"    volumes: [{volume}:{svc['state_mount']}]")
        deps = sorted({v[1:] for v in (svc.get("env") or {}).values()
                       if isinstance(v, str) and v.startswith("@") and not v.startswith("@app:")})
        if svc["kind"] == "burst":
            deps = sorted(set(deps) | {"redis"})
            lines.append("    profiles: [workers]")
        if svc.get("phase"):
            lines.append("    profiles: [phase2]")
        if deps:
            lines.append("    depends_on: " + json.dumps(deps))
        lines.append("    restart: unless-stopped")
    lines.append("volumes:")
    lines += [f"  {v}:" for v in sorted(set(volumes))]
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------- k8s cross-checks

def check_k8s(topo: dict, repo: Path = REPO) -> list[str]:
    """The K8s manifests stay hand-maintained (they predate this generator) but may not drift
    from the topology on the facts both share. Returns a list of mismatch messages."""
    problems: list[str] = []
    checks = topo["k8s_cross_checks"]
    plane = (repo / checks["service_plane_file"])
    if plane.is_file():
        text = plane.read_text(encoding="utf-8")
        for name in checks["service_plane_must_contain_deployments"]:
            if f"name: {name}" not in text:
                problems.append(f"{checks['service_plane_file']}: missing Deployment/Service '{name}'")
        if "OH_BIND_HOST" not in text:
            problems.append(f"{checks['service_plane_file']}: no OH_BIND_HOST env — pods would bind 127.0.0.1 and be unreachable")
    else:
        problems.append(f"{checks['service_plane_file']}: file missing")
    worker = (repo / checks["worker_file"])
    scaling = next(s for s in topo["services"] if s["name"] == "worker")["scaling"]
    if worker.is_file():
        text = worker.read_text(encoding="utf-8")
        expectations = {
            f'listName: "{scaling["queue_key"]}"': "queue key",
            f'listLength: "{scaling["jobs_per_worker"]}"': "jobs per worker",
            f"maxReplicaCount: {scaling['max_workers']['k8s']}": "max workers (k8s)",
            f"pollingInterval: {scaling['poll_seconds']}": "poll seconds",
            f"cooldownPeriod: {scaling['cooldown_seconds']}": "cooldown seconds",
        }
        for needle, label in expectations.items():
            if needle not in text:
                problems.append(f"{checks['worker_file']}: {label} drifted from deploy_topology ({needle!r} not found)")
    else:
        problems.append(f"{checks['worker_file']}: file missing")
    # stray hand-typed queue-key copies: every watched file must carry the canonical key,
    # so changing the topology key fails loudly everywhere instead of silently forking queues
    for rel in checks.get("queue_key_watch_files", []):
        watched = repo / rel
        if not watched.is_file():
            problems.append(f"{rel}: queue-key watch file missing")
        elif scaling["queue_key"] not in watched.read_text(encoding="utf-8"):
            problems.append(f"{rel}: does not carry the canonical queue key {scaling['queue_key']!r} — "
                            f"stale copy (update it or drop it from queue_key_watch_files)")
    return problems


# ---------------------------------------------------------------- generate / check

def render_all(topo: dict) -> dict[Path, str]:
    order = [s for s in topo["services"]]  # topology order IS the dependency order
    out: dict[Path, str] = {}
    for svc in topo["services"]:
        if svc.get("providers") and "fly" not in svc["providers"]:
            continue
        out[FLY_DIR / f"{fly_app_name(topo, svc['name'])}.fly.toml"] = fly_toml(topo, svc)
    out[FLY_DIR / "README.generated.md"] = fly_readme(topo, order)
    out[COMPOSE_PATH] = compose_yaml(topo)
    return out


def generate() -> int:
    topo = load_topology()
    problems = check_k8s(topo)
    if problems:
        print("K8S CROSS-CHECK FAILURES (fix manifests or topology — same facts, one source):")
        for p in problems:
            print(f"  ✗ {p}")
        return 1
    rendered = render_all(topo)
    FLY_DIR.mkdir(exist_ok=True)
    COMPOSE_PATH.parent.mkdir(exist_ok=True)
    for path, content in rendered.items():
        path.write_text(content, encoding="utf-8")
        print(f"  wrote {path.relative_to(REPO)}")
    print(f"PASS — {len(rendered)} provider configs generated from {TOPOLOGY_PATH.relative_to(REPO)}")
    return 0


def check() -> int:
    topo = load_topology()
    problems = check_k8s(topo)
    rendered = render_all(topo)
    for path, expected in rendered.items():
        actual = path.read_text(encoding="utf-8") if path.is_file() else None
        if actual is None:
            problems.append(f"{path.relative_to(REPO)}: missing — run the generator")
        elif actual != expected:
            diff = list(difflib.unified_diff(actual.splitlines(), expected.splitlines(), lineterm="", n=1))
            problems.append(f"{path.relative_to(REPO)}: drifted from topology ({len(diff)} diff lines; first: "
                            f"{next((d for d in diff if d.startswith(('+', '-')) and not d.startswith(('+++', '---'))), '')!r})")
    if problems:
        print("CHECK FAILURES:")
        for p in problems:
            print(f"  ✗ {p}")
        return 1
    print(f"PASS — fly/ + compose match {TOPOLOGY_PATH.relative_to(REPO)}; k8s cross-checks green")
    return 0


# ---------------------------------------------------------------- self-test

def self_test() -> int:
    topo = load_topology()
    rendered = render_all(topo)
    web = rendered[FLY_DIR / f"{fly_app_name(topo, 'web-harness-hub')}.fly.toml"]
    identity = rendered[FLY_DIR / f"{fly_app_name(topo, 'identity')}.fly.toml"]
    worker = rendered[FLY_DIR / f"{fly_app_name(topo, 'worker')}.fly.toml"]
    compose = rendered[COMPOSE_PATH]
    checks = [
        ("web app is public", "[http_service]" in web and "min_machines_running = 1" in web),
        ("web seams resolve to fly .internal bases",
         'OH_SEAM_IDENTITY_BASE = "http://aidr-identity.internal:9410"' in web
         and 'OH_SEAM_LIVEOPS_BASE = "http://aidr-baltor-backend.internal:9301"' in web),
        ("internal service has no public proxy", "[http_service]" not in identity and "[checks.health]" in identity),
        ("every service binds 0.0.0.0 in containers", all('OH_BIND_HOST = "0.0.0.0"' in t
         for p, t in rendered.items() if p.suffix == ".toml" and "[processes]" in t)),
        ("worker has no proxy and no checks (controller-managed)",
         "[http_service]" not in worker and "[checks.health]" not in worker),
        ("controller is fly-only (absent from compose)", "worker-controller" not in compose),
        ("compose seams resolve to service DNS", '"http://identity:9410"' in compose),
        ("compose wires worker REDIS_URL to the redis service", '"redis://redis:6379/0"' in compose),
        ("no secret VALUES leak into any generated file", all(
            tok not in content for content in rendered.values()
            for tok in ("sk-or-", "OH_LLM_API_KEY ="))),
        ("k8s cross-checks pass on the real manifests", not check_k8s(topo)),
        ("queue key single-sourced", topo and DEFAULT_QUEUE_KEY == "ohh:foundry:jobs"),
    ]
    # drift detection actually fires
    with tempfile.TemporaryDirectory() as tmp:
        sample = Path(tmp) / "sample.toml"
        sample.write_text(web + "\n# tampered", encoding="utf-8")
        checks.append(("tampered output differs from render", sample.read_text(encoding="utf-8") != web))
    failed = [name for name, ok in checks if not ok]
    for name, ok in checks:
        print(f"  [{'ok' if ok else 'FAIL'}] {name}")
    print(("PASS — " if not failed else "FAIL — ") + f"{len(checks) - len(failed)}/{len(checks)} self-test checks")
    return 1 if failed else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="verify generated files + k8s match the topology")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args(argv)
    if args.self_test:
        return self_test()
    if args.check:
        return check()
    return generate()


if __name__ == "__main__":
    raise SystemExit(main())
