#!/usr/bin/env python3
"""Provider-config generator — one topology, many providers (the switch-cost killer).

`architecture/deploy_topology.json` is the single source for the cloud service plane
(services, commands, resources, seams, scaling). This script renders it into:

  * `fly/<app>.fly.toml`            — one Fly app per service (current target provider)
  * `fly/README.generated.md`       — exact deploy order + commands (no secrets, placeholders)
  * `deploy/docker-compose.deploy.yml` — the same plane on plain Docker (parity proof + any-VPS path)

and CROSS-CHECKS the hand-maintained K8s manifests (`infra/k8s/service-plane.yaml`,
`infra/k8s/worker.yaml`) against the same topology, so KEDA scaling numbers and the Fly
worker-controller numbers can never drift apart. Ports are never typed in the topology —
they are joined from `architecture/local_service_registry.json` (no magic values).

Switching providers later = add an emitter here (or run the compose file on any VPS/k3s);
the services themselves are provider-blind: they read OH_BIND_HOST, OH_SEAM_*_BASE and
AIDR_IDENTITY_BASE from env, defaulting to the local 127.0.0.1 plane.

Modes:
  python3 scripts/deploy/generate_provider_configs.py              # (re)generate
  python3 scripts/deploy/generate_provider_configs.py --check      # fail if outputs drift / k8s mismatch
  python3 scripts/deploy/generate_provider_configs.py --self-test  # offline invariants
"""
from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from scripts.foundry.queues import DEFAULT_QUEUE_KEY  # noqa: E402  (single source of the queue key)

TOPOLOGY_PATH = REPO / "architecture" / "deploy_topology.json"
SERVICE_REGISTRY_PATH = REPO / "architecture" / "local_service_registry.json"
FLY_DIR = REPO / "fly"
COMPOSE_PATH = REPO / "deploy" / "docker-compose.deploy.yml"
TOFU_DIR = REPO / "deploy" / "tofu" / "cloudflare"   # OpenTofu (open-source Terraform fork) emitter — Cloudflare plane
GENERATED_MARK = "GENERATED by scripts/deploy/generate_provider_configs.py — edit architecture/deploy_topology.json, then re-run; do not hand-edit"
FEEDER_SCHEDULE = "daily"          # Fly scheduled-machine cadence for the queue feeders (hourly|daily|weekly|monthly)
VOLUME_SNAPSHOT_RETENTION_DAYS = 5  # Fly BILLS snapshot storage — pin retention explicitly (≈ a working week of rollback)


# ---------------------------------------------------------------- topology load + join

def load_topology(topology_path: Path = TOPOLOGY_PATH,
                  registry_path: Path = SERVICE_REGISTRY_PATH) -> dict:
    topo = json.loads(topology_path.read_text(encoding="utf-8"))
    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    ports = {svc["service_id"]: svc["port"] for svc in registry["services"]}
    for svc in topo["services"]:
        rid = svc.get("registry_service_id")
        if rid is not None:
            if rid not in ports:
                raise SystemExit(f"deploy_topology: service '{svc['name']}' references unknown "
                                 f"registry_service_id '{rid}' (not in {registry_path.name})")
            svc["port"] = ports[rid]
        elif svc.get("kind") in ("backend", "web", "data") and "port" not in svc:
            raise SystemExit(f"deploy_topology: service '{svc['name']}' has neither "
                             f"registry_service_id nor an explicit port")
    scaling = next(s for s in topo["services"] if s["name"] == "worker")["scaling"]
    if scaling["queue_key"] != DEFAULT_QUEUE_KEY:
        raise SystemExit(f"deploy_topology: worker scaling.queue_key={scaling['queue_key']!r} but "
                         f"scripts.foundry.queues.DEFAULT_QUEUE_KEY={DEFAULT_QUEUE_KEY!r} — one source only")
    return topo


def fly_app_name(topo: dict, service_name: str) -> str:
    return f"{topo['fly']['app_prefix']}-{service_name}"


def volume_name(svc: dict) -> str:
    """The volume name for a stateful service — ONE definition (toml mounts, volume-create
    steps, and the snapshot-retention runbook must never drift apart)."""
    return re.sub(r"[^a-z0-9_]", "_", f"{svc['name']}_state")


def stateful_services(topo: dict) -> list[dict]:
    """Services owning single-writer volume state (the single-machine-law set), topology order."""
    return [s for s in topo["services"] if s.get("state_mount")]


def resolve_ref(topo: dict, value: str, provider: str) -> str:
    """'@<service>' → that service's base URL on the given provider's private network."""
    if not value.startswith("@"):
        return value
    ref = value[1:]
    if ref.startswith("app:"):  # '@app:worker' → the provider-level app name
        return fly_app_name(topo, ref[4:]) if provider == "fly" else ref[4:]
    target = next((s for s in topo["services"] if s["name"] == ref), None)
    if target is None:
        raise SystemExit(f"deploy_topology: env reference '@{ref}' matches no service")
    if provider == "fly":
        suffix = topo["fly"]["internal_domain_suffix"]
        return f"http://{fly_app_name(topo, ref)}{suffix}:{target['port']}"
    return f"http://{ref}:{target['port']}"  # k8s Service / compose service DNS


def service_env(topo: dict, svc: dict, provider: str) -> dict[str, str]:
    env = {"OH_BIND_HOST": "0.0.0.0"}
    for key, value in (svc.get("env") or {}).items():
        env[key] = resolve_ref(topo, value, provider)
    return env


def secret_keys(topo: dict, svc: dict) -> list[str]:
    keys: list[str] = []
    for group in svc.get("secret_groups") or []:
        keys.extend(topo["secret_group_contents"][group])
    return keys


# ---------------------------------------------------------------- fly emitter

def fly_toml(topo: dict, svc: dict) -> str:
    app = fly_app_name(topo, svc["name"])
    lines = [
        f"# {GENERATED_MARK}",
        f"# service: {svc['name']} (kind={svc['kind']})" + (f" — {svc['phase']}" if svc.get("phase") else ""),
        f'app = "{app}"',
        f'primary_region = "{topo["fly"]["primary_region"]}"',
        "",
        "[build]",
    ]
    if svc.get("image"):
        lines.append(f'  image = "{svc["image"]}"')
    else:
        lines.append(f'  dockerfile = "{topo["image"]["dockerfile"]}"  # deploy from repo root: fly deploy -c fly/{app}.fly.toml')
    lines += ["", "[processes]", f'  app = "{" ".join(svc["command"])}"'] if svc.get("command") else []
    env = service_env(topo, svc, "fly")
    if env:
        lines += ["", "[env]"]
        lines += [f'  {k} = "{v}"' for k, v in sorted(env.items())]
    secrets = secret_keys(topo, svc)
    if secrets:
        lines += ["", f"# secrets (never in this file): fly secrets set -a {app} " + " ".join(f"{k}=…" for k in secrets)]
    if svc.get("state_mount"):
        lines += ["", "[[mounts]]", f'  source = "{volume_name(svc)}"', f'  destination = "{svc["state_mount"]}"',
                  f'  initial_size = "{svc.get("volume_gb", 1)}gb"']
    if svc.get("public"):
        lines += ["", "[http_service]", f"  internal_port = {svc['port']}", "  force_https = true",
                  '  auto_stop_machines = "stop"', "  auto_start_machines = true", "  min_machines_running = 1",
                  "", "  [[http_service.checks]]", '    interval = "30s"', '    timeout = "5s"',
                  '    grace_period = "20s"', '    method = "GET"', f'    path = "{svc.get("health_path", "/")}"']
    elif svc.get("health_path") and svc.get("port"):
        lines += ["", "[checks.health]", '  type = "http"', f"  port = {svc['port']}",
                  f'  path = "{svc["health_path"]}"', '  interval = "30s"', '  timeout = "5s"',
                  '  grace_period = "20s"']
    if svc["kind"] == "burst":
        scaling = svc["scaling"]
        lines += ["", f"# burst fleet: machines are managed by the worker-controller (scale "
                      f"{scaling['min_workers']}→{scaling['max_workers']['fly']} on redis list "
                      f"'{scaling['queue_key']}', {scaling['jobs_per_worker']} jobs/worker). "
                      f"After 'fly deploy --ha=false', stop the seed machine; the controller owns the fleet."]
    lines += ["", "[[vm]]", f'  cpu_kind = "{svc.get("cpu_kind", "shared")}"', f"  cpus = {svc.get('cpus', 1)}",
              f"  memory_mb = {svc.get('memory_mb', 512)}", ""]
    return "\n".join(lines)


def fly_readme(topo: dict, order: list[dict]) -> str:
    prefix = topo["fly"]["app_prefix"]
    region = topo["fly"]["primary_region"]
    out = [f"<!-- {GENERATED_MARK} -->", "", "# Fly.io deploy — generated plan",
           "", f"Region: `{region}` (fallback `{topo['fly']['fallback_region']}`). One Fly app per service; "
               "internal services have NO public proxy and talk over the private 6PN network "
               "(`<app>.internal:<port>`). Full owner/agent runbook: `docs/architecture/fly-deploy-runbook.md`.",
           "", "Deploy order (dependencies first):", ""]
    step_no = 0
    for svc in order:
        app = f"{prefix}-{svc['name']}"
        if svc.get("providers") and "fly" not in svc["providers"]:
            continue
        step_no += 1
        steps = [f"fly apps create {app}"]
        if svc.get("state_mount"):
            steps.append(f"fly volumes create {volume_name(svc)} -a {app} -r {region} -s {svc.get('volume_gb', 1)}")
        secrets = secret_keys(topo, svc)
        if secrets:
            steps.append(f"fly secrets set -a {app} --stage " + " ".join(f"{k}=<value>" for k in secrets))
        steps.append(f"fly deploy -c fly/{app}.fly.toml --ha=false")
        if svc["kind"] == "burst":
            steps.append(f"fly machine list -a {app} -q | xargs -r -n1 fly machine stop -a {app}  "
                         f"# controller owns the fleet from here")
        out.append(f"## {step_no}. {app}" + (f" — {svc['phase']}" if svc.get("phase") else ""))
        out += ["", "```bash", *steps, "```", ""]
    out += ["After deploys: point Cloudflare DNS at the public apps (CNAME → <app>.fly.dev, proxied), "
            "then run the public gates (e2e/ohh_public_gate.mjs, e2e/teleon_gate.mjs) against the domains.", ""]

    worker_app = fly_app_name(topo, "worker")
    stateful = [s for s in stateful_services(topo) if not (s.get("providers") and "fly" not in s["providers"])]
    out += [
        "## Scheduled feeder (keep the worker queue fed)", "",
        f"The worker fleet drains the `{DEFAULT_QUEUE_KEY}` queue; feed it on a schedule with Fly "
        f"scheduled machines on the worker app (run from the repo root — `.` builds "
        f"`{topo['image']['dockerfile']}`; or pass the app's currently deployed image ref instead):", "",
        "```bash",
        f'fly machine run . --schedule {FEEDER_SCHEDULE} -a {worker_app} --command "python -m scripts.foundry.seeds --enqueue"',
        f'fly machine run . --schedule {FEEDER_SCHEDULE} -a {worker_app} --command "python -m scripts.ingest.freshness --check --enqueue"',
        "```", "",
        "`seeds --enqueue` puts one partition job per research-queue area on the broker (add "
        "`--with-fixture` for a guaranteed-promoting smoke partition); `freshness --check --enqueue` "
        "polls every registered source (CDC) and enqueues a `reingest` job per new/changed source — "
        "the worker re-feeds it through `scripts.ingest.feed`.", "",
        "## Single-machine law (stateful apps)", "",
        "Every app below owns SINGLE-WRITER state (JSON/JSONL/SQLite on its volume). Never "
        "`fly scale count >1` on any of them — a second machine gets a second empty volume and forks "
        "the state; `--ha=false` at deploy time is mandatory, not an optimization. Scale these UP "
        "(bigger VM), never OUT:", "",
        *[f"- `{fly_app_name(topo, s['name'])}` — single-writer state at `{s['state_mount']}` "
          f"(volume `{volume_name(s)}`)" for s in stateful],
        "",
        "## Volume snapshots (+ off-provider backup)", "",
        f"Fly bills snapshot storage — pin retention to {VOLUME_SNAPSHOT_RETENTION_DAYS} days on every "
        "volume (`fly volumes list -a <app>` shows the volume id):", "",
        "```bash",
        *[f"fly volumes update <{volume_name(s)}-id> --snapshot-retention {VOLUME_SNAPSHOT_RETENTION_DAYS}"
          f"  # app {fly_app_name(topo, s['name'])}, volume {volume_name(s)}" for s in stateful],
        "```", "",
        "Snapshots live on the same provider as the volumes — also run a nightly off-provider backup "
        "(e.g. a scheduled machine running restic from each state mount to Cloudflare R2 or Backblaze "
        "B2) so a provider/account-level incident can't take the state and its only copies together.", "",
    ]
    return "\n".join(out)


# ---------------------------------------------------------------- compose emitter

def _compose_services(topo: dict) -> list[dict]:
    """Compose-eligible services (fly-only roles like the worker-controller have no compose analog)."""
    return [s for s in topo["services"]
            if not (s.get("providers") and set(s["providers"]) == {"fly"})]


def _dep_graph(topo: dict) -> dict[str, list[str]]:
    """service → the compose services it references via '@<service>' env refs (sorted, deterministic)."""
    names = {s["name"] for s in _compose_services(topo)}
    graph: dict[str, list[str]] = {}
    for s in _compose_services(topo):
        deps = {v[1:] for v in (s.get("env") or {}).values()
                if isinstance(v, str) and v.startswith("@") and not v.startswith("@app:")}
        graph[s["name"]] = sorted(d for d in deps if d in names)
    return graph


def _acyclic_deps(graph: dict[str, list[str]]) -> tuple[dict[str, list[str]], list[tuple[str, str]]]:
    """Break dependency cycles so docker-compose accepts the graph (it rejects ANY cyclic depends_on).

    compose `depends_on` is start-ORDER only. The env @-refs that can form a cycle here are RUNTIME
    seams — e.g. identity pushes verify-mail to mailbox (best-effort, swallowed) while mailbox calls
    identity to complete an on-demand verify click — so neither is a startup requirement and the
    cycle-closing edge is safe to drop. Deterministic DFS back-edge removal over sorted nodes/edges,
    so the same topology always drops the same edge. Returns (kept_deps, dropped_edges)."""
    WHITE, GRAY, BLACK = 0, 1, 2
    color = {n: WHITE for n in graph}
    kept: dict[str, list[str]] = {n: [] for n in graph}
    dropped: list[tuple[str, str]] = []

    def visit(u: str) -> None:
        color[u] = GRAY
        for v in graph.get(u, []):
            if color.get(v) == GRAY:          # back-edge → closes a cycle → drop it
                dropped.append((u, v))
                continue
            kept[u].append(v)
            if color.get(v) == WHITE:
                visit(v)
        color[u] = BLACK

    for n in sorted(graph):
        if color[n] == WHITE:
            visit(n)
    return kept, dropped


def _compose_has_cycle(compose_text: str) -> bool:
    """Independently parse the EMITTED compose's depends_on edges and report whether they cycle.
    docker-compose rejects ANY cyclic depends_on, so this is the gate that catches a cycle BEFORE
    deploy even if _acyclic_deps ever regresses — defense-in-depth for the exact bug that only
    container start-up (not --check/preflight) first surfaced."""
    graph: dict[str, list[str]] = {}
    cur = None
    in_services = False
    for line in compose_text.splitlines():
        if re.match(r"^services:\s*$", line):
            in_services = True; continue
        if re.match(r"^[A-Za-z]", line):       # a new top-level key (volumes:, name:) ends services
            in_services = False; continue
        if not in_services:
            continue
        m = re.match(r"^  ([A-Za-z0-9_-]+):\s*$", line)
        if m:
            cur = m.group(1); graph.setdefault(cur, [])
            continue
        m = re.match(r"^    depends_on:\s*(\[.*\])\s*$", line)
        if m and cur:
            try:
                graph[cur] = list(json.loads(m.group(1)))
            except (ValueError, TypeError):
                graph[cur] = []
    WHITE, GRAY, BLACK = 0, 1, 2
    color = {n: WHITE for n in graph}

    def walk(u: str) -> bool:
        color[u] = GRAY
        for v in graph.get(u, []):
            if v not in color:        # edge to a non-service (shouldn't happen) — ignore
                continue
            if color[v] == GRAY or (color[v] == WHITE and walk(v)):
                return True
        color[u] = BLACK
        return False

    return any(color[n] == WHITE and walk(n) for n in sorted(graph))


def compose_yaml(topo: dict) -> str:
    """The same plane as plain docker-compose — parity proof and the any-VPS escape hatch."""
    dep_map, dropped_edges = _acyclic_deps(_dep_graph(topo))
    lines = [f"# {GENERATED_MARK}",
             "# Run from repo root: docker compose -f deploy/docker-compose.deploy.yml up",
             "# Worker fleet: --profile workers (scaled manually here; KEDA on k8s / controller on Fly)."]
    for (u, v) in dropped_edges:  # surfaced, never silent: the cycle-closing start-order hint we dropped
        lines.append(f"# depends_on {u}→{v} omitted: runtime seam (best-effort/on-demand) that would "
                     "form a start-order cycle; compose depends_on is ordering only.")
    lines += ["name: aidoneright", "services:"]
    volumes: list[str] = []
    for svc in topo["services"]:
        if svc.get("providers") and set(svc["providers"]) == {"fly"}:
            continue  # fly-only roles (worker-controller) have no compose analog
        lines.append(f"  {svc['name']}:")
        if svc.get("image"):
            lines.append(f"    image: {svc['image']}")
        else:
            lines.append("    build: { context: .., dockerfile: Dockerfile }")
        if svc.get("command"):
            lines.append("    command: " + json.dumps(svc["command"]))
        env = service_env(topo, svc, "compose")
        for group in svc.get("secret_groups") or []:
            if group in ("queue-stores", "baltor-stores"):
                env.setdefault("REDIS_URL", "redis://redis:6379/0")
        if svc["name"] == "postgres":
            env.setdefault("POSTGRES_PASSWORD", "${POSTGRES_PASSWORD:?set in .env}")
        if env:
            lines.append("    environment:")
            lines += [f"      {k}: {json.dumps(v)}" for k, v in sorted(env.items())]
        if svc.get("public"):
            lines.append(f'    ports: ["{svc["port"]}:{svc["port"]}"]')
        if svc.get("state_mount"):
            volume = volume_name(svc)
            volumes.append(volume)
            lines.append(f"    volumes: [{volume}:{svc['state_mount']}]")
        deps = list(dep_map.get(svc["name"], []))  # cycle-broken (see _acyclic_deps)
        if svc["kind"] == "burst":
            deps = sorted(set(deps) | {"redis"})
            lines.append("    profiles: [workers]")
        if svc.get("phase"):
            lines.append("    profiles: [phase2]")
        if deps:
            lines.append("    depends_on: " + json.dumps(deps))
        lines.append("    restart: unless-stopped")
    lines.append("volumes:")
    lines += [f"  {v}:" for v in sorted(set(volumes))]
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------- opentofu emitter (cloudflare plane)

def _tf_name(name: str) -> str:
    """A valid OpenTofu/HCL resource label from a service name (deterministic)."""
    return re.sub(r"[^a-z0-9_]", "_", name.lower())


def tofu_main_tf(topo: dict) -> str:
    """Cloudflare provisioning rendered from the SAME topology as fly/ + compose (the doc's 'add an emitter here').

    Emits exactly the two Cloudflare things this topology implies and the Fly runbook otherwise leaves MANUAL:
      * a proxied CNAME per PUBLIC service  (the 'point Cloudflare DNS at the public apps' step), and
      * one R2 bucket per stateful service  (the off-provider state backup the runbook recommends).
    Inert until `tofu apply`; `tofu plan` is the reviewable gate. The token is a SecretRef (TF_VAR_*), never committed."""
    domain_default = topo["fly"].get("public_domain_suffix", "fly.dev")
    public = [s for s in topo["services"] if s.get("public")]
    stateful = stateful_services(topo)
    lines = [
        f"# {GENERATED_MARK}",
        "# Cloudflare plane rendered from architecture/deploy_topology.json — the SAME single source as fly/ + compose",
        "# (no magic values). Provisioning ONLY (DNS + R2); per-request compute stays in the dispatch layer. Inert",
        "# until `tofu apply`; run `tofu plan` first as the gate. Switch/extend providers = add another emitter, never",
        "# a second source of truth.", "",
        "terraform {",
        '  required_version = ">= 1.6"  # OpenTofu',
        "  required_providers {",
        '    cloudflare = { source = "cloudflare/cloudflare", version = "~> 5" }',
        "  }",
        "  # Remote state on R2 (uncomment AFTER a state bucket exists; S3-compatible creds via env):",
        '  # backend "s3" { /* R2 endpoint + bucket; see README.generated.md */ }',
        "}", "",
        'provider "cloudflare" {',
        "  api_token = var.cloudflare_api_token",
        "}", "",
        "# ---- inputs (set via TF_VAR_* env or a gitignored *.tfvars — the token is a SecretRef, never committed) ----",
        'variable "cloudflare_api_token" {',
        "  type        = string",
        "  sensitive   = true",
        '  description = "Cloudflare API token (Zone:DNS:Edit + Workers R2 Storage:Edit). Set TF_VAR_cloudflare_api_token."',
        "}",
        'variable "account_id" {',
        "  type        = string",
        '  description = "Cloudflare account id"',
        "}",
        'variable "zone_id" {',
        "  type        = string",
        '  description = "Cloudflare DNS zone id for the public domain"',
        "}",
        'variable "fly_app_domain" {',
        "  type        = string",
        f'  default     = "{domain_default}"',
        '  description = "CNAME target suffix; a public app routes to <app>.<domain>"',
        "}", "",
        "# ---- public surfaces: a proxied CNAME per public service (the DNS step the Fly runbook leaves manual) ----",
    ]
    for s in public:
        app = fly_app_name(topo, s["name"])
        rn = _tf_name(s["name"])
        lines += [f'resource "cloudflare_dns_record" "{rn}" {{',
                  "  zone_id = var.zone_id",
                  f'  name    = "{s["name"]}"',
                  '  type    = "CNAME"',
                  f'  content = "{app}.${{var.fly_app_domain}}"',
                  "  proxied = true",
                  "  ttl     = 1  # automatic (required when proxied)",
                  "}", ""]
    if not public:
        lines += ['# (no public services in the topology yet — mark one with "public": true)', ""]
    lines += ["# ---- off-provider state backup: one R2 bucket per single-writer stateful service ----"]
    for s in stateful:
        app = fly_app_name(topo, s["name"])
        rn = _tf_name(s["name"])
        lines += [f'resource "cloudflare_r2_bucket" "{rn}_state_backup" {{',
                  "  account_id = var.account_id",
                  f'  name       = "{app}-state-backup"',
                  "}", ""]
    lines += ['output "public_hostnames" {',
              "  value = {",
              *[f'    {_tf_name(s["name"])} = cloudflare_dns_record.{_tf_name(s["name"])}.name' for s in public],
              "  }",
              "}", ""]
    return "\n".join(lines)


def tofu_readme(topo: dict) -> str:
    public = [s for s in topo["services"] if s.get("public")]
    stateful = stateful_services(topo)
    return "\n".join([
        f"<!-- {GENERATED_MARK} -->", "", "# Cloudflare (OpenTofu) — generated plan", "",
        "OpenTofu is the open-source (MPL-2.0, Linux Foundation) Terraform fork. This module provisions the Cloudflare",
        "plane for the public demo surface — rendered from `architecture/deploy_topology.json`, the same single source",
        "as `fly/` and the compose file. It is PROVISIONING only (DNS + R2 backup buckets); per-request worker compute",
        "stays in the dispatch layer (`src/teleon/runtime/dispatch.py`), and customer BYO compute stays API-key based —",
        "never run this against a customer account.", "",
        f"It manages **{len(public)} proxied CNAME(s)** (public services) and **{len(stateful)} R2 backup bucket(s)** "
        "(one per stateful service).", "",
        "## Apply (the plan is the gate)", "", "```bash",
        "cd deploy/tofu/cloudflare",
        "export TF_VAR_cloudflare_api_token=<token>   # Zone:DNS:Edit + Workers R2 Storage:Edit (a SecretRef; never commit it)",
        "export TF_VAR_account_id=<account-id>",
        "export TF_VAR_zone_id=<zone-id>",
        "tofu init",
        "tofu plan      # REVIEW this diff — it is the change-verification gate (like the fly/compose --check)",
        "tofu apply     # only after the plan reads correctly",
        "```", "",
        "## Notes",
        "- Re-generate (never hand-edit): `python3 scripts/deploy/generate_provider_configs.py`; drift-checked by `--check`.",
        "- State can live in R2 (S3-compatible) — uncomment the `backend \"s3\"` block in `main.tf` after the bucket exists.",
        "- This does NOT replace the Fly deploy (`fly/README.generated.md`); it adds the Cloudflare DNS/R2 layer in front.",
        "",
    ])


# ---------------------------------------------------------------- k8s cross-checks

def check_k8s(topo: dict, repo: Path = REPO) -> list[str]:
    """The K8s manifests stay hand-maintained (they predate this generator) but may not drift
    from the topology on the facts both share. Returns a list of mismatch messages."""
    problems: list[str] = []
    checks = topo["k8s_cross_checks"]
    plane = (repo / checks["service_plane_file"])
    if plane.is_file():
        text = plane.read_text(encoding="utf-8")
        for name in checks["service_plane_must_contain_deployments"]:
            if f"name: {name}" not in text:
                problems.append(f"{checks['service_plane_file']}: missing Deployment/Service '{name}'")
        if "OH_BIND_HOST" not in text:
            problems.append(f"{checks['service_plane_file']}: no OH_BIND_HOST env — pods would bind 127.0.0.1 and be unreachable")
    else:
        problems.append(f"{checks['service_plane_file']}: file missing")
    worker = (repo / checks["worker_file"])
    scaling = next(s for s in topo["services"] if s["name"] == "worker")["scaling"]
    if worker.is_file():
        text = worker.read_text(encoding="utf-8")
        expectations = {
            f'listName: "{scaling["queue_key"]}"': "queue key",
            f'listLength: "{scaling["jobs_per_worker"]}"': "jobs per worker",
            f"maxReplicaCount: {scaling['max_workers']['k8s']}": "max workers (k8s)",
            f"pollingInterval: {scaling['poll_seconds']}": "poll seconds",
            f"cooldownPeriod: {scaling['cooldown_seconds']}": "cooldown seconds",
        }
        for needle, label in expectations.items():
            if needle not in text:
                problems.append(f"{checks['worker_file']}: {label} drifted from deploy_topology ({needle!r} not found)")
    else:
        problems.append(f"{checks['worker_file']}: file missing")
    # stray hand-typed queue-key copies: every watched file must carry the canonical key,
    # so changing the topology key fails loudly everywhere instead of silently forking queues
    for rel in checks.get("queue_key_watch_files", []):
        watched = repo / rel
        if not watched.is_file():
            problems.append(f"{rel}: queue-key watch file missing")
        elif scaling["queue_key"] not in watched.read_text(encoding="utf-8"):
            problems.append(f"{rel}: does not carry the canonical queue key {scaling['queue_key']!r} — "
                            f"stale copy (update it or drop it from queue_key_watch_files)")
    return problems


# ---------------------------------------------------------------- generate / check

def render_all(topo: dict) -> dict[Path, str]:
    order = [s for s in topo["services"]]  # topology order IS the dependency order
    out: dict[Path, str] = {}
    for svc in topo["services"]:
        if svc.get("providers") and "fly" not in svc["providers"]:
            continue
        out[FLY_DIR / f"{fly_app_name(topo, svc['name'])}.fly.toml"] = fly_toml(topo, svc)
    out[FLY_DIR / "README.generated.md"] = fly_readme(topo, order)
    out[COMPOSE_PATH] = compose_yaml(topo)
    out[TOFU_DIR / "main.tf"] = tofu_main_tf(topo)
    out[TOFU_DIR / "README.generated.md"] = tofu_readme(topo)
    return out


def generate() -> int:
    topo = load_topology()
    problems = check_k8s(topo)
    if problems:
        print("K8S CROSS-CHECK FAILURES (fix manifests or topology — same facts, one source):")
        for p in problems:
            print(f"  ✗ {p}")
        return 1
    rendered = render_all(topo)
    FLY_DIR.mkdir(exist_ok=True)
    COMPOSE_PATH.parent.mkdir(exist_ok=True)
    TOFU_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in rendered.items():
        path.write_text(content, encoding="utf-8")
        print(f"  wrote {path.relative_to(REPO)}")
    print(f"PASS — {len(rendered)} provider configs generated from {TOPOLOGY_PATH.relative_to(REPO)}")
    return 0


def check() -> int:
    topo = load_topology()
    problems = check_k8s(topo)
    rendered = render_all(topo)
    for path, expected in rendered.items():
        actual = path.read_text(encoding="utf-8") if path.is_file() else None
        if actual is None:
            problems.append(f"{path.relative_to(REPO)}: missing — run the generator")
        elif actual != expected:
            diff = list(difflib.unified_diff(actual.splitlines(), expected.splitlines(), lineterm="", n=1))
            problems.append(f"{path.relative_to(REPO)}: drifted from topology ({len(diff)} diff lines; first: "
                            f"{next((d for d in diff if d.startswith(('+', '-')) and not d.startswith(('+++', '---'))), '')!r})")
    if problems:
        print("CHECK FAILURES:")
        for p in problems:
            print(f"  ✗ {p}")
        return 1
    print(f"PASS — fly/ + compose + cloudflare-tofu match {TOPOLOGY_PATH.relative_to(REPO)}; k8s cross-checks green")
    return 0


# ---------------------------------------------------------------- self-test

def self_test() -> int:
    topo = load_topology()
    rendered = render_all(topo)
    web = rendered[FLY_DIR / f"{fly_app_name(topo, 'web-harness-hub')}.fly.toml"]
    identity = rendered[FLY_DIR / f"{fly_app_name(topo, 'identity')}.fly.toml"]
    worker = rendered[FLY_DIR / f"{fly_app_name(topo, 'worker')}.fly.toml"]
    compose = rendered[COMPOSE_PATH]
    readme = rendered[FLY_DIR / "README.generated.md"]
    tofu = rendered[TOFU_DIR / "main.tf"]
    stateful = stateful_services(topo)
    checks = [
        ("web app is public", "[http_service]" in web and "min_machines_running = 1" in web),
        ("web seams resolve to fly .internal bases",
         'OH_SEAM_IDENTITY_BASE = "http://aidr-identity.internal:9410"' in web
         and 'OH_SEAM_LIVEOPS_BASE = "http://aidr-baltor-backend.internal:9301"' in web),
        ("internal service has no public proxy", "[http_service]" not in identity and "[checks.health]" in identity),
        ("every service binds 0.0.0.0 in containers", all('OH_BIND_HOST = "0.0.0.0"' in t
         for p, t in rendered.items() if p.suffix == ".toml" and "[processes]" in t)),
        ("worker has no proxy and no checks (controller-managed)",
         "[http_service]" not in worker and "[checks.health]" not in worker),
        ("controller is fly-only (absent from compose)", "worker-controller" not in compose),
        ("compose seams resolve to service DNS", '"http://identity:9410"' in compose),
        ("compose wires worker REDIS_URL to the redis service", '"redis://redis:6379/0"' in compose),
        ("generated compose has NO dependency cycle (compose rejects cycles — the deploy-blocker "
         "only container start-up first caught)", not _compose_has_cycle(compose)),
        ("...and the cycle detector actually fires on a planted cycle (not a silent no-op)",
         _compose_has_cycle('services:\n  a:\n    depends_on: ["b"]\n  b:\n    depends_on: ["a"]\n')),
        ("no secret VALUES leak into any generated file", all(
            tok not in content for content in rendered.values()
            for tok in ("sk-or-", "OH_LLM_API_KEY ="))),
        ("k8s cross-checks pass on the real manifests", not check_k8s(topo)),
        ("queue key single-sourced", topo and DEFAULT_QUEUE_KEY == "ohh:foundry:jobs"),
        ("README: scheduled feeder uses the REAL seeds/freshness CLI flags",
         f'--schedule {FEEDER_SCHEDULE} -a {fly_app_name(topo, "worker")} --command '
         f'"python -m scripts.foundry.seeds --enqueue"' in readme
         and '--command "python -m scripts.ingest.freshness --check --enqueue"' in readme),
        ("README: single-machine law names every stateful app",
         "`fly scale count >1`" in readme
         and all(f"`{fly_app_name(topo, s['name'])}` — single-writer state" in readme for s in stateful)),
        ("README: one snapshot-retention line per stateful volume + off-provider backup note",
         readme.count("--snapshot-retention") == len(stateful)
         and f"--snapshot-retention {VOLUME_SNAPSHOT_RETENTION_DAYS}" in readme and "restic" in readme),
        # OPENTOFU emitter (cloudflare) — same single source, one more provider, no lock-in
        ("tofu: cloudflare provider pinned + OpenTofu version floor", 'source = "cloudflare/cloudflare"' in tofu and 'required_version = ">= 1.6"' in tofu),
        ("tofu: a proxied CNAME per public service -> the fly app domain (one source)",
         all((f'resource "cloudflare_dns_record" "{_tf_name(s["name"])}"' in tofu and "proxied = true" in tofu
              and f'content = "{fly_app_name(topo, s["name"])}.${{var.fly_app_domain}}"' in tofu)
             for s in topo["services"] if s.get("public"))),
        ("tofu: an R2 backup bucket per stateful service",
         all(f'name       = "{fly_app_name(topo, s["name"])}-state-backup"' in tofu for s in stateful)),
        ("tofu: the API token is a sensitive SecretRef var (never inlined)", "sensitive   = true" in tofu and "var.cloudflare_api_token" in tofu),
        ("tofu: provisioning only — no per-request compute leaks into IaC", "dispatch layer" in rendered[TOFU_DIR / "README.generated.md"]),
    ]
    # drift detection actually fires
    with tempfile.TemporaryDirectory() as tmp:
        sample = Path(tmp) / "sample.toml"
        sample.write_text(web + "\n# tampered", encoding="utf-8")
        checks.append(("tampered output differs from render", sample.read_text(encoding="utf-8") != web))
    failed = [name for name, ok in checks if not ok]
    for name, ok in checks:
        print(f"  [{'ok' if ok else 'FAIL'}] {name}")
    print(("PASS — " if not failed else "FAIL — ") + f"{len(checks) - len(failed)}/{len(checks)} self-test checks")
    return 1 if failed else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="verify generated files + k8s match the topology")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args(argv)
    if args.self_test:
        return self_test()
    if args.check:
        return check()
    return generate()


if __name__ == "__main__":
    raise SystemExit(main())
