"""Deterministic ComponentCard -> PipelinePlan compiler for Teleon.

Purpose: let an LLM propose a compact graph of primitive/component ids while this module performs the
non-negotiable work: validate contracts, derive ordering, enforce side-effect gates, and emit a locked
execution manifest. The LLM is a planner/explainer; this compiler is the builder. All outputs are
candidate evidence (`serves_truth=false`) until a separate executor/proof/promotion gate verifies them.
"""
from __future__ import annotations

import hashlib
import json
from collections import defaultdict, deque


py_const_src_teleon_synthesis_component_plan_compiler__SERVES_TRUTH = False
py_const_src_teleon_synthesis_component_plan_compiler__COMPILER_VERSION = "0.1.0"
py_const_src_teleon_synthesis_component_plan_compiler__REQUIRED_COMPONENT_CARD_FIELDS = {
    "component_id",
    "version",
    "purpose",
    "input_contract",
    "output_contract",
    "runtime",
    "policy",
    "proofs",
    "serves_truth",
}
py_const_src_teleon_synthesis_component_plan_compiler__ALLOWED_BINDING_ROOTS = {"$task", "$system", "$nodes"}
py_const_src_teleon_synthesis_component_plan_compiler__SIDE_EFFECT_TAGS = {"side_effect", "external_api_call", "delivery", "write", "email"}
py_const_src_teleon_synthesis_component_plan_compiler__LOCK_FIELDS = (
    "execution_plan_id",
    "pipeline_name",
    "compiler_version",
    "ordered_nodes",
    "locked_components",
    "policy_report",
    "component_registry_snapshot",
    "random_seed_strategy",
    "serves_truth",
)


def py_function_src_teleon_synthesis_component_plan_compiler__stable_json(py_arg_value) -> str:
    """Return deterministic JSON for lock ids and provenance diffs."""
    return json.dumps(py_arg_value, sort_keys=True, separators=(",", ":"), default=repr)


def py_function_src_teleon_synthesis_component_plan_compiler__stable_digest(py_arg_value) -> str:
    """Return a short deterministic digest for registry snapshots and lock ids."""
    return hashlib.sha256(
        py_function_src_teleon_synthesis_component_plan_compiler__stable_json(py_arg_value).encode("utf-8")
    ).hexdigest()


def py_function_src_teleon_synthesis_component_plan_compiler__parse_component_ref(py_arg_ref: str) -> tuple[str, str | None]:
    """Parse `component.id@version` into `(component_id, version)`.

    A missing version is allowed in the input plan, but the compiler resolves the exact version from the
    registry and records it in the lockfile.
    """
    if "@" not in py_arg_ref:
        return py_arg_ref, None
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__parse_component_ref__py_var_component_id, py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__parse_component_ref__py_var_version = py_arg_ref.rsplit("@", 1)
    return py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__parse_component_ref__py_var_component_id, py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__parse_component_ref__py_var_version


def py_function_src_teleon_synthesis_component_plan_compiler__contract_fields(py_arg_contract: dict) -> set[str]:
    """Extract deterministic field names from a lightweight input/output contract."""
    if not isinstance(py_arg_contract, dict):
        return set()
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__contract_fields__py_var_fields = py_arg_contract.get("fields") or py_arg_contract.get("properties") or {}
    if isinstance(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__contract_fields__py_var_fields, dict):
        return set(str(py_var_key) for py_var_key in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__contract_fields__py_var_fields)
    if isinstance(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__contract_fields__py_var_fields, list):
        return set(str(py_var_key) for py_var_key in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__contract_fields__py_var_fields)
    return set()


def py_function_src_teleon_synthesis_component_plan_compiler__contract_shape(py_arg_contract: dict) -> str:
    """Extract a coarse shape/type from a lightweight contract."""
    if not isinstance(py_arg_contract, dict):
        return "unknown"
    return str(py_arg_contract.get("shape") or py_arg_contract.get("type") or py_arg_contract.get("kind") or "unknown")


def py_function_src_teleon_synthesis_component_plan_compiler__component_key(py_arg_card: dict) -> str:
    return f"{py_arg_card['component_id']}@{py_arg_card['version']}"


def py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards(
    py_arg_component_cards: list[dict],
) -> tuple[dict[str, dict], list[str]]:
    """Validate and index ComponentCards by id and id@version."""
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_index: dict[str, dict] = {}
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_errors: list[str] = []
    for py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_card in py_arg_component_cards:
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_missing = sorted(py_const_src_teleon_synthesis_component_plan_compiler__REQUIRED_COMPONENT_CARD_FIELDS - set(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_card))
        if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_missing:
            py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_errors.append(f"component card missing fields {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_missing}: {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_card.get('component_id')}")
            continue
        if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_card.get("serves_truth") is not False:
            py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_errors.append(f"component card may not serve truth: {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_card.get('component_id')}")
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_key = py_function_src_teleon_synthesis_component_plan_compiler__component_key(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_card)
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_index[py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_key] = py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_card
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_index.setdefault(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_card["component_id"], py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_card)
    return py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_index, py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards__py_var_errors


def py_function_src_teleon_synthesis_component_plan_compiler__binding_dependency(py_arg_source: str) -> tuple[str | None, str | None]:
    """Return `(node_id, output_name)` for `$nodes.<node>.outputs.<field>` bindings."""
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__binding_dependency__py_var_parts = py_arg_source.split(".")
    if len(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__binding_dependency__py_var_parts) >= 4 and py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__binding_dependency__py_var_parts[0] == "$nodes" and py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__binding_dependency__py_var_parts[2] == "outputs":
        return py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__binding_dependency__py_var_parts[1], py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__binding_dependency__py_var_parts[3]
    return None, None


def py_function_src_teleon_synthesis_component_plan_compiler__validate_binding_source(py_arg_source: str) -> bool:
    return any(py_arg_source == py_var_root or py_arg_source.startswith(f"{py_var_root}.") for py_var_root in py_const_src_teleon_synthesis_component_plan_compiler__ALLOWED_BINDING_ROOTS)


def py_function_src_teleon_synthesis_component_plan_compiler__topological_order(
    py_arg_nodes: list[dict],
    py_arg_extra_edges: list[tuple[str, str]] | None = None,
) -> tuple[list[str], list[str]]:
    """Return deterministic topological node order and validation errors."""
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node_ids = [py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node["id"] for py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node in py_arg_nodes]
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node_id_set = set(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node_ids)
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_edges: dict[str, set[str]] = defaultdict(set)
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_indegree: dict[str, int] = {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node_id: 0 for py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node_id in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node_ids}
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_errors: list[str] = []
    for py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node in py_arg_nodes:
        for py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_parent in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node.get("after", []):
            if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_parent not in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node_id_set:
                py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_errors.append(f"node {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node['id']} depends on missing node {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_parent}")
                continue
            if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node["id"] not in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_edges[py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_parent]:
                py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_edges[py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_parent].add(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node["id"])
                py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_indegree[py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node["id"]] += 1
    for py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_parent, py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_child in py_arg_extra_edges or []:
        if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_parent not in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node_id_set or py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_child not in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node_id_set:
            py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_errors.append(f"binding edge references missing node {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_parent}->{py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_child}")
            continue
        if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_child not in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_edges[py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_parent]:
            py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_edges[py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_parent].add(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_child)
            py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_indegree[py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_child] += 1
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_ready = deque(sorted(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node_id for py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node_id, py_var_degree in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_indegree.items() if py_var_degree == 0))
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_order: list[str] = []
    while py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_ready:
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node_id = py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_ready.popleft()
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_order.append(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node_id)
        for py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_child in sorted(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_edges.get(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node_id, [])):
            py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_indegree[py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_child] -= 1
            if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_indegree[py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_child] == 0:
                py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_ready.append(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_child)
    if len(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_order) != len(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_node_ids):
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_errors.append("cycle detected in pipeline plan")
    return py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_order, py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__topological_order__py_var_errors


def py_function_src_teleon_synthesis_component_plan_compiler__node_has_side_effect(py_arg_card: dict, py_arg_node: dict) -> bool:
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__node_has_side_effect__py_var_tags = {str(py_var_tag).lower() for py_var_tag in py_arg_card.get("side_effects", [])}
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__node_has_side_effect__py_var_tags |= {str(py_var_tag).lower() for py_var_tag in py_arg_node.get("tags", [])}
    return bool(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__node_has_side_effect__py_var_tags & py_const_src_teleon_synthesis_component_plan_compiler__SIDE_EFFECT_TAGS) or bool(py_arg_node.get("side_effect"))


def py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan(
    py_arg_pipeline_plan: dict,
    py_arg_component_cards: list[dict],
    py_arg_retrieved_component_ids: set[str] | None = None,
) -> dict:
    """Validate a candidate PipelinePlan and emit a deterministic lockfile-shaped dict.

    The lock is the only artifact an executor should run. If validation fails, the returned envelope has
    `ok=false`, `errors=[...]`, and still `serves_truth=false`.
    """
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_index, py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_errors = py_function_src_teleon_synthesis_component_plan_compiler__index_component_cards(py_arg_component_cards)
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_nodes = list(py_arg_pipeline_plan.get("nodes", []))
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_by_id = {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node.get("id"): py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node for py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_nodes}
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_cards: dict[str, dict] = {}
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_binding_edges: list[tuple[str, str]] = []
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_gate_nodes: dict[str, str] = {}
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_retrieved = set(py_arg_retrieved_component_ids or [])

    if len(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_by_id) != len(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_nodes):
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_errors.append("node ids must be unique")
    for py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_nodes:
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_id = py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node.get("id")
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_component_ref = py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node.get("component") or py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node.get("component_id")
        if not py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_id or not py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_component_ref:
            py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_errors.append(f"node missing id/component: {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node}")
            continue
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_component_id, py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_version = py_function_src_teleon_synthesis_component_plan_compiler__parse_component_ref(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_component_ref)
        if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_retrieved and py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_component_id not in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_retrieved and py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_component_ref not in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_retrieved:
            py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_errors.append(f"component was not in retrieved candidate set: {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_component_ref}")
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card = py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_index.get(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_component_ref) or py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_index.get(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_component_id)
        if not py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card:
            py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_errors.append(f"unknown component: {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_component_ref}")
            continue
        if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_version and py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card.get("version") != py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_version:
            py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_errors.append(f"version mismatch for {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_component_id}: requested {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_version}, found {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card.get('version')}")
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_cards[py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_id] = py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_input_fields = py_function_src_teleon_synthesis_component_plan_compiler__contract_fields(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card.get("input_contract", {}))
        for py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_input_name, py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_source in (py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node.get("bindings") or {}).items():
            if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_input_fields and py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_input_name not in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_input_fields:
                py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_errors.append(f"node {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_id} binds undeclared input {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_input_name}")
            if not py_function_src_teleon_synthesis_component_plan_compiler__validate_binding_source(str(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_source)):
                py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_errors.append(f"node {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_id} has invalid binding source {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_source}")
            py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_parent_node_id, py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_output_name = py_function_src_teleon_synthesis_component_plan_compiler__binding_dependency(str(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_source))
            if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_parent_node_id:
                if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_parent_node_id not in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_by_id:
                    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_errors.append(f"node {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_id} binds from missing node {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_parent_node_id}")
                else:
                    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_parent_card = py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_cards.get(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_parent_node_id)
                    if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_parent_card:
                        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_output_fields = py_function_src_teleon_synthesis_component_plan_compiler__contract_fields(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_parent_card.get("output_contract", {}))
                        if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_output_fields and py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_output_name not in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_output_fields:
                            py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_errors.append(f"node {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_id} binds missing output {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_output_name} from {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_parent_node_id}")
                    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_binding_edges.append((py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_parent_node_id, py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_id))
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_gate_id = py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node.get("gate") or py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card.get("policy", {}).get("gate_id")
        if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_gate_id:
            py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_gate_nodes[str(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_gate_id)] = py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_id

    for py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_id, py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_cards.items():
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node = py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_by_id[py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_id]
        if not py_function_src_teleon_synthesis_component_plan_compiler__node_has_side_effect(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card, py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node):
            continue
        for py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_required_gate in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card.get("policy", {}).get("requires_before_side_effect", []):
            py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_gate_node_id = py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_gate_nodes.get(str(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_required_gate))
            if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_gate_node_id:
                py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_binding_edges.append((py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_gate_node_id, py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_id))

    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_order, py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_order_errors = py_function_src_teleon_synthesis_component_plan_compiler__topological_order(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_nodes, py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_binding_edges)
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_errors.extend(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_order_errors)
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_gates_seen: set[str] = set()
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_locked_components: dict[str, dict] = {}
    for py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_id in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_order:
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node = py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_by_id[py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_id]
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card = py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_cards.get(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_id)
        if not py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card:
            continue
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_required_before = set(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card.get("policy", {}).get("requires_before_side_effect", []))
        if py_function_src_teleon_synthesis_component_plan_compiler__node_has_side_effect(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card, py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node):
            py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_missing_gates = sorted(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_required_before - py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_gates_seen)
            if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_missing_gates:
                py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_errors.append(f"side-effect node {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_id} missing prior gates {py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_missing_gates}")
        if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node.get("gate") or py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card.get("policy", {}).get("gate_id"):
            py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_gates_seen.add(str(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node.get("gate") or py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card.get("policy", {}).get("gate_id")))
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_locked_components[py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_node_id] = {
            "component_id": py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card["component_id"],
            "version": py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card["version"],
            "source_sha256": py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card.get("source_sha256", "candidate-unknown"),
            "runtime": py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card.get("runtime", {}),
            "input_shape": py_function_src_teleon_synthesis_component_plan_compiler__contract_shape(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card.get("input_contract", {})),
            "output_shape": py_function_src_teleon_synthesis_component_plan_compiler__contract_shape(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card.get("output_contract", {})),
            "serves_truth": py_const_src_teleon_synthesis_component_plan_compiler__SERVES_TRUTH,
        }

    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_registry_snapshot = py_function_src_teleon_synthesis_component_plan_compiler__stable_digest(
        sorted(py_function_src_teleon_synthesis_component_plan_compiler__component_key(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card) for py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_card in py_arg_component_cards)
    )
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_lock_body = {
        "pipeline_name": py_arg_pipeline_plan.get("plan_id") or py_arg_pipeline_plan.get("goal", "candidate_pipeline"),
        "compiler_version": py_const_src_teleon_synthesis_component_plan_compiler__COMPILER_VERSION,
        "ordered_nodes": py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_order,
        "locked_components": py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_locked_components,
        "component_registry_snapshot": py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_registry_snapshot,
    }
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_lock_id = "pipeline_lock_" + py_function_src_teleon_synthesis_component_plan_compiler__stable_digest(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_lock_body)[:16]
    return {
        "ok": not py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_errors,
        "errors": py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_errors,
        "execution_plan_id": py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_lock_id,
        "pipeline_name": py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_lock_body["pipeline_name"],
        "compiler_version": py_const_src_teleon_synthesis_component_plan_compiler__COMPILER_VERSION,
        "ordered_nodes": py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_order,
        "locked_components": py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_locked_components,
        "policy_report": {
            "gates_seen": sorted(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_gates_seen),
            "errors": py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_errors,
            "candidate_only": True,
        },
        "component_registry_snapshot": py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan__py_var_registry_snapshot,
        "random_seed_strategy": "sha256(run_id, task_id, node_id, attempt)",
        "serves_truth": py_const_src_teleon_synthesis_component_plan_compiler__SERVES_TRUTH,
    }


def py_function_src_teleon_synthesis_component_plan_compiler___self_test() -> int:
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_cards = [
        {
            "component_id": "prompt.prepare",
            "version": "1.0.0",
            "purpose": "Normalize prompt.",
            "input_contract": {"shape": "object", "fields": {"prompt": "str"}},
            "output_contract": {"shape": "object", "fields": {"normalized_prompt": "str"}},
            "runtime": {"compatible": ["local", "temporal_activity"]},
            "policy": {},
            "proofs": ["unit"],
            "serves_truth": False,
            "source_sha256": "abc",
        },
        {
            "component_id": "image.generate",
            "version": "1.0.0",
            "purpose": "Generate image.",
            "input_contract": {"shape": "object", "fields": {"prompt": "str", "seed": "int"}},
            "output_contract": {"shape": "object", "fields": {"image": "ImageArtifact"}},
            "runtime": {"compatible": ["temporal_activity"]},
            "policy": {},
            "proofs": ["unit"],
            "serves_truth": False,
            "source_sha256": "def",
        },
        {
            "component_id": "image.safety_gate",
            "version": "1.0.0",
            "purpose": "Vet image.",
            "input_contract": {"shape": "object", "fields": {"image": "ImageArtifact"}},
            "output_contract": {"shape": "object", "fields": {"decision": "SafetyDecision"}},
            "runtime": {"compatible": ["local"]},
            "policy": {"gate_id": "image_safety_gate"},
            "proofs": ["unit"],
            "serves_truth": False,
            "source_sha256": "ghi",
        },
        {
            "component_id": "delivery.email",
            "version": "1.0.0",
            "purpose": "Send email.",
            "input_contract": {"shape": "object", "fields": {"recipient": "str", "image": "ImageArtifact"}},
            "output_contract": {"shape": "object", "fields": {"receipt": "DeliveryReceipt"}},
            "side_effects": ["email"],
            "runtime": {"compatible": ["temporal_activity"]},
            "policy": {"requires_before_side_effect": ["image_safety_gate"]},
            "proofs": ["unit"],
            "serves_truth": False,
            "source_sha256": "jkl",
        },
    ]
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_plan = {
        "plan_id": "pinterest_image_candidate",
        "goal": "Generate and deliver a vetted image.",
        "nodes": [
            {"id": "prompt_prepare", "component": "prompt.prepare@1.0.0", "bindings": {"prompt": "$task.prompt"}},
            {
                "id": "image_generate",
                "component": "image.generate@1.0.0",
                "bindings": {"prompt": "$nodes.prompt_prepare.outputs.normalized_prompt", "seed": "$system.seed"},
            },
            {
                "id": "image_vet",
                "component": "image.safety_gate@1.0.0",
                "gate": "image_safety_gate",
                "bindings": {"image": "$nodes.image_generate.outputs.image"},
            },
            {
                "id": "delivery_email",
                "component": "delivery.email@1.0.0",
                "side_effect": True,
                "bindings": {"recipient": "$task.mail_hook_to_email", "image": "$nodes.image_generate.outputs.image"},
            },
        ],
    }
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_lock = py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan(
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_plan,
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_cards,
        {"prompt.prepare", "image.generate", "image.safety_gate", "delivery.email"},
    )
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_bad_plan = dict(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_plan)
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_bad_plan["nodes"] = [py_var_node for py_var_node in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_plan["nodes"] if py_var_node["id"] != "image_vet"]
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_bad_lock = py_function_src_teleon_synthesis_component_plan_compiler__validate_and_lock_pipeline_plan(
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_bad_plan,
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_cards,
        {"prompt.prepare", "image.generate", "image.safety_gate", "delivery.email"},
    )
    py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_failures = []

    def py_function_src_teleon_synthesis_component_plan_compiler___self_test__check(py_arg_name, py_arg_ok):
        print(f"  [{'ok' if py_arg_ok else 'FAIL'}] {py_arg_name}")
        if not py_arg_ok:
            py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_failures.append(py_arg_name)

    py_function_src_teleon_synthesis_component_plan_compiler___self_test__check(
        "valid plan compiles to candidate-only lock",
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_lock["ok"] and py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_lock["serves_truth"] is False,
    )
    py_function_src_teleon_synthesis_component_plan_compiler___self_test__check(
        "binding-derived dependencies produce deterministic order",
        py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_lock["ordered_nodes"] == ["prompt_prepare", "image_generate", "image_vet", "delivery_email"],
    )
    py_function_src_teleon_synthesis_component_plan_compiler___self_test__check(
        "lock contains required immutable fields",
        set(py_const_src_teleon_synthesis_component_plan_compiler__LOCK_FIELDS) <= set(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_lock),
    )
    py_function_src_teleon_synthesis_component_plan_compiler___self_test__check(
        "missing safety gate blocks side-effect node",
        not py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_bad_lock["ok"] and any("missing prior gates" in py_var_error for py_var_error in py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_bad_lock["errors"]),
    )
    if py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_failures:
        print(f"\nFAIL - component_plan_compiler: {len(py_local_src_teleon_synthesis_component_plan_compiler__py_function_src_teleon_synthesis_component_plan_compiler__self_test__py_var_failures)} failure(s)")
        return 1
    print("\nPASS - component_plan_compiler: candidate PipelinePlans validate and lock deterministically")
    return 0


if __name__ == "__main__":
    raise SystemExit(py_function_src_teleon_synthesis_component_plan_compiler___self_test())
