#!/usr/bin/env python3
"""check_capability_pr_workflow — proof for the GitHub-FAMILIAR capability layer: branches / pull requests /
checks / merge, where the eval-lift gate IS the CI check. A fork that provably lifts within policy merges; a fork
that regresses or leaves policy is BLOCKED. Same workflow on internal git OR the client's GitHub/GitLab (parity
map). Renders a familiar repo/PR UI page. serves_truth=false.

  --build      (re)write the familiar capability-repo HTML view
  --self-test  validate the PR workflow + platform parity + the UI (the registered proof)

CLI: PYTHONPATH=. python3 _repos/shared-backend-components/scripts/check_capability_pr_workflow.py --build | --self-test
"""
from __future__ import annotations
from scripts._repo_paths import resource as _resource

import html
import json
import os
import sys
from pathlib import Path

if __name__ == "__main__" and __package__ in (None, ""):  # pragma: no cover
    _R = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if _R not in sys.path:
        sys.path.insert(0, _R)

_REPO = Path(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
_MAP = _resource("architecture") / "git_platform_operation_map.json"
_OUT = _resource("dist") / "sites" / "opencontexthub" / "capability-repo-demo.html"

from src.teleon.storage.capability_pr import CapabilityRepo
from src.teleon.storage.git_backend_port import ClientPlatformBackend, LocalGitBackend


def _demo_repo() -> tuple:
    """A demo capability repo: main v1, a LIFTING PR (merges), a REGRESSING PR (blocked)."""
    repo = CapabilityRepo(LocalGitBackend("internal"))
    repo.commit_main("reg-e-deadline", "def deadline(): return ask_model()", message="v1: model-guessed", now="t0")
    good = repo.open_pr("reg-e-deadline", branch="distill-deterministic-rule",
                        head_code="def deadline(): return rule_lookup('ecfr://12/1005.11')",
                        eval_result={"lift_delta": 0.71, "accuracy": 1.0, "within_policy": True},
                        governance={"verified": True, "measured_lift": 0.71, "receipt_id": "rc_pr1"},
                        title="distill to deterministic rule")
    bad = repo.open_pr("reg-e-deadline", branch="risky-shortcut",
                       head_code="def deadline(): return cached_stale()",
                       eval_result={"lift_delta": -0.2, "accuracy": 0.6, "within_policy": True},
                       title="cache a stale answer")
    return repo, good, bad


def render_view() -> str:
    repo, good, bad = _demo_repo()
    m = json.loads(_MAP.read_text())
    gv = repo.pr_view(good)
    merged = repo.merge(good, now="t1")
    bv = repo.pr_view(bad)
    repo.merge(bad, now="t2")  # will be rejected

    def pr_card(view, after):
        chk = view["checks"]
        cls = "ok" if chk["passed"] else "bad"
        return (f'<div class="panel"><h2>{html.escape(view["pr_id"])} · {html.escape(view["title"])} '
                f'<span class="pill {cls}">{"checks passed" if chk["passed"] else "checks failed"}</span></h2>'
                f'<div class="row"><span class="mut">branch</span><code>{html.escape(view["branch"])}</code></div>'
                f'<div class="row"><span class="mut">check</span><code>{html.escape(chk["check"])}</code></div>'
                f'<div class="row"><span class="mut">behavior diff (lift Δ)</span><span>{view["behavior_diff"]["lift_delta"]}</span></div>'
                f'<div class="add{" bad" if not chk["passed"] else ""}">{html.escape(chk["summary"])}</div>'
                f'<div class="row"><span class="mut">state</span><span>{html.escape(after)}</span></div>'
                f'<pre>{html.escape(view["code_diff"])}</pre></div>')

    rows = "".join(f'<div class="row"><code>{html.escape(o["operation"])}</code>'
                   f'<span class="mut">GitHub: {html.escape(o["github"])} · GitLab: {html.escape(o["gitlab"])}</span></div>'
                   for o in m["operations"])
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Teleon · capability repo (GitHub-familiar)</title>
<!-- GENERATED by scripts/check_capability_pr_workflow.py — do not hand-edit. -->
<style>
 :root {{ --bg:#0d1117;--panel:#161b22;--line:#21262d;--fg:#e6edf3;--mut:#8b949e;--ok:#3fb950;--bad:#f85149;--acc:#58a6ff; }}
 *{{box-sizing:border-box}} body{{margin:0;background:var(--bg);color:var(--fg);font:13px/1.5 ui-monospace,Menlo,Consolas,monospace}}
 header{{padding:16px 20px;border-bottom:1px solid var(--line)}} h1{{font-size:16px;margin:0}}
 .sub{{color:var(--mut);font-size:12px}} main{{padding:16px;max-width:1000px}}
 .panel{{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:12px;margin-bottom:12px}}
 .panel h2{{font-size:13px;margin:0 0 8px;display:flex;justify-content:space-between;gap:8px;align-items:center}}
 .row{{display:flex;justify-content:space-between;gap:8px;padding:2px 0;border-bottom:1px dashed var(--line)}}
 .mut{{color:var(--mut)}} code{{color:var(--acc)}}
 .add{{color:var(--ok);font-size:12px;margin:6px 0}} .add.bad{{color:var(--bad)}}
 .pill{{padding:1px 7px;border-radius:999px;font-size:11px}} .pill.ok{{background:rgba(63,185,80,.15);color:var(--ok)}}
 .pill.bad{{background:rgba(248,81,73,.15);color:var(--bad)}}
 pre{{white-space:pre-wrap;color:var(--mut);font-size:11px;max-height:160px;overflow:auto;margin:6px 0 0}}
 footer{{padding:14px 20px;border-top:1px solid var(--line);color:var(--mut);font-size:11px}}
</style></head><body>
<header><h1>teleon/reg-e-deadline <span class="sub">· capability repo · backend: internal git (or your GitHub/GitLab)</span></h1>
<div class="sub">A capability unit as a familiar git repo. A Pull Request is a proposed capability fork; the status CHECK is the eval/lift gate; a fork merges only if it provably lifts within policy.</div></header>
<main>
<div class="panel"><h2>Pull requests</h2><div class="sub">the eval-lift gate is the CI check — a regression cannot merge</div></div>
{pr_card(gv, "merged" if merged["merged"] else "rejected")}
{pr_card(bv, "rejected")}
<div class="panel"><h2>Same workflow on GitHub / GitLab / Gitea (operation parity)</h2>
<div class="sub">{html.escape(m["naming_differences"]["pull_request"])} · {html.escape(m["naming_differences"]["status_check"])}</div>
{rows}</div>
</main>
<footer>Generated from architecture/git_platform_operation_map.json + the capability-PR workflow. Governance (lift/receipt) rides in the notes sidecar — your code stays clean. This page computes no truth (serves_truth=false).</footer>
</body></html>
"""


def write_view() -> str:
    _OUT.parent.mkdir(parents=True, exist_ok=True)
    _OUT.write_text(render_view())
    return str(_OUT.relative_to(_REPO))


def _self_test() -> int:
    fails: list[str] = []

    def ck(name: str, ok: bool, detail: str = "") -> None:
        print(f"  [{'ok' if ok else 'FAIL'}] {name}{(': ' + detail) if detail and not ok else ''}")
        if not ok:
            fails.append(name)

    repo, good, bad = _demo_repo()
    # the eval-lift gate IS the check: a lifting fork passes + merges + attaches the sidecar
    ck("a lifting fork passes the eval-lift CHECK", repo.checks(good)["passed"] is True)
    mg = repo.merge(good, now="t1")
    ck("a passing PR merges + records the governance sidecar (lift/receipt)",
       mg["merged"] is True and mg["governance_sidecar"].get("measured_lift") == 0.71 and mg["checks"]["passed"])
    # a regressing fork is BLOCKED (the governance teeth)
    ck("a REGRESSING fork fails the check and CANNOT merge",
       repo.checks(bad)["passed"] is False and repo.merge(bad, now="t2")["merged"] is False)
    # an out-of-policy fork is blocked too
    oop = repo.open_pr("reg-e-deadline", branch="x", head_code="y",
                       eval_result={"lift_delta": 0.5, "accuracy": 1.0, "within_policy": False})
    ck("an OUT-OF-POLICY fork fails the check", repo.checks(oop)["passed"] is False)
    # the PR carries a code diff AND a behavior(eval) diff
    gv = repo.pr_view(good)
    ck("a PR shows both a code diff and a behavior(eval-lift) diff",
       "rule_lookup" in gv["code_diff"] and gv["behavior_diff"]["lift_delta"] == 0.71)
    # the SAME workflow runs on the client's GitHub backend
    gh = CapabilityRepo(ClientPlatformBackend("github", "acme/caps"))
    gh.commit_main("u", "v1", message="v1", now="t0")
    pr2 = gh.open_pr("u", branch="b", head_code="v2", eval_result={"lift_delta": 0.1, "accuracy": 1.0, "within_policy": True})
    ck("the SAME PR/checks/merge workflow runs on the client's GitHub backend",
       gh.merge(pr2, now="t1")["merged"] is True and gh.backend.platform == "github")
    ck("never serves truth", gv["serves_truth"] is False and mg["serves_truth"] is False)

    # platform parity map
    m = json.loads(_MAP.read_text())
    ops = m["operations"]
    ck("every capability-repo operation maps to GitHub + GitLab + Gitea + a real port method (>= 8 ops)",
       len(ops) >= 8 and all(o["github"] and o["gitlab"] and o["gitea"] and o["port_method"] and o["parity"] for o in ops))
    ck("the naming differences are captured (PR==MR, Checks==Pipelines)",
       "MR" in m["naming_differences"]["pull_request"] and "Pipelines" in m["naming_differences"]["status_check"])
    ck("the governed metadata rides in the notes SIDECAR (attach_governance) on every platform",
       any(o["operation"] == "governance_notes" and o["port_method"] == "attach_governance" for o in ops))

    # the familiar UI renders the repo + PRs + the passing/failing checks + parity
    page = render_view()
    ck("the familiar UI renders the repo, a passing check, a failing check, and the parity table",
       "Pull requests" in page and "checks passed" in page and "checks failed" in page
       and "GitLab" in page and "0.71" in page)
    if _OUT.exists():
        ck("the on-disk UI is fresh (regenerate with --build)", _OUT.read_text() == page)
    ck("deterministic", render_view() == page)

    print("\n" + ("PASS - check_capability_pr_workflow: a capability unit is a FAMILIAR git repo — branches / PRs / "
                  "checks / merge — where the eval-lift gate IS the CI check (a regressing or out-of-policy fork "
                  "cannot merge); the same workflow runs on internal git OR the client's GitHub/GitLab/Gitea "
                  "(operation parity); governance rides in the notes sidecar; a familiar UI renders it. Never serves "
                  "truth." if not fails else f"{len(fails)} FAILURES: {fails}"))
    return 0 if not fails else 1


def _main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    if "--build" in argv:
        print("wrote:", write_view())
        return 0
    if "--self-test" in argv:
        return _self_test()
    print("usage: check_capability_pr_workflow.py --build | --self-test")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
