#!/usr/bin/env python3
"""Generate primitive-kind family seeds for AIDevExplorer/AIDevObserver."""
from __future__ import annotations
from scripts._repo_paths import resource as _resource

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

if __package__ is None or __package__ == "":
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts._config import (  # noqa: E402
    AIDEVEXPLORER_PRIMITIVE_KIND_FAMILY_CATALOG_MANIFEST_PATH,
    AIDEVEXPLORER_PRIMITIVE_KIND_FAMILY_CATALOG_PATH,
    AIDEVEXPLORER_PRIMITIVE_KIND_SOURCE_EVIDENCE_STATUS,
    AIDEVEXPLORER_PRIMITIVE_KIND_SOURCE_FAMILY,
    REPO_ROOT,
)

OUT_PATH = _resource(AIDEVEXPLORER_PRIMITIVE_KIND_FAMILY_CATALOG_PATH)
MANIFEST_PATH = _resource(AIDEVEXPLORER_PRIMITIVE_KIND_FAMILY_CATALOG_MANIFEST_PATH)


def _sha(value: Any, *, n: int = 16) -> str:
    text = json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:n]


def _slug(value: str) -> str:
    out = []
    prev_dash = False
    for char in value.lower():
        if char.isalnum():
            out.append(char)
            prev_dash = False
        elif not prev_dash:
            out.append("-")
            prev_dash = True
    return "".join(out).strip("-") or "primitive-kind"


def _family(
    primitive_kind: str,
    title: str,
    *,
    visible_edge: tuple[str, str],
    hidden_edges: list[str],
    effects: list[str],
    mutators: list[str],
    proofs: list[str],
    pitfalls: list[str],
    domains: list[str],
    runtime_targets: list[str],
    examples: list[str],
) -> dict[str, Any]:
    input_edge, output_edge = visible_edge
    return {
        "id": f"pkf:{primitive_kind}:{_sha([primitive_kind, input_edge, output_edge], n=8)}",
        "slug": _slug(primitive_kind),
        "primitive_kind": primitive_kind,
        "title": title,
        "input_edge": input_edge,
        "output_edge": output_edge,
        "visible_edge": f"{input_edge} -> {output_edge}",
        "hidden_member_edges": hidden_edges,
        "effects": effects,
        "adapter_mutators": mutators,
        "proof_requirements": sorted(dict.fromkeys([*proofs, "candidate_boundary_gate"])),
        "common_pitfalls": pitfalls,
        "domains": domains,
        "runtime_targets": runtime_targets,
        "example_tasks": examples,
        "source_family": AIDEVEXPLORER_PRIMITIVE_KIND_SOURCE_FAMILY,
        "source_evidence_status": AIDEVEXPLORER_PRIMITIVE_KIND_SOURCE_EVIDENCE_STATUS,
        "trust": "candidate",
        "candidate": True,
        "serves_truth": False,
    }


PRIMITIVE_KIND_FAMILIES: list[dict[str, Any]] = [
    _family(
        "api.endpoint",
        "HTTP API endpoint contract",
        visible_edge=("HttpRequest[DomainCommandEnvelope]", "HttpResponse[DomainReceipt]"),
        hidden_edges=[
            "HttpRequest->AuthenticatedRequest",
            "AuthenticatedRequest->ValidatedDomainCommand",
            "ValidatedDomainCommand->IdempotencyDecision",
            "IdempotencyDecision->DomainReceipt",
            "DomainReceipt->HttpResponse",
        ],
        effects=["network_read", "database_write", "audit_log_write"],
        mutators=["api_endpoint_wrapper", "schema_validator_inserter", "idempotency_wrapper", "output_wrapper"],
        proofs=["openapi_contract_test", "authz_test", "schema_validation_test", "idempotency_test"],
        pitfalls=["validation after persistence", "missing idempotency key", "unbounded request body", "audit receipt absent"],
        domains=["backend_api", "software_engineering"],
        runtime_targets=["api.endpoint", "cloud.function.http", "container.python", "k8s.deployment"],
        examples=["POST import CSV", "PATCH approve request", "GET audit trail"],
    ),
    _family(
        "graphql.resolver",
        "GraphQL resolver contract",
        visible_edge=("GraphQLOperation[SelectionSet+Variables]", "GraphQLResult[TypedPayload]"),
        hidden_edges=[
            "GraphQLOperation->AuthzDecision",
            "SelectionSet+Variables->ValidatedResolverInput",
            "ValidatedResolverInput->DataLoaderPlan",
            "DataLoaderPlan->TypedPayload",
            "TypedPayload->GraphQLResult",
        ],
        effects=["network_read", "database_read", "database_write_optional"],
        mutators=["schema_validator_inserter", "field_project", "output_wrapper"],
        proofs=["schema_contract_test", "resolver_fixture_test", "selection_set_authz_test"],
        pitfalls=["overfetching", "N+1 queries", "field-level auth skipped", "ambiguous error envelope"],
        domains=["backend_api", "software_engineering"],
        runtime_targets=["graphql.resolver", "container.node", "container.python"],
        examples=["Create order mutation", "Customer profile query", "Paginated search resolver"],
    ),
    _family(
        "grpc.method",
        "gRPC service method contract",
        visible_edge=("GrpcRequest[TypedProtoMessage]", "GrpcResponse[TypedProtoReceipt]"),
        hidden_edges=[
            "GrpcRequest->MetadataAuthDecision",
            "TypedProtoMessage->ValidatedProtoInput",
            "ValidatedProtoInput->ServiceDecision",
            "ServiceDecision->TypedProtoReceipt",
            "TypedProtoReceipt->GrpcResponse",
        ],
        effects=["network_read", "database_write_optional", "audit_log_write"],
        mutators=["schema_validator_inserter", "retry_wrapper", "output_wrapper"],
        proofs=["proto_contract_test", "deadline_test", "status_code_test"],
        pitfalls=["deadline ignored", "status codes collapsed", "metadata auth bypassed", "retry not idempotent"],
        domains=["backend_api", "service_mesh"],
        runtime_targets=["grpc.method", "container.go", "k8s.deployment"],
        examples=["Authorize payment", "Create shipment", "Lookup eligibility"],
    ),
    _family(
        "webhook.handler",
        "Webhook handler contract",
        visible_edge=("WebhookEventEnvelope", "VerifiedDomainEventReceipt"),
        hidden_edges=[
            "WebhookEventEnvelope->SignatureVerification",
            "SignatureVerification->ValidatedWebhookPayload",
            "ValidatedWebhookPayload->WebhookDedupeDecision",
            "WebhookDedupeDecision->DomainEventMapping",
            "DomainEventMapping->VerifiedDomainEventReceipt",
        ],
        effects=["network_read", "queue_write", "audit_log_write"],
        mutators=["schema_validator_inserter", "idempotency_wrapper", "retry_wrapper"],
        proofs=["signature_fixture_test", "replay_safety_test", "dedupe_fixture_test"],
        pitfalls=["signature bypass", "raw payload logged", "duplicate side effects", "retry storm"],
        domains=["integration", "backend_api"],
        runtime_targets=["webhook.handler", "api.endpoint", "cloud.function.http"],
        examples=["Stripe invoice paid", "GitHub pull request opened", "Shopify order created"],
    ),
    _family(
        "queue.consumer",
        "Queue worker consumer contract",
        visible_edge=("QueueMessage[JobEnvelope]", "JobExecutionReceipt"),
        hidden_edges=[
            "QueueMessage->DecodedJobEnvelope",
            "DecodedJobEnvelope->ValidatedJobInput",
            "ValidatedJobInput->IdempotencyDecision",
            "IdempotencyDecision->JobExecutionResult",
            "JobExecutionResult->JobExecutionReceipt",
        ],
        effects=["queue_read", "database_write", "audit_log_write"],
        mutators=["input_envelope_wrapper", "retry_wrapper", "idempotency_wrapper"],
        proofs=["queue_fixture_test", "retry_policy_test", "dead_letter_test"],
        pitfalls=["poison message loop", "non-idempotent retries", "dead letter missing", "unbounded concurrency"],
        domains=["workflow_automation", "backend_api"],
        runtime_targets=["queue.consumer", "container.python", "k8s.deployment"],
        examples=["Generate PDF worker", "Sync CRM worker", "Retry failed webhook worker"],
    ),
    _family(
        "queue.producer",
        "Queue producer contract",
        visible_edge=("DomainEvent+PublishPolicy", "PublishedMessageReceipt"),
        hidden_edges=[
            "DomainEvent->SerializableMessage",
            "SerializableMessage+PublishPolicy->TopicRoutingDecision",
            "TopicRoutingDecision->DeliveryMetadata",
            "DeliveryMetadata->PublishedMessageReceipt",
        ],
        effects=["queue_write", "audit_log_write"],
        mutators=["output_wrapper", "provenance_wrapper", "retry_wrapper"],
        proofs=["topic_contract_test", "message_schema_test", "delivery_receipt_test"],
        pitfalls=["topic names duplicated", "schema version omitted", "delivery receipt absent", "PII in message body"],
        domains=["eventing", "backend_api"],
        runtime_targets=["queue.producer", "container.python", "cloud.function.http"],
        examples=["Publish onboarding event", "Emit audit event", "Fan out report job"],
    ),
    _family(
        "event.handler",
        "Domain event handler contract",
        visible_edge=("DomainEventEnvelope+HandlerPolicy", "EventHandlerReceipt"),
        hidden_edges=[
            "DomainEventEnvelope->EventTypeDecision",
            "EventTypeDecision+HandlerPolicy->HandlerRoute",
            "HandlerRoute->SideEffectPlan",
            "SideEffectPlan->EventHandlerReceipt",
        ],
        effects=["workflow_state_write", "database_write_optional", "audit_log_write"],
        mutators=["filter_predicate", "retry_wrapper", "idempotency_wrapper"],
        proofs=["event_route_fixture_test", "idempotent_replay_test", "side_effect_audit"],
        pitfalls=["event type switch duplicated", "handler side effects untracked", "replay unsafe", "no ordering policy"],
        domains=["eventing", "workflow_automation"],
        runtime_targets=["event.handler", "queue.consumer", "workflow.step"],
        examples=["User signed up event", "Invoice approved event", "Risk score changed event"],
    ),
    _family(
        "cron.job",
        "Scheduled job contract",
        visible_edge=("ScheduleTick+JobPolicy", "ScheduledJobReceipt"),
        hidden_edges=[
            "ScheduleTick->ScheduleWindow",
            "ScheduleWindow+JobPolicy->RunEligibilityDecision",
            "RunEligibilityDecision->ScheduledJobInput",
            "ScheduledJobInput->JobResult",
            "JobResult->ScheduledJobReceipt",
        ],
        effects=["time_trigger", "database_write", "audit_log_write"],
        mutators=["k8s_cronjob_wrapper", "idempotency_wrapper", "provenance_wrapper"],
        proofs=["schedule_policy_test", "missed_run_recovery_test", "idempotent_rerun_test"],
        pitfalls=["timezone drift", "missed run ignored", "duplicate scheduled writes", "no backfill policy"],
        domains=["devops", "workflow_automation"],
        runtime_targets=["cron.job", "k8s.cronjob", "container.python"],
        examples=["Nightly billing reconciliation", "Weekly compliance export", "Daily data sync"],
    ),
    _family(
        "workflow.step",
        "Durable workflow step contract",
        visible_edge=("WorkflowState+StepInput", "WorkflowStepReceipt"),
        hidden_edges=[
            "WorkflowState+StepInput->StepPreconditionDecision",
            "StepPreconditionDecision->StepExecutionPlan",
            "StepExecutionPlan->StepResult",
            "StepResult->WorkflowStatePatch",
            "WorkflowStatePatch->WorkflowStepReceipt",
        ],
        effects=["workflow_state_write", "audit_log_write"],
        mutators=["input_envelope_wrapper", "retry_wrapper", "provenance_wrapper"],
        proofs=["workflow_replay_test", "state_transition_test", "compensation_test"],
        pitfalls=["state transition implicit", "compensation absent", "step replay unsafe", "hidden dependency on wall clock"],
        domains=["workflow_automation", "software_engineering"],
        runtime_targets=["workflow.step", "durable.workflow"],
        examples=["Approval step", "Document review step", "Escalation step"],
    ),
    _family(
        "workflow.group",
        "Multi-step workflow group contract",
        visible_edge=("WorkflowIntent+WorkflowInputs", "WorkflowExecutionReceipt"),
        hidden_edges=[
            "WorkflowIntent->WorkflowTemplateRoute",
            "WorkflowTemplateRoute+WorkflowInputs->StepGraph",
            "StepGraph->CompensationPlan",
            "StepGraph+CompensationPlan->WorkflowExecutionReceipt",
        ],
        effects=["workflow_state_write", "queue_write", "audit_log_write"],
        mutators=["fanout_fanin", "retry_wrapper", "provenance_wrapper"],
        proofs=["workflow_graph_contract_test", "compensation_path_test", "replay_test"],
        pitfalls=["workflow modeled as one function", "compensation not declared", "hidden queues not audited", "step ownership unclear"],
        domains=["workflow_automation"],
        runtime_targets=["workflow.group", "durable.workflow", "container.python"],
        examples=["Lead import workflow", "Invoice approval workflow", "Dependency exception workflow"],
    ),
    _family(
        "service.group",
        "Microservice bounded capability group",
        visible_edge=("ServiceCommandEnvelope", "ServiceReceipt"),
        hidden_edges=[
            "ServiceCommandEnvelope->AuthzDecision",
            "ServiceCommandEnvelope->IdempotencyKey",
            "ServiceCommandEnvelope->EndpointOrWorkerRoute",
            "EndpointOrWorkerRoute->PersistencePlan",
            "PersistencePlan->ServiceReceipt",
        ],
        effects=["network_read", "database_read", "database_write", "audit_log_write"],
        mutators=["api_endpoint_wrapper", "retry_wrapper", "idempotency_wrapper", "provenance_wrapper"],
        proofs=["service_contract_test", "failure_mode_test", "idempotency_test", "observability_receipt_test"],
        pitfalls=["microservice treated as one primitive", "DB writes hidden", "retry semantics unclear", "observability missing"],
        domains=["backend_api", "software_architecture"],
        runtime_targets=["service.group", "api.endpoint", "queue.consumer", "k8s.deployment"],
        examples=["Billing service", "Identity service", "Notification service"],
    ),
    _family(
        "integration.connector",
        "SaaS/API integration connector contract",
        visible_edge=("SourceSystemDelta+SyncPolicy", "TargetSystemMutationReceipt"),
        hidden_edges=[
            "SourceSystemDelta->SourceApiPageSet",
            "SourceApiPageSet+SyncPolicy->NormalizedChangeSet",
            "NormalizedChangeSet->TargetMutationPlan",
            "TargetMutationPlan->TargetSystemMutationReceipt",
        ],
        effects=["network_read", "network_write", "audit_log_write"],
        mutators=["pagination_expander", "retry_wrapper", "idempotency_wrapper", "schema_validator_inserter"],
        proofs=["source_fixture_test", "target_contract_test", "idempotent_sync_test", "rate_limit_policy_test"],
        pitfalls=["field mapping implicit", "rate limits ignored", "non-idempotent upsert", "source timestamps missing"],
        domains=["integration", "business_operations"],
        runtime_targets=["integration.connector", "container.python", "queue.consumer", "cron.job"],
        examples=["Salesforce to HubSpot sync", "Shopify to QuickBooks sync", "Slack alert to Jira ticket"],
    ),
    _family(
        "sdk.client",
        "Typed SDK client adapter contract",
        visible_edge=("ApiRequestEnvelope+ClientPolicy", "TypedApiResponse"),
        hidden_edges=[
            "ApiRequestEnvelope->AuthHeaderPlan",
            "AuthHeaderPlan+ClientPolicy->HttpClientRequest",
            "HttpClientRequest->RawApiResponse",
            "RawApiResponse->TypedApiResponse",
        ],
        effects=["network_read", "network_write_optional"],
        mutators=["retry_wrapper", "schema_validator_inserter", "pagination_expander"],
        proofs=["client_contract_test", "error_mapping_test", "retry_policy_test"],
        pitfalls=["SDK errors collapsed", "auth header copied", "pagination hidden", "timeouts unset"],
        domains=["integration", "backend_api"],
        runtime_targets=["sdk.client", "local.python", "container.python"],
        examples=["Stripe client adapter", "GitHub client adapter", "HubSpot client adapter"],
    ),
    _family(
        "cli.command",
        "Command-line tool primitive",
        visible_edge=("CommandArgs+Files", "CliExecutionReceipt"),
        hidden_edges=[
            "CommandArgs->ParsedCommandInput",
            "Files->ArtifactRefSet",
            "ParsedCommandInput+ArtifactRefSet->CommandExecutionPlan",
            "CommandExecutionPlan->CliExecutionReceipt",
        ],
        effects=["subprocess_optional", "artifact_read", "artifact_write"],
        mutators=["cli_wrapper", "schema_validator_inserter", "output_wrapper"],
        proofs=["argv_contract_test", "exit_code_test", "artifact_output_test"],
        pitfalls=["exit codes ignored", "stdout parsed ad hoc", "destructive flags unchecked", "artifact paths not declared"],
        domains=["developer_tools", "software_engineering"],
        runtime_targets=["cli.command", "local.python", "container.python"],
        examples=["Import CSV CLI", "Generate report CLI", "Validate manifests CLI"],
    ),
    _family(
        "shell.script",
        "Shell automation primitive",
        visible_edge=("ShellExecutionContext+ScriptPolicy", "CommandRunReceipt"),
        hidden_edges=[
            "ShellExecutionContext+ScriptPolicy->AllowedCommandPlan",
            "AllowedCommandPlan->ShellProcessResult",
            "ShellProcessResult->CommandRunReceipt",
        ],
        effects=["subprocess", "fs.read_optional", "fs.write_optional"],
        mutators=["cli_wrapper", "provenance_wrapper", "idempotency_wrapper"],
        proofs=["shellcheck_gate", "dry_run_test", "exit_code_test"],
        pitfalls=["unsafe glob", "secret echoed", "non-idempotent filesystem write", "working directory implicit"],
        domains=["devops", "developer_tools"],
        runtime_targets=["shell.script", "local.shell", "container.shell"],
        examples=["Build script", "Backup script", "Release script"],
    ),
    _family(
        "container.job",
        "Containerized one-shot job contract",
        visible_edge=("ContainerJobSpec+InputArtifacts", "ContainerJobRunReceipt"),
        hidden_edges=[
            "ContainerJobSpec->ImagePolicyDecision",
            "InputArtifacts->MountedArtifactSet",
            "ImagePolicyDecision+MountedArtifactSet->ContainerRunPlan",
            "ContainerRunPlan->ContainerJobRunReceipt",
        ],
        effects=["container_run", "artifact_read", "artifact_write"],
        mutators=["artifact_reference", "provenance_wrapper", "retry_wrapper"],
        proofs=["image_policy_test", "artifact_mount_test", "job_exit_test"],
        pitfalls=["latest tag used", "resource limit missing", "artifact digest absent", "logs not captured"],
        domains=["devops", "data_engineering"],
        runtime_targets=["container.job", "container.python", "k8s.job"],
        examples=["Batch import job", "Embedding build job", "Report export job"],
    ),
    _family(
        "kubernetes.job",
        "Kubernetes batch job contract",
        visible_edge=("KubernetesJobSpec+DataRef", "KubernetesJobReceipt"),
        hidden_edges=[
            "KubernetesJobSpec->ResourcePolicyDecision",
            "DataRef->ArtifactMountPlan",
            "ResourcePolicyDecision+ArtifactMountPlan->KubernetesJobManifest",
            "KubernetesJobManifest->KubernetesJobReceipt",
        ],
        effects=["k8s.apply", "container_run", "artifact_read", "artifact_write"],
        mutators=["k8s_job_wrapper", "artifact_reference", "provenance_wrapper"],
        proofs=["manifest_contract_test", "resource_limit_test", "job_completion_test"],
        pitfalls=["namespace implicit", "resources unset", "restart policy wrong", "artifact path not durable"],
        domains=["devops_cloud_k8s", "software_engineering"],
        runtime_targets=["kubernetes.job", "k8s.job"],
        examples=["ETL batch job", "Model scoring batch", "Index rebuild job"],
    ),
    _family(
        "kubernetes.controller",
        "Kubernetes reconciliation controller contract",
        visible_edge=("DesiredState+ObservedState", "ReconcileReceipt"),
        hidden_edges=[
            "DesiredState+ObservedState->StateDiff",
            "StateDiff->ReconcilePlan",
            "ReconcilePlan->KubernetesPatchSet",
            "KubernetesPatchSet->ReconcileReceipt",
        ],
        effects=["k8s.read", "k8s.write", "audit_log_write"],
        mutators=["retry_wrapper", "idempotency_wrapper", "provenance_wrapper"],
        proofs=["reconcile_idempotency_test", "dry_run_patch_test", "finalizer_test"],
        pitfalls=["reconcile loop not idempotent", "owner refs absent", "finalizer leak", "patch too broad"],
        domains=["devops_cloud_k8s"],
        runtime_targets=["kubernetes.controller", "k8s.deployment"],
        examples=["Custom resource controller", "Secret rotation controller", "Preview environment controller"],
    ),
    _family(
        "terraform.module",
        "Terraform infrastructure module contract",
        visible_edge=("InfraConfig+StatePolicy", "ProvisionPlanReceipt"),
        hidden_edges=[
            "InfraConfig->TerraformVariables",
            "TerraformVariables+StatePolicy->TerraformPlan",
            "TerraformPlan->PolicyDecision",
            "PolicyDecision->ProvisionPlanReceipt",
        ],
        effects=["cloud_plan", "cloud_write_optional", "state_write"],
        mutators=["schema_validator_inserter", "provenance_wrapper", "secret_ref_wrapper"],
        proofs=["terraform_validate_test", "plan_policy_test", "state_backend_test"],
        pitfalls=["state backend implicit", "secrets in variables", "destroy plan unchecked", "provider version floating"],
        domains=["devops_infra", "cloud"],
        runtime_targets=["terraform.module", "ci.workflow"],
        examples=["Postgres module", "Static site module", "Queue module"],
    ),
    _family(
        "github.action",
        "GitHub Actions workflow primitive",
        visible_edge=("RepoEvent+WorkflowConfig", "PipelineReceipt"),
        hidden_edges=[
            "RepoEvent->WorkflowTriggerDecision",
            "WorkflowConfig->JobMatrix",
            "JobMatrix->ArtifactPlan",
            "ArtifactPlan->PipelineReceipt",
        ],
        effects=["ci_run", "artifact_write", "network_read_optional"],
        mutators=["cache_wrapper", "provenance_wrapper", "secret_ref_wrapper"],
        proofs=["workflow_syntax_test", "permissions_policy_test", "artifact_receipt_test"],
        pitfalls=["overbroad token", "cache key unstable", "artifacts missing", "matrix too slow"],
        domains=["devops", "developer_tools"],
        runtime_targets=["github.action", "ci.workflow"],
        examples=["CI test matrix", "Preview deployment", "Release workflow"],
    ),
    _family(
        "db.migration",
        "Database migration contract",
        visible_edge=("DatabaseState+MigrationSpec", "MigrationReceipt"),
        hidden_edges=[
            "DatabaseState+MigrationSpec->MigrationPlan",
            "MigrationPlan->LockAndBackupDecision",
            "LockAndBackupDecision->SchemaChangeSet",
            "SchemaChangeSet->MigrationReceipt",
        ],
        effects=["database_write", "schema_write", "audit_log_write"],
        mutators=["idempotency_wrapper", "provenance_wrapper", "schema_validator_inserter"],
        proofs=["migration_dry_run_test", "rollback_test", "data_integrity_test"],
        pitfalls=["rollback absent", "long lock ignored", "backfill not batched", "PII migration unreviewed"],
        domains=["database", "backend_api"],
        runtime_targets=["db.migration", "ci.workflow", "container.job"],
        examples=["Add audit table", "Backfill column", "Mask PII fields"],
    ),
    _family(
        "sql.view",
        "Reusable SQL view contract",
        visible_edge=("DatabaseTables+ViewSpec", "AnalyticsViewReceipt"),
        hidden_edges=[
            "DatabaseTables+ViewSpec->ColumnLineageMap",
            "ColumnLineageMap->SqlViewDefinition",
            "SqlViewDefinition->ViewValidationReport",
            "ViewValidationReport->AnalyticsViewReceipt",
        ],
        effects=["database_read", "schema_write"],
        mutators=["field_project", "schema_validator_inserter", "provenance_wrapper"],
        proofs=["view_compile_test", "row_count_fixture_test", "column_contract_test"],
        pitfalls=["ambiguous join", "column names drift", "PII exposed", "view performance unchecked"],
        domains=["analytics", "database"],
        runtime_targets=["sql.view", "warehouse"],
        examples=["Customer reporting view", "Revenue view", "Inventory analytics view"],
    ),
    _family(
        "sql.proc",
        "Stored procedure contract",
        visible_edge=("ProcedureArgs+DatabaseState", "ProcedureResultReceipt"),
        hidden_edges=[
            "ProcedureArgs->ValidatedProcedureArgs",
            "ValidatedProcedureArgs+DatabaseState->ProcedureExecutionPlan",
            "ProcedureExecutionPlan->ProcedureResult",
            "ProcedureResult->ProcedureResultReceipt",
        ],
        effects=["database_read", "database_write_optional", "audit_log_write"],
        mutators=["schema_validator_inserter", "idempotency_wrapper", "output_wrapper"],
        proofs=["procedure_fixture_test", "transaction_boundary_test", "error_code_test"],
        pitfalls=["transaction implicit", "procedure mutates hidden tables", "error handling ad hoc", "permissions too broad"],
        domains=["database", "backend_api"],
        runtime_targets=["sql.proc", "database"],
        examples=["Recalculate invoice totals", "Archive old records", "Restore soft-deleted records"],
    ),
    _family(
        "etl.pipeline",
        "ETL data pipeline contract",
        visible_edge=("RawSourceBatch+PipelinePolicy", "WarehouseLoadReceipt"),
        hidden_edges=[
            "RawSourceBatch->ExtractedRecords",
            "ExtractedRecords+PipelinePolicy->TransformedRecords",
            "TransformedRecords->QualityGateDecision",
            "QualityGateDecision->WarehouseLoadReceipt",
        ],
        effects=["network_read_optional", "database_write", "artifact_write"],
        mutators=["batch_chunker", "schema_validator_inserter", "provenance_wrapper"],
        proofs=["source_fixture_test", "row_count_test", "lineage_receipt_test"],
        pitfalls=["row-count checks absent", "schema drift ignored", "lineage not emitted", "quarantine missing"],
        domains=["data_engineering"],
        runtime_targets=["etl.pipeline", "container.job", "cron.job"],
        examples=["Vendor feed ETL", "Warehouse sync", "Compliance evidence export"],
    ),
    _family(
        "elt.model",
        "Warehouse ELT model contract",
        visible_edge=("RawWarehouseTables+ModelSpec", "ModeledAnalyticsTableReceipt"),
        hidden_edges=[
            "RawWarehouseTables+ModelSpec->SqlTransformPlan",
            "SqlTransformPlan->ModeledTable",
            "ModeledTable->DataQualityReport",
            "DataQualityReport->ModeledAnalyticsTableReceipt",
        ],
        effects=["database_read", "database_write"],
        mutators=["field_project", "schema_validator_inserter", "provenance_wrapper"],
        proofs=["model_compile_test", "data_quality_test", "lineage_test"],
        pitfalls=["SQL hard-coded per customer", "tests missing", "lineage not declared", "incremental model unsafe"],
        domains=["analytics_engineering", "data_engineering"],
        runtime_targets=["elt.model", "warehouse", "dbt"],
        examples=["Customer dimension", "Revenue model", "Churn model"],
    ),
    _family(
        "data.quality.rule",
        "Deterministic data quality rule contract",
        visible_edge=("DatasetSnapshot+QualityRule", "QualityRuleReceipt"),
        hidden_edges=[
            "DatasetSnapshot+QualityRule->RuleEvaluationPlan",
            "RuleEvaluationPlan->ViolationSet",
            "ViolationSet->SeverityDecision",
            "SeverityDecision->QualityRuleReceipt",
        ],
        effects=["database_read", "artifact_write"],
        mutators=["filter_predicate", "schema_validator_inserter", "output_wrapper"],
        proofs=["fixture_violation_test", "threshold_boundary_test", "receipt_schema_test"],
        pitfalls=["threshold subjective", "baseline absent", "violations not sample-backed", "owner routing missing"],
        domains=["data_quality", "analytics"],
        runtime_targets=["data.quality.rule", "container.python"],
        examples=["Null spike rule", "Volume anomaly rule", "Foreign key orphan rule"],
    ),
    _family(
        "rag.pipeline",
        "Retrieval-augmented generation pipeline contract",
        visible_edge=("UserQuestion+CorpusRef+RetrievalPolicy", "CitedAnswerReceipt"),
        hidden_edges=[
            "CorpusRef->ChunkedDocumentSet",
            "ChunkedDocumentSet->VectorIndexRef",
            "UserQuestion+VectorIndexRef->RetrievedEvidenceSet",
            "RetrievedEvidenceSet+RetrievalPolicy->GroundedAnswerDraft",
            "GroundedAnswerDraft->CitedAnswerReceipt",
        ],
        effects=["model.call", "vector_read", "artifact_write"],
        mutators=["batch_chunker", "schema_validator_inserter", "provenance_wrapper"],
        proofs=["citation_span_test", "retrieval_fixture_test", "answer_grounding_test"],
        pitfalls=["citations not span-backed", "stale index", "prompt contains full docs", "eval cases absent"],
        domains=["ai_rag", "knowledge_management"],
        runtime_targets=["rag.pipeline", "api.endpoint", "container.python"],
        examples=["Docs search app", "Policy QA", "Support knowledge assistant"],
    ),
    _family(
        "vector.indexer",
        "Vector index build contract",
        visible_edge=("DocumentBatch+EmbeddingPolicy", "VectorIndexReceipt"),
        hidden_edges=[
            "DocumentBatch->ChunkedDocumentSet",
            "ChunkedDocumentSet+EmbeddingPolicy->EmbeddingBatch",
            "EmbeddingBatch->VectorUpsertPlan",
            "VectorUpsertPlan->VectorIndexReceipt",
        ],
        effects=["model.call", "vector_write", "artifact_write"],
        mutators=["batch_chunker", "artifact_reference", "provenance_wrapper"],
        proofs=["chunking_fixture_test", "embedding_batch_test", "index_receipt_test"],
        pitfalls=["chunking ad hoc", "embedding model version omitted", "upserts not idempotent", "source digest absent"],
        domains=["ai_rag", "data_engineering"],
        runtime_targets=["vector.indexer", "container.job", "kubernetes.job"],
        examples=["Build docs index", "Refresh support index", "Embed contract corpus"],
    ),
    _family(
        "llm.tool",
        "Agent-callable tool contract",
        visible_edge=("ToolInputEnvelope+ToolPolicy", "ToolResultEnvelope"),
        hidden_edges=[
            "ToolInputEnvelope->ToolSchemaValidation",
            "ToolSchemaValidation+ToolPolicy->ToolPermissionDecision",
            "ToolPermissionDecision->ToolExecutionResult",
            "ToolExecutionResult->ToolResultEnvelope",
        ],
        effects=["tool_call", "network_read_optional", "audit_log_write"],
        mutators=["schema_validator_inserter", "redaction_wrapper", "provenance_wrapper"],
        proofs=["tool_schema_test", "permission_gate_test", "tool_audit_receipt_test"],
        pitfalls=["tool bypasses policy", "secrets in result", "schema too loose", "side effects not declared"],
        domains=["agent_tools", "ai"],
        runtime_targets=["llm.tool", "api.endpoint", "local.python"],
        examples=["OpenAPI endpoint as tool", "Search tool", "Report generator tool"],
    ),
    _family(
        "policy.rule",
        "Policy evaluation primitive",
        visible_edge=("ActionContext+PolicySet", "PolicyDecisionReceipt"),
        hidden_edges=[
            "ActionContext+PolicySet->PolicyMatchSet",
            "PolicyMatchSet->DecisionReasonSet",
            "DecisionReasonSet->AllowDenyWarnDecision",
            "AllowDenyWarnDecision->PolicyDecisionReceipt",
        ],
        effects=["policy_check", "audit_log_write"],
        mutators=["filter_predicate", "redaction_wrapper", "output_wrapper"],
        proofs=["policy_fixture_test", "deny_override_test", "decision_receipt_test"],
        pitfalls=["policy names duplicated", "deny precedence unclear", "reason missing", "decision not audited"],
        domains=["security", "compliance", "agent_tools"],
        runtime_targets=["policy.rule", "local.python", "api.endpoint"],
        examples=["Tool permission rule", "Data access rule", "Exception approval rule"],
    ),
    _family(
        "auth.middleware",
        "Authentication and authorization middleware contract",
        visible_edge=("Request+Credentials+AuthPolicy", "AuthorizedRequestReceipt"),
        hidden_edges=[
            "Credentials->IdentityAssertion",
            "IdentityAssertion+AuthPolicy->ScopeDecision",
            "ScopeDecision->AuthorizedRequest",
            "AuthorizedRequest->AuthorizedRequestReceipt",
        ],
        effects=["network_read_optional", "audit_log_write"],
        mutators=["redaction_wrapper", "schema_validator_inserter", "output_wrapper"],
        proofs=["authn_fixture_test", "scope_matrix_test", "audit_receipt_test"],
        pitfalls=["authn and authz mixed", "scope matrix duplicated", "token logged", "anonymous bypass"],
        domains=["security", "backend_api"],
        runtime_targets=["auth.middleware", "api.endpoint", "service.group"],
        examples=["RBAC gate", "SSO callback auth", "Tenant scope middleware"],
    ),
    _family(
        "rate.limit.middleware",
        "Rate limit gate contract",
        visible_edge=("Request+QuotaPolicy", "RateLimitDecisionReceipt"),
        hidden_edges=[
            "Request+QuotaPolicy->QuotaKey",
            "QuotaKey->QuotaWindowState",
            "QuotaWindowState->AllowThrottleRejectDecision",
            "AllowThrottleRejectDecision->RateLimitDecisionReceipt",
        ],
        effects=["cache_read", "cache_write", "audit_log_write_optional"],
        mutators=["cache_wrapper", "output_wrapper", "retry_wrapper"],
        proofs=["quota_window_test", "burst_policy_test", "header_contract_test"],
        pitfalls=["tenant key missing", "clock skew ignored", "headers absent", "cache unavailable path untested"],
        domains=["backend_api", "security"],
        runtime_targets=["rate.limit.middleware", "api.endpoint"],
        examples=["API quota gate", "Webhook burst limiter", "Tool call throttle"],
    ),
    _family(
        "ui.component",
        "Reusable UI component contract",
        visible_edge=("ComponentProps+DesignTokens", "RenderedComponentArtifact"),
        hidden_edges=[
            "ComponentProps->ValidatedProps",
            "DesignTokens->StyleContract",
            "ValidatedProps+StyleContract->RenderedComponent",
            "RenderedComponent->RenderedComponentArtifact",
        ],
        effects=["artifact_write"],
        mutators=["field_project", "schema_validator_inserter", "output_wrapper"],
        proofs=["prop_contract_test", "accessibility_test", "visual_smoke_test"],
        pitfalls=["props too loose", "design tokens hard-coded", "keyboard path untested", "mobile overflow"],
        domains=["frontend", "design_system"],
        runtime_targets=["ui.component", "web.ui"],
        examples=["Data table", "Approval button", "Upload widget"],
    ),
    _family(
        "ui.route",
        "UI route/page model contract",
        visible_edge=("RouteParams+SessionContext", "PageModelReceipt"),
        hidden_edges=[
            "RouteParams+SessionContext->RouteAccessDecision",
            "RouteAccessDecision->PageDataQuery",
            "PageDataQuery->PageModel",
            "PageModel->PageModelReceipt",
        ],
        effects=["network_read_optional", "artifact_write"],
        mutators=["schema_validator_inserter", "cache_wrapper", "output_wrapper"],
        proofs=["route_guard_test", "page_model_fixture_test", "empty_state_test"],
        pitfalls=["route guard client-only", "loading state missing", "deep link breaks", "data fetch duplicated"],
        domains=["frontend", "backend_api"],
        runtime_targets=["ui.route", "web.ui"],
        examples=["Admin page", "Dashboard route", "Settings route"],
    ),
    _family(
        "dashboard",
        "Business dashboard artifact contract",
        visible_edge=("MetricSources+DashboardPolicy", "DashboardArtifactReceipt"),
        hidden_edges=[
            "MetricSources->MetricQuerySet",
            "MetricQuerySet+DashboardPolicy->ChartModelSet",
            "ChartModelSet->AccessFilteredDashboard",
            "AccessFilteredDashboard->DashboardArtifactReceipt",
        ],
        effects=["database_read", "artifact_write"],
        mutators=["cache_wrapper", "artifact_materialize", "output_wrapper"],
        proofs=["dashboard_smoke_test", "metric_fixture_test", "access_filter_test"],
        pitfalls=["metric definitions duplicated", "empty state absent", "access filtering skipped", "charts not source-linked"],
        domains=["analytics", "frontend"],
        runtime_targets=["dashboard", "web.ui", "artifact.static"],
        examples=["Ops dashboard", "Security dashboard", "Sales report dashboard"],
    ),
    _family(
        "alert.rule",
        "Monitoring alert rule contract",
        visible_edge=("MetricWindow+AlertPolicy", "AlertDecisionReceipt"),
        hidden_edges=[
            "MetricWindow+AlertPolicy->ThresholdEvaluation",
            "ThresholdEvaluation->NoiseSuppressionDecision",
            "NoiseSuppressionDecision->AlertRoute",
            "AlertRoute->AlertDecisionReceipt",
        ],
        effects=["metric_read", "notification_write_optional", "audit_log_write"],
        mutators=["filter_predicate", "retry_wrapper", "output_wrapper"],
        proofs=["threshold_fixture_test", "suppression_test", "routing_receipt_test"],
        pitfalls=["alert noise", "threshold unversioned", "owner missing", "recovery condition absent"],
        domains=["observability", "devops"],
        runtime_targets=["alert.rule", "monitoring"],
        examples=["Latency alert", "Failed job alert", "Schema drift alert"],
    ),
    _family(
        "runbook",
        "Operational runbook contract",
        visible_edge=("IncidentContext+RunbookPolicy", "ActionChecklistReceipt"),
        hidden_edges=[
            "IncidentContext->IncidentClassification",
            "IncidentClassification+RunbookPolicy->ActionChecklist",
            "ActionChecklist->ApprovalOrEscalationDecision",
            "ApprovalOrEscalationDecision->ActionChecklistReceipt",
        ],
        effects=["human_action_required", "audit_log_write"],
        mutators=["output_wrapper", "provenance_wrapper", "redaction_wrapper"],
        proofs=["incident_fixture_test", "checklist_completeness_test", "approval_gate_test"],
        pitfalls=["commands not gated", "ownership unclear", "rollback absent", "secrets in instructions"],
        domains=["operations", "devops"],
        runtime_targets=["runbook", "documentation"],
        examples=["Database outage runbook", "Security incident runbook", "Rollback runbook"],
    ),
    _family(
        "security.compliance.workflow",
        "Security/compliance workflow contract",
        visible_edge=("ControlContext+EvidencePolicy", "ComplianceEvidenceReceipt"),
        hidden_edges=[
            "ControlContext+EvidencePolicy->EvidenceCollectionPlan",
            "EvidenceCollectionPlan->EvidenceArtifactSet",
            "EvidenceArtifactSet->ControlDecision",
            "ControlDecision->ComplianceEvidenceReceipt",
        ],
        effects=["artifact_read", "artifact_write", "audit_log_write"],
        mutators=["redaction_wrapper", "provenance_wrapper", "schema_validator_inserter"],
        proofs=["evidence_fixture_test", "redaction_test", "control_receipt_test"],
        pitfalls=["evidence stale", "PII not redacted", "control owner missing", "audit trail incomplete"],
        domains=["security", "compliance"],
        runtime_targets=["workflow.group", "dashboard", "container.job"],
        examples=["SOC 2 evidence export", "Access review workflow", "GDPR deletion workflow"],
    ),
    _family(
        "test.fixture",
        "Reusable test fixture contract",
        visible_edge=("FixturePolicy+SchemaContract", "TestDatasetReceipt"),
        hidden_edges=[
            "FixturePolicy+SchemaContract->FixtureGenerationPlan",
            "FixtureGenerationPlan->SyntheticRecordSet",
            "SyntheticRecordSet->FixtureValidationReport",
            "FixtureValidationReport->TestDatasetReceipt",
        ],
        effects=["artifact_write"],
        mutators=["schema_validator_inserter", "redaction_wrapper", "output_wrapper"],
        proofs=["schema_fixture_test", "determinism_test", "privacy_boundary_test"],
        pitfalls=["fixture contains PII", "random seed unstated", "schema drift untested", "edge cases absent"],
        domains=["testing", "software_engineering"],
        runtime_targets=["test.fixture", "local.python"],
        examples=["CSV import fixture", "Webhook replay fixture", "Auth matrix fixture"],
    ),
    _family(
        "contract.test",
        "Service/API contract proof primitive",
        visible_edge=("ServiceSpec+ExampleSet", "ContractTestReceipt"),
        hidden_edges=[
            "ServiceSpec+ExampleSet->ContractAssertionSet",
            "ContractAssertionSet->TestExecutionPlan",
            "TestExecutionPlan->ContractViolationSet",
            "ContractViolationSet->ContractTestReceipt",
        ],
        effects=["subprocess_optional", "network_read_optional", "artifact_write"],
        mutators=["schema_validator_inserter", "output_wrapper", "provenance_wrapper"],
        proofs=["positive_example_test", "negative_example_test", "receipt_schema_test"],
        pitfalls=["only happy path tested", "contract examples stale", "network dependency flaky", "violations not typed"],
        domains=["testing", "backend_api"],
        runtime_targets=["contract.test", "ci.workflow", "local.python"],
        examples=["OpenAPI contract test", "Webhook contract test", "SDK client contract test"],
    ),
    _family(
        "mock.server",
        "Local fake service contract",
        visible_edge=("ApiSpec+MockPolicy", "MockServerReceipt"),
        hidden_edges=[
            "ApiSpec+MockPolicy->MockRouteSet",
            "MockRouteSet->FixtureResponseSet",
            "FixtureResponseSet->MockServerConfig",
            "MockServerConfig->MockServerReceipt",
        ],
        effects=["local_network_bind", "artifact_write"],
        mutators=["schema_validator_inserter", "output_wrapper", "cache_wrapper"],
        proofs=["route_fixture_test", "error_response_test", "contract_compatibility_test"],
        pitfalls=["mock diverges from spec", "error cases absent", "stateful behavior hidden", "port conflict unhandled"],
        domains=["testing", "developer_tools"],
        runtime_targets=["mock.server", "local.http", "container.python"],
        examples=["Stripe mock server", "Webhook mock server", "CRM API mock"],
    ),
    # ── ALGORITHM / FUNCTION families (owner ask 2026-07-01: mine public source-backed
    #    algorithmic capabilities — Google OR-Tools/ScaNN, Meta FAISS, TheAlgorithms,
    #    RapidFuzz, NetworkX, scikit-learn — as CONTRACTS, never copied code) ──
    _family(
        "algorithm.sort",
        "Ordering algorithm (deterministic)",
        visible_edge=("RecordBatch+SortKeyPolicy", "OrderedRecordBatch"),
        hidden_edges=[
            "RecordBatch+SortKeyPolicy->KeyedRecordBatch",
            "KeyedRecordBatch->ComparatorPlan",
            "ComparatorPlan->OrderedRecordBatch",
        ],
        effects=["cpu_compute"],
        mutators=["field_project", "map_sequence", "output_wrapper"],
        proofs=["ordering_invariant_test", "stability_test", "empty_and_singleton_test", "large_input_perf_benchmark"],
        pitfalls=["unstable sort where stability assumed", "comparator not total order", "external sort not used for oversized input"],
        domains=["algorithms", "data_engineering"],
        runtime_targets=["local.python", "container.python", "sql.proc"],
        examples=["timsort a record batch", "top-k selection", "external merge sort of large file"],
    ),
    _family(
        "algorithm.graph",
        "Graph/network algorithm (deterministic)",
        visible_edge=("NodeTable+EdgeTable+GraphQueryPolicy", "GraphResult+GraphReceipt"),
        hidden_edges=[
            "NodeTable+EdgeTable->AdjacencyModel",
            "AdjacencyModel+GraphQueryPolicy->TraversalPlan",
            "TraversalPlan->GraphResult",
            "GraphResult->GraphReceipt",
        ],
        effects=["cpu_compute"],
        mutators=["map_sequence", "output_wrapper", "cache_wrapper"],
        proofs=["known_path_fixture_test", "complexity_bound_check", "disconnected_graph_test", "cycle_handling_test"],
        pitfalls=["negative-weight edges with Dijkstra", "unbounded recursion on cycles", "memory blowup on dense graphs"],
        domains=["algorithms", "graph"],
        runtime_targets=["local.python", "container.python"],
        examples=["shortest path (Dijkstra/A*)", "connected components", "PageRank", "max-flow/min-cut"],
    ),
    _family(
        "algorithm.optimization",
        "Constraint/mathematical optimization (deterministic solver)",
        visible_edge=("OptimizationProblemSpec+SolverPolicy", "SolverResult+SolverReceipt"),
        hidden_edges=[
            "OptimizationProblemSpec->VariableModel",
            "VariableModel+ConstraintSet->SolverModel",
            "SolverModel+SolverPolicy->SolverResult",
            "SolverResult->SolverReceipt",
        ],
        effects=["cpu_compute"],
        mutators=["schema_validator_inserter", "output_wrapper", "retry_wrapper"],
        proofs=["constraint_satisfaction_test", "objective_score_check", "infeasible_case_test", "fixture_solution_test"],
        pitfalls=["infeasible model returned as feasible", "no time limit on solve", "non-determinism unrecorded"],
        domains=["algorithms", "operations_research"],
        runtime_targets=["local.python", "container.python", "kubernetes.job"],
        examples=["vehicle routing (OR-Tools)", "shift scheduling", "bin packing", "linear/CP-SAT programming"],
    ),
    _family(
        "algorithm.fuzzy_match",
        "Fuzzy string similarity (deterministic)",
        visible_edge=("StringPair+MatchPolicy", "SimilarityScore+MatchReceipt"),
        hidden_edges=[
            "StringPair->NormalizedStringPair",
            "NormalizedStringPair->SimilarityFeatureVector",
            "SimilarityFeatureVector+ThresholdPolicy->MatchReceipt",
        ],
        effects=["cpu_compute"],
        mutators=["field_rename", "map_sequence", "output_wrapper"],
        proofs=["known_pair_fixture_test", "symmetry_test", "unicode_test", "threshold_boundary_test"],
        pitfalls=["normalization skipped", "wrong metric for data shape", "threshold hardcoded", "no explainability receipt"],
        domains=["algorithms", "entity_resolution"],
        runtime_targets=["local.python", "container.python"],
        examples=["Levenshtein / Jaro-Winkler name match", "token-sort ratio", "phonetic match"],
    ),
    _family(
        "algorithm.near_duplicate",
        "Near-duplicate / LSH detection (deterministic)",
        visible_edge=("RecordBatch+BlockingPolicy", "DuplicateClusterSet+DedupeReceipt"),
        hidden_edges=[
            "RecordBatch->FingerprintBatch",
            "FingerprintBatch+BlockingPolicy->CandidateBlockingKeys",
            "CandidateBlockingKeys->CandidatePairSet",
            "CandidatePairSet->DuplicateClusterSet",
            "DuplicateClusterSet->DedupeReceipt",
        ],
        effects=["cpu_compute"],
        mutators=["map_sequence", "cache_wrapper", "output_wrapper"],
        proofs=["recall_at_threshold_test", "collision_rate_check", "block_key_stability_test", "cluster_transitivity_test"],
        pitfalls=["quadratic blowup without blocking", "hash seed unrecorded", "over-merging via transitive closure"],
        domains=["algorithms", "entity_resolution", "data_quality"],
        runtime_targets=["local.python", "container.python", "kubernetes.job"],
        examples=["MinHash/LSH blocking", "SimHash fingerprint", "customer dedupe clusters"],
    ),
    _family(
        "algorithm.vector_search",
        "Approximate nearest-neighbor vector search (deterministic index)",
        visible_edge=("DenseVectorMatrix+QueryVectorBatch+IndexPolicy", "NeighborIdScoreBatch+SearchReceipt"),
        hidden_edges=[
            "DenseVectorMatrix+IndexPolicy->TrainedVectorIndex",
            "TrainedVectorIndex->SerializedIndexArtifact",
            "TrainedVectorIndex+QueryVectorBatch->NeighborIdScoreBatch",
            "NeighborIdScoreBatch->SearchReceipt",
        ],
        effects=["cpu_compute", "memory_index_build", "artifact_write_optional"],
        mutators=["artifact_materialize", "cache_wrapper", "output_wrapper"],
        proofs=["recall_at_k_test", "serialization_roundtrip_test", "dimension_mismatch_error_test", "latency_benchmark"],
        pitfalls=["metric mismatch (L2 vs inner-product)", "index not trained before query", "recall/latency tradeoff unrecorded"],
        domains=["algorithms", "vector_search", "retrieval"],
        runtime_targets=["local.python", "container.python", "pgvector", "kubernetes.job"],
        examples=["FAISS IVF-PQ search", "ScaNN partitioned search", "HNSW index build+query"],
    ),
    _family(
        "function.chain",
        "Reusable multi-function chain (the value unit, not the single fn)",
        visible_edge=("RawInputArtifact+ChainPolicy", "ChainResultArtifact+ChainReceipt"),
        hidden_edges=[
            "RawInputArtifact->NormalizedInput",
            "NormalizedInput->IntermediateArtifactA",
            "IntermediateArtifactA->IntermediateArtifactB",
            "IntermediateArtifactB->ChainResultArtifact",
            "ChainResultArtifact->ChainReceipt",
        ],
        effects=["cpu_compute", "artifact_write_optional"],
        mutators=["map_sequence", "route_to_group_card", "output_wrapper"],
        proofs=["end_to_end_fixture_test", "step_contract_compatibility_test", "no_silent_row_drop_test"],
        pitfalls=["each step regenerated instead of reused", "intermediate contracts mismatch", "chain not promoted to a group card"],
        domains=["algorithms", "software_engineering"],
        runtime_targets=["local.python", "container.python", "workflow.step"],
        examples=["normalize->block->score->decide entity match", "parse->validate->dedupe->load"],
    ),
    # ── TOOLS-WE-BUILD-AND-USE families (owner ask 2026-07-01: our own RapidAPI routes,
    #    1000+ programmatic browsing/scraping combinations, search endpoints, and the
    #    keyword-multiplication query lattice are first-class primitives too) ──
    _family(
        "tool.rapidapi_endpoint",
        "Third-party API endpoint behind a governed key (RapidAPI-style)",
        visible_edge=("ApiRequestEnvelope+KeyRef+QuotaPolicy", "TypedApiResponse+CallReceipt"),
        hidden_edges=[
            "ApiRequestEnvelope+KeyRef->AuthenticatedRequest",
            "AuthenticatedRequest+QuotaPolicy->RateLimitDecision",
            "RateLimitDecision->UpstreamCall",
            "UpstreamCall->TypedApiResponse",
            "TypedApiResponse->CallReceipt",
        ],
        effects=["network_read", "network_write_optional", "cost_incurring", "credential_use"],
        mutators=["retry_wrapper", "cache_wrapper", "idempotency_wrapper", "output_wrapper"],
        proofs=["provider_contract_test", "auth_scope_test", "quota_backoff_test", "redaction_receipt", "sandbox_smoke_test"],
        pitfalls=["raw key logged", "no backoff on 429", "response schema drift unhandled", "cost per call unrecorded"],
        domains=["integrations", "developer_tools"],
        runtime_targets=["container.python", "api.endpoint", "workflow.worker"],
        examples=["RapidAPI enrichment call", "geocoding endpoint", "third-party search endpoint"],
    ),
    _family(
        "tool.browser_automation",
        "Programmatic browser drive (one of many escalation combinations)",
        visible_edge=("NavigationPlan+BrowserPolicy", "PageStateArtifact+AutomationReceipt"),
        hidden_edges=[
            "NavigationPlan->BrowserSession",
            "BrowserSession+BrowserPolicy->RenderedPageState",
            "RenderedPageState->PageStateArtifact",
            "PageStateArtifact->AutomationReceipt",
        ],
        effects=["network_read", "browser_state_read", "browser_state_write_optional", "artifact_write"],
        mutators=["retry_wrapper", "cache_wrapper", "output_wrapper"],
        proofs=["selector_contract_test", "screenshot_ref_optional", "robots_policy_review_optional", "escalation_ladder_recorded"],
        pitfalls=["brittle selectors", "no headless/stealth escalation rung", "side effect on submit unreviewed", "challenge page not handled"],
        domains=["web_automation", "acquisition"],
        runtime_targets=["browser.playwright", "browser.cdp", "container.python"],
        examples=["CDP-driven Open WebUI call", "Playwright form fill", "headless render for extraction"],
    ),
    _family(
        "tool.web_scraper",
        "Structured extraction from web pages (governed, license-aware)",
        visible_edge=("UrlOrSnapshot+ExtractionPolicy", "NormalizedTableBatch+ExtractionReceipt"),
        hidden_edges=[
            "UrlOrSnapshot->PageSnapshot",
            "PageSnapshot->CandidateBlockSet",
            "CandidateBlockSet->NormalizedTableBatch",
            "NormalizedTableBatch->ExtractionReceipt",
        ],
        effects=["network_read", "artifact_write"],
        mutators=["pagination_expander", "retry_wrapper", "output_wrapper"],
        proofs=["selector_fixture_test", "row_count_check", "field_presence_check", "robots_policy_review", "provenance_receipt"],
        pitfalls=["robots.txt ignored", "restricted content republished", "pagination truncated silently", "no provenance"],
        domains=["acquisition", "web_automation"],
        runtime_targets=["container.python", "browser.playwright", "workflow.worker"],
        examples=["page->structured table", "site crawl map", "listing extraction with provenance"],
    ),
    _family(
        "tool.search_provider",
        "Pluggable search/discovery provider behind the search port",
        visible_edge=("SearchQuery+SourcePolicy", "RankedResultPage+SearchReceipt"),
        hidden_edges=[
            "SearchQuery+SourcePolicy->ProviderFanout",
            "ProviderFanout->MergedDedupedHits",
            "MergedDedupedHits->RankedResultPage",
            "RankedResultPage->SearchReceipt",
        ],
        effects=["network_read", "cost_incurring_optional", "credential_use_optional"],
        mutators=["retry_wrapper", "cache_wrapper", "output_wrapper"],
        proofs=["provider_contract_test", "graceful_degradation_test", "dedupe_key_test", "escalation_ladder_recorded"],
        pitfalls=["single provider hardwired", "no keyless-first fallback", "results not deduped", "quota unhandled"],
        domains=["acquisition", "retrieval"],
        runtime_targets=["container.python", "api.endpoint"],
        examples=["arxiv/PyPI/GitHub keyless fan-out", "Brave key-gated search", "google-dork inurl:/intitle: expansion"],
    ),
    _family(
        "tool.query_lattice",
        "Keyword-multiplication query lattice (scored, not blind Cartesian)",
        visible_edge=("DimensionBanks+SchedulePolicy", "ScheduledQueryBatch+LatticeReceipt"),
        hidden_edges=[
            "DimensionBanks->CandidateQueryUniverse",
            "CandidateQueryUniverse->ScoredQuerySet",
            "ScoredQuerySet+SchedulePolicy->DedupedDiverseBatch",
            "DedupedDiverseBatch->ScheduledQueryBatch",
            "ScheduledQueryBatch->LatticeReceipt",
        ],
        effects=["cpu_compute", "artifact_write"],
        mutators=["map_sequence", "cache_wrapper", "output_wrapper"],
        proofs=["yield_score_recorded", "dedupe_near_query_test", "diversity_coverage_check", "budget_cap_enforced"],
        pitfalls=["full Cartesian executed", "no yield model", "duplicate queries", "high-cost sources unbudgeted"],
        domains=["acquisition"],
        runtime_targets=["container.python", "workflow.worker"],
        examples=["person x question x industry x problem lattice", "google-dork lattice", "job-series x grade x duty lattice"],
    ),
    # ── VISUALIZATION / MEDIA families (owner ask 2026-07-01: deterministic render/export
    #    jobs vs seeded/probabilistic generation + validation receipts; PyPI mining) ──
    _family(
        "viz.chart",
        "Render a chart from data (deterministic)",
        visible_edge=("DataFrame+ChartIntent+RenderPolicy", "ChartArtifact+RenderReceipt"),
        hidden_edges=[
            "DataFrame+ChartIntent->ChartSpec",
            "ChartSpec+RenderPolicy->RendererPlan",
            "RendererPlan->ChartArtifact",
            "ChartArtifact->RenderReceipt",
        ],
        effects=["artifact_write", "file_write_optional"],
        mutators=["field_project", "artifact_materialize", "output_wrapper"],
        proofs=["schema_mapping_test", "render_smoke_test", "artifact_exists_test", "axis_label_check", "visual_regression_optional"],
        pitfalls=["wrong column mapping", "missing series silently dropped", "renderer choice unrecorded", "no artifact digest"],
        domains=["visualization", "reporting"],
        runtime_targets=["local.python", "container.python", "browser.render_optional"],
        examples=["dataframe->line chart (matplotlib/plotly/vega-lite)", "KPI chart pack", "anomaly chart"],
    ),
    _family(
        "viz.graph_network",
        "Render a network/graph diagram (deterministic, seeded layout)",
        visible_edge=("NodeTable+EdgeTable+LayoutPolicy", "GraphDiagramArtifact+LayoutReceipt"),
        hidden_edges=[
            "NodeTable+EdgeTable->GraphModel",
            "GraphModel+LayoutPolicy->LayoutPlan",
            "LayoutPlan->GraphDiagramArtifact",
            "GraphDiagramArtifact->LayoutReceipt",
        ],
        effects=["cpu_compute", "artifact_write"],
        mutators=["artifact_materialize", "output_wrapper", "cache_wrapper"],
        proofs=["node_count_check", "edge_count_check", "layout_seed_recorded", "artifact_snapshot_test"],
        pitfalls=["layout seed unrecorded (non-reproducible)", "legend/encoding missing", "dense graph unreadable"],
        domains=["visualization", "diagramming"],
        runtime_targets=["local.python", "container.python", "browser.render_optional"],
        examples=["package dependency graph", "infra diagram (Graphviz)", "Mermaid sequence diagram"],
    ),
    _family(
        "media.image_processing",
        "Deterministic image transform/export",
        visible_edge=("ImageArtifact+TransformSpec+OutputFormatPolicy", "ImageArtifact+ImageTransformReceipt"),
        hidden_edges=[
            "ImageArtifact->DecodedImage",
            "DecodedImage+TransformSpec->TransformedImage",
            "TransformedImage+OutputFormatPolicy->EncodedImage",
            "EncodedImage->ImageTransformReceipt",
        ],
        effects=["file_read", "file_write", "artifact_write"],
        mutators=["path_to_bytes", "bytes_to_text", "artifact_materialize", "output_wrapper"],
        proofs=["output_exists", "dimensions_match", "format_match", "metadata_policy_check", "visual_regression_optional"],
        pitfalls=["aspect ratio distorted", "color space unhandled", "EXIF/PII metadata leaked", "no digest receipt"],
        domains=["media", "assets"],
        runtime_targets=["local.python", "container.python", "cli.command"],
        examples=["resize+convert (Pillow/ImageMagick)", "thumbnail batch", "composite/watermark"],
    ),
    _family(
        "media.video_processing",
        "Deterministic video/gif transform, trim, caption, transcode",
        visible_edge=("VideoOrFrameArtifact+EditSpec+ExportPolicy", "MediaArtifact+MediaExportReceipt"),
        hidden_edges=[
            "VideoOrFrameArtifact->DecodedMedia",
            "DecodedMedia+EditSpec->EditedMedia",
            "EditedMedia+ExportPolicy->EncodedMedia",
            "EncodedMedia->MediaExportReceipt",
        ],
        effects=["file_read", "file_write", "cpu_compute", "gpu_compute_optional", "artifact_write"],
        mutators=["artifact_materialize", "retry_wrapper", "output_wrapper"],
        proofs=["duration_check", "codec_check", "resolution_check", "frame_count_check", "file_size_budget_check"],
        pitfalls=["codec mismatch", "audio track dropped", "gif palette not optimized", "unbounded output size"],
        domains=["media", "assets"],
        runtime_targets=["local.python", "container.python", "cli.command", "kubernetes.job"],
        examples=["frames->optimized GIF (ffmpeg)", "trim+caption+export clip (MoviePy)", "transcode to web codec"],
    ),
    _family(
        "package.pypi_scan",
        "Extract a package API-surface card without copying source",
        visible_edge=("PackageName+VersionPolicy+LicensePolicy", "PackageApiSurfaceCard+SourceRefBundle"),
        hidden_edges=[
            "PackageName->ProjectMetadata",
            "ProjectMetadata->ReleaseVersionSet",
            "ReleaseVersionSet->DependencySummary",
            "ProjectMetadata+DocsRefs->CandidateApiSurfaceCard",
            "CandidateApiSurfaceCard->LicenseReviewObligation",
        ],
        effects=["network_read", "artifact_write"],
        mutators=["retry_wrapper", "cache_wrapper", "output_wrapper"],
        proofs=["source_ref_resolution", "version_pin_check", "license_policy_review", "signature_extraction_test_optional"],
        pitfalls=["package code copied not contracted", "version unpinned", "license unreviewed", "no source ref"],
        domains=["package_mining", "acquisition"],
        runtime_targets=["container.python", "network.client"],
        examples=["PyPI JSON API -> API surface card", "npm metadata -> exported symbols", "dependency graph card"],
    ),
    _family(
        "genai.image_generation",
        "Probabilistic image generation with deterministic wrapper + validation",
        visible_edge=("ImagePromptEnvelope+ModelPolicy+SafetyPolicy+SeedPolicy", "ImageCandidateSet+GenerationReceipt"),
        hidden_edges=[
            "ImagePromptEnvelope+SafetyPolicy->ScreenedPromptEnvelope",
            "ScreenedPromptEnvelope+ModelPolicy+SeedPolicy->ModelCall",
            "ModelCall->ImageCandidateSet",
            "ImageCandidateSet->GenerationReceipt",
        ],
        effects=["model_call", "network_write", "artifact_write", "cost_incurring"],
        mutators=["retry_wrapper", "output_wrapper", "artifact_materialize"],
        proofs=["provider_contract_test", "prompt_policy_check", "dimensions_check", "safety_receipt", "model_version_recorded", "provenance_receipt"],
        pitfalls=["seed unrecorded (non-reproducible)", "safety gate skipped", "likeness/copyright unreviewed", "cost per accepted artifact unrecorded"],
        domains=["media", "genai"],
        runtime_targets=["api.endpoint", "container.python", "workflow.worker"],
        examples=["prompt->image candidate set (OpenAI Images/Diffusers)", "brand image variants + ranking"],
    ),
    _family(
        "genai.video_generation",
        "Probabilistic video generation with deterministic wrapper + validation",
        visible_edge=("StoryboardSpec+VideoModelPolicy+SafetyPolicy", "VideoCandidateSet+VideoGenerationReceipt"),
        hidden_edges=[
            "StoryboardSpec+SafetyPolicy->ScreenedStoryboard",
            "ScreenedStoryboard+VideoModelPolicy->ModelCall",
            "ModelCall->VideoCandidateSet",
            "VideoCandidateSet->VideoGenerationReceipt",
        ],
        effects=["model_call", "network_write", "artifact_write", "cost_incurring"],
        mutators=["retry_wrapper", "output_wrapper", "artifact_materialize"],
        proofs=["provider_contract_test", "duration_check", "aspect_ratio_check", "safety_receipt", "model_version_recorded", "provenance_receipt"],
        pitfalls=["no storyboard alignment score", "safety gate skipped", "cost unbounded", "provenance absent"],
        domains=["media", "genai"],
        runtime_targets=["api.endpoint", "container.python", "workflow.worker"],
        examples=["storyboard->video candidates (Runway/Veo)", "animated chart video", "product demo clip"],
    ),
]


def generate_rows() -> list[dict[str, Any]]:
    return sorted(PRIMITIVE_KIND_FAMILIES, key=lambda row: str(row["primitive_kind"]))


def write_rows(rows: list[dict[str, Any]]) -> dict[str, Any]:
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(
        "".join(json.dumps(row, sort_keys=True, separators=(",", ":"), ensure_ascii=True) + "\n" for row in rows),
        encoding="utf-8",
    )
    by_domain: dict[str, int] = {}
    for row in rows:
        for domain in row.get("domains") or []:
            by_domain[str(domain)] = by_domain.get(str(domain), 0) + 1
    manifest = {
        "record_type": "aidevexplorer_primitive_kind_family_catalog_manifest",
        "path": AIDEVEXPLORER_PRIMITIVE_KIND_FAMILY_CATALOG_PATH,
        "row_count": len(rows),
        "primitive_kinds": [row["primitive_kind"] for row in rows],
        "domain_counts": dict(sorted(by_domain.items())),
        "source_family": AIDEVEXPLORER_PRIMITIVE_KIND_SOURCE_FAMILY,
        "source_evidence_status": AIDEVEXPLORER_PRIMITIVE_KIND_SOURCE_EVIDENCE_STATUS,
        "candidate": True,
        "serves_truth": False,
    }
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args(argv)
    rows = generate_rows()
    manifest: dict[str, Any] = {
        "row_count": len(rows),
        "would_write": AIDEVEXPLORER_PRIMITIVE_KIND_FAMILY_CATALOG_PATH,
        "candidate": True,
        "serves_truth": False,
    }
    if not args.check_only:
        manifest = write_rows(rows)
    print(json.dumps(manifest, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
