#!/usr/bin/env python3
"""scripts.path_router_zoo — ROUTER METHODOLOGIES: choose the graph CONFIG per QUERY instead of one global
champion (the measured finding behind this: always-union LOSES to racing+picking, and different query classes
have different winners). A ZOO of contract-substitutable routers behind one selector, raced by receipt:

  * global_champion   — graph_autotune.active_config() for every query (the incumbent; REUSED, not rebuilt)
  * always_union      — the full multi-path union config (the known loser; kept as the labelled baseline)
  * query_type_rules  — deterministic table keyed by the analyze stage's query_type
  * difficulty_gate   — cheap config for easy queries, escalating machinery as QPP difficulty rises
  * learned_table     — PER-CLASS champions learned by racing (path_graph_bench.quality_bench per class) and
                        persisted (dist/path-router/learned_table.json) — the contextual-router evolution of
                        graph_autotune from "one champion" to "champion per query class"; self-heals to the
                        global champion for unseen classes.

The query CLASS is deterministic: the graph's own analyze options (query_type × difficulty), so routing costs
one 0-token analyze pass. Adding a router = a new ROUTERS row, never a rewrite; a bandit/learned-model router
plugs in as another row behind the same contract (query -> config).

serves_truth=false — routed configs and race receipts are measurements/candidates, never served truth.

    PYTHONPATH=. python3 scripts/path_router_zoo.py --self-test
    PYTHONPATH=. python3 scripts/path_router_zoo.py --race [--sample 200]   # race routers, persist the table
"""
from __future__ import annotations

import sys
from pathlib import Path

# ── substrate-root bootstrap (sentinel; mirrors scripts/capability_retrieval_mcp_server.py) ──────────────────
_here_boot = Path(__file__).resolve()
_sbc_boot = next((q for q in _here_boot.parents if (q / "scripts" / "_repo_paths.py").exists()),
                 _here_boot.parents[1])
if str(_sbc_boot) not in sys.path:
    sys.path.insert(0, str(_sbc_boot))
from scripts._repo_paths import install as _install_code_roots, resource  # noqa: E402

_install_code_roots()

import argparse  # noqa: E402
import json  # noqa: E402
from typing import Any, Callable, Optional  # noqa: E402

from scripts import graph_autotune as _tune  # noqa: E402  REUSE: the global champion + fallback config
from scripts import path_graph_bench as _bench  # noqa: E402  REUSE: the racer, metrics, corpus, labelled set
from scripts import pipeline_path_graph as _graph  # noqa: E402  REUSE: analyze stage + run_path

BOUNDARY: dict[str, Any] = {"candidate": True, "serves_truth": False}

_TABLE_DIRNAME = "path-router"          # under dist/ (learned artifact; regenerated by --race)
_UNION_CONFIG: dict[str, str] = {"expand": "none", "search": "all", "fuse": "combmnz", "rerank": "none"}
_CHEAP_CONFIG: dict[str, str] = {"expand": "none", "search": "lexical", "fuse": "combmnz", "rerank": "none"}
_SEMANTIC_CONFIG: dict[str, str] = {"expand": "none", "search": "semantic_embedding", "fuse": "combmnz",
                                    "rerank": "none"}
_HARD_CONFIG: dict[str, str] = {"expand": "prf_rm3", "search": "all", "fuse": "combmnz", "rerank": "none"}
#: query_type -> config for the rules router (deterministic; edge-syntax queries lean on typed-role retrieval)
_TYPE_RULES: dict[str, dict[str, str]] = {
    "edge_syntax": {"expand": "none", "search": "hierarchical", "fuse": "combmnz", "rerank": "none"},
    "multi_capability": {"expand": "facet_expand", "search": "all", "fuse": "combmnz", "rerank": "none"},
    "single_capability": _SEMANTIC_CONFIG,
    "vague": _HARD_CONFIG,
}


def default_table_path() -> Path:
    return resource("dist") / _TABLE_DIRNAME / "learned_table.json"


def query_class(query: str) -> str:
    """The deterministic query class: the graph's OWN analyze options (query_type × QPP difficulty) — one
    0-token pass, single-sourced from the live stage (never a parallel classifier)."""
    ctx = _graph.apply_stage({"query": query, "cards": [], **BOUNDARY}, "analyze", "difficulty_qpp")
    a = ctx.get("analysis") or {}
    return f"{a.get('query_type', 'unknown')}|{a.get('difficulty', 'unknown')}"


# ── the ROUTER ZOO: name -> fn(query, table) -> ranking config. A new router = a new row. ────────────────────
def _r_global_champion(query: str, table: Optional[dict[str, Any]]) -> dict[str, str]:
    return _tune.active_config()


def _r_always_union(query: str, table: Optional[dict[str, Any]]) -> dict[str, str]:
    return dict(_UNION_CONFIG)


def _r_query_type_rules(query: str, table: Optional[dict[str, Any]]) -> dict[str, str]:
    qtype = query_class(query).split("|", 1)[0]
    return dict(_TYPE_RULES.get(qtype, _UNION_CONFIG))


def _r_difficulty_gate(query: str, table: Optional[dict[str, Any]]) -> dict[str, str]:
    difficulty = query_class(query).split("|", 1)[1]
    return dict({"easy": _CHEAP_CONFIG, "medium": _SEMANTIC_CONFIG}.get(difficulty, _HARD_CONFIG))


def _r_learned_table(query: str, table: Optional[dict[str, Any]]) -> dict[str, str]:
    table = table if table is not None else load_table()
    cfg = (table or {}).get("classes", {}).get(query_class(query))
    return dict(cfg) if cfg else _tune.active_config()   # self-heal: unseen class -> the global champion


ROUTERS: dict[str, Callable[[str, Optional[dict[str, Any]]], dict[str, str]]] = {
    "global_champion": _r_global_champion,
    "always_union": _r_always_union,
    "query_type_rules": _r_query_type_rules,
    "difficulty_gate": _r_difficulty_gate,
    "learned_table": _r_learned_table,
}


def route(query: str, *, router: str = "learned_table", table: Optional[dict[str, Any]] = None) -> dict[str, Any]:
    """The serving front door: query -> {config, router, class}. 0-token, deterministic."""
    if router not in ROUTERS:
        raise ValueError(f"unknown router {router!r}; routers are {sorted(ROUTERS)}")
    return {"config": ROUTERS[router](query, table), "router": router, "class": query_class(query), **BOUNDARY}


# ── LEARNING: per-class champions via the EXISTING racer (quality_bench per class) ───────────────────────────
def train_learned_table(cards: list[dict[str, Any]], labelled: list[dict[str, str]],
                        *, k: int = _bench._DEFAULT_K) -> dict[str, Any]:  # noqa: SLF001 single-source k
    """Group the labelled queries by class, race the ranking configs WITHIN each class (quality_bench — the
    one racer, reused), and record each class's champion. Classes with one query still get a champion (noted:
    thin evidence — more labelled data sharpens the table; the gold-set seed grows it)."""
    by_class: dict[str, list[dict[str, str]]] = {}
    for q in labelled:
        by_class.setdefault(query_class(q["query"]), []).append(q)
    classes: dict[str, dict[str, Any]] = {}
    for cls, queries in sorted(by_class.items()):
        rec = _bench.quality_bench(cards, queries, k=k)
        champ = {s: rec["champion"][s] for s in _bench._RANKING_STAGES}  # noqa: SLF001 single-source stages
        classes[cls] = {**champ, "ndcg_at_k": rec["champion"]["ndcg_at_k"], "queries": len(queries)}
    return {"record_type": "path_router_learned_table", "classes":
            {c: {kk: v[kk] for kk in ("expand", "search", "fuse", "rerank")} for c, v in classes.items()},
            "class_receipts": classes, "trained_on_queries": len(labelled), **BOUNDARY}


def persist_table(table: dict[str, Any], path: Optional[Path] = None) -> Path:
    p = path or default_table_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(table, indent=2, sort_keys=True))
    return p


_TABLE_CACHE: Any = None


def load_table(path: Optional[Path] = None) -> Optional[dict[str, Any]]:
    """The persisted learned table (memoized for the default path). None when never trained."""
    global _TABLE_CACHE
    if path is not None:
        try:
            return json.loads(path.read_text())
        except OSError:
            return None
    if _TABLE_CACHE is None:
        try:
            _TABLE_CACHE = json.loads(default_table_path().read_text())
        except OSError:
            _TABLE_CACHE = False
    return _TABLE_CACHE or None


# ── the RACE: every router over the same labelled set, scored end-to-end ─────────────────────────────────────
def race_routers(cards: list[dict[str, Any]], labelled: list[dict[str, str]],
                 *, k: int = _bench._DEFAULT_K, table: Optional[dict[str, Any]] = None) -> dict[str, Any]:  # noqa: SLF001
    """Route each labelled query per router, run the routed config, score nDCG/recall — the honest comparison
    of routing METHODOLOGIES (per-class routing must EARN its complexity over the single champion)."""
    from scripts.build_primitive_search_index import build_index  # noqa: PLC0415
    index = build_index(cards)
    cache: dict = {}
    fixed = _bench._fixed_prefix()  # noqa: SLF001 — single-source neutral prefix
    receipts = []
    for name in sorted(ROUTERS):
        ndcgs, recalls, distinct_configs = [], [], set()
        for q in labelled:
            cfg = ROUTERS[name](q["query"], table)
            distinct_configs.add(json.dumps(cfg, sort_keys=True))
            run = _graph.run_path(q["query"], cards, {**fixed, **cfg}, index=index, cache=cache)
            ids = [r.get("primitive_id") for r in run["results"]]
            rel = _bench._relevant(q["family"])  # noqa: SLF001 — single-source gold
            ndcgs.append(_bench._ndcg_at_k(ids, rel, k))  # noqa: SLF001
            recalls.append(_bench._recall_at_k(ids, rel, k))  # noqa: SLF001
        n = len(labelled) or 1
        receipts.append({"router": name, "ndcg_at_k": round(sum(ndcgs) / n, 4),
                         "recall_at_k": round(sum(recalls) / n, 4),
                         "distinct_configs_used": len(distinct_configs)})
    ranked = sorted(receipts, key=lambda r: (-r["ndcg_at_k"], -r["recall_at_k"], r["router"]))
    return {"record_type": "path_router_race", "queries": len(labelled), "corpus_cards": len(cards), "k": k,
            "ranked": ranked, "champion_router": ranked[0]["router"] if ranked else None,
            "note": "each router picks a config PER QUERY (class = the graph's own analyze stage); the "
                    "learned_table router must beat the single global champion to earn its complexity. "
                    "Thin per-class evidence sharpens as the labelled gold set grows.", **BOUNDARY}


def _self_test() -> int:
    checks: list[tuple[str, bool]] = []
    cards = _bench.bench_corpus(0)  # the 5 gold families, hermetic (no real-corpus dependence)
    # a labelled set spanning CLASSES: clean single-capability, vague, multi-capability
    labelled = list(_bench._LABELLED_QUERIES) + [  # noqa: SLF001 — single-source labelled families
        {"query": "please just fix up all this messy stuff somehow", "family": "normalize"},
        {"query": "pull words from the scanned page, then get rid of repeated entries", "family": "ocr"},
    ]
    classes = {query_class(q["query"]) for q in labelled}
    checks.append(("the labelled set spans multiple deterministic query classes", len(classes) >= 2))
    checks.append(("query_class is deterministic", query_class("dedupe rows") == query_class("dedupe rows")))

    # (a) every router returns a VALID runnable config; the zoo is real (routers disagree somewhere)
    table = train_learned_table(cards, labelled)
    cfgs = {name: ROUTERS[name]("tidy up messy rows", table) for name in ROUTERS}
    checks.append(("every router returns a config the graph can run",
                   all(set(c) == set(_bench._RANKING_STAGES)  # noqa: SLF001
                       and all(c[s] in _graph.STAGE_OPTIONS[s] for s in c) for c in cfgs.values())))
    checks.append(("routers genuinely disagree for at least one query (a real zoo, not five aliases)",
                   len({json.dumps(c, sort_keys=True) for c in cfgs.values()}) >= 2))

    # (b) the learned table has a champion per observed class and persists/reloads losslessly
    import tempfile  # noqa: PLC0415
    checks.append(("the learned table carries a champion per observed class",
                   set(table["classes"]) == classes))
    with tempfile.TemporaryDirectory() as d:
        p = persist_table(table, Path(d) / "t.json")
        checks.append(("the table persists and reloads byte-equal",
                       json.dumps(load_table(p), sort_keys=True) == json.dumps(table, sort_keys=True)))

    # (c) the RACE: per-class routing never loses to the single global champion ON ITS TRAINING SET
    #     (per-class champions subsume the global one there — the mutation-grade routing claim)
    race = race_routers(cards, labelled, table=table)
    by = {r["router"]: r for r in race["ranked"]}
    checks.append(("learned_table >= global_champion on the training set (routing earns its keep)",
                   by["learned_table"]["ndcg_at_k"] >= by["global_champion"]["ndcg_at_k"] - 1e-9))
    checks.append(("the learned router actually uses more than one config across the set",
                   by["learned_table"]["distinct_configs_used"] >= 2))
    # (d) self-heal: an unseen class routes to the global champion, never crashes
    checks.append(("an unseen class self-heals to the global champion",
                   _r_learned_table("x -> y", {"classes": {}}) == _tune.active_config()))
    # (e) determinism + governance
    checks.append(("the router race is deterministic (byte-identical twice)",
                   json.dumps(race_routers(cards, labelled, table=table), sort_keys=True)
                   == json.dumps(race_routers(cards, labelled, table=table), sort_keys=True)))
    checks.append(("receipts are candidate/serves_truth=false",
                   race["serves_truth"] is False and table["serves_truth"] is False))

    failed = [name for name, ok in checks if not ok]
    for name, ok in checks:
        print(f"  [{'ok' if ok else 'FAIL'}] {name}")
    if failed:
        print(f"\n{len(failed)} FAILURES: {failed}")
        return 1
    print(f"\nPASS - path_router_zoo: {len(ROUTERS)} router methodologies behind one contract (query -> "
          f"config) — global champion, always-union baseline, query-type rules, difficulty gate, and a "
          f"LEARNED per-class champion table (trained by the existing racer, persisted, self-healing) — "
          f"raced end-to-end; the learned router never loses to the single champion on its training set and "
          f"routes distinct configs per class. 0-token routing via the graph's own analyze stage. "
          f"serves_truth=false.")
    return 0


def _race(sample: int) -> int:
    cards = _bench.bench_corpus(sample)
    labelled = list(_bench._LABELLED_QUERIES)  # noqa: SLF001
    table = train_learned_table(cards, labelled)
    persist_table(table)
    rec = race_routers(cards, labelled, table=table)
    out = resource("data") / "dev-intel" / "session_emulation" / "path_router_race_receipt.json"
    out.write_text(json.dumps(rec, indent=2, sort_keys=True))
    print(json.dumps(rec, indent=2, sort_keys=True))
    print(f"\nlearned table: {default_table_path()}\nwritten: {out}")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--race", action="store_true", help="train the per-class table + race all routers")
    ap.add_argument("--sample", type=int, default=200, help="real distractor cards mixed into the corpus")
    args = ap.parse_args(argv)
    if args.self_test:
        return _self_test()
    if args.race:
        return _race(args.sample)
    ap.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
