#!/usr/bin/env python3
"""scripts.real_generation_token_bench — REAL measured tokens, not proxies: run actual generations through
the Ollama harness (local daemon or Ollama Cloud — GLM / Kimi via the `:cloud` lane, OLLAMA_API_KEY for the
direct cloud endpoint) for a deterministic sample of SaaS requirements, and count the API's OWN
prompt_eval_count / eval_count per call. Compares the two build strategies with REAL numbers:

  * PURE generation — every sampled requirement is generated by the model (real tokens counted).
  * OUR system      — requirements the corpus VERIFIABLY covers (saas_requirements_bench hits) cost 0
                      generation tokens (the measured deterministic retrieve+compose lane); only corpus-gap
                      MISSES call the model (and under the flywheel each miss is paid once fleet-wide).

The measured mean tokens-per-component also anchors the fleet simulation's generation-size SWEEP with an
empirical point (does the real model land inside the 500/1500/4000 band?). Network calls are OPT-IN
(--run); the self-test is hermetic via an injected stub transport. serves_truth=false.

    PYTHONPATH=. python3 scripts/real_generation_token_bench.py --self-test
    PYTHONPATH=. python3 scripts/real_generation_token_bench.py --run [--models glm-5.2:cloud,kimi-k2.5:cloud]
"""
from __future__ import annotations

import sys
from pathlib import Path

# ── substrate-root bootstrap (sentinel; mirrors scripts/capability_retrieval_mcp_server.py) ──────────────────
_here_boot = Path(__file__).resolve()
_sbc_boot = next((q for q in _here_boot.parents if (q / "scripts" / "_repo_paths.py").exists()),
                 _here_boot.parents[1])
if str(_sbc_boot) not in sys.path:
    sys.path.insert(0, str(_sbc_boot))
from scripts._repo_paths import install as _install_code_roots, resource  # noqa: E402

_install_code_roots()

import argparse  # noqa: E402
import json  # noqa: E402
import os  # noqa: E402
from typing import Any, Callable, Optional  # noqa: E402

from scripts import saas_requirements_bench as _saas  # noqa: E402  REUSE: the suite + verified coverage

BOUNDARY: dict[str, Any] = {"candidate": True, "serves_truth": False}

#: default model rows for the real harness (env-overridable; the :cloud suffix routes through the signed-in
#: local daemon to Ollama Cloud). A new model = a row in this comma list, never a code change.
_DEFAULT_MODELS = os.environ.get("OH_REAL_GEN_MODELS", "glm-5.2:cloud,kimi-k2.5:cloud")
_BASE = os.environ.get("OH_OLLAMA_BASE", "http://127.0.0.1:11434")
_CLOUD_BASE = os.environ.get("OH_OLLAMA_CLOUD_BASE", "https://ollama.com")
#: generation cap per call — bounds real spend/time; labelled in the receipt (a real component may run longer)
_NUM_PREDICT = 600
_TIMEOUT_S = 180.0
_SAMPLE_HITS = 3     # covered requirements sampled (deterministic head of the covered set)
_SAMPLE_MISSES = 2   # corpus-gap requirements sampled (deterministic head of the uncovered set)


def _ollama_chat(model: str, prompt: str, *, num_predict: int = _NUM_PREDICT) -> dict[str, Any]:
    """One REAL generation via the Ollama chat API (local daemon first; direct cloud with OLLAMA_API_KEY as
    the fallback). Returns the API's own token counts. ok=False on any failure — recorded, never fabricated."""
    import urllib.request  # noqa: PLC0415
    payload = json.dumps({"model": model, "stream": False,
                          "messages": [{"role": "user", "content": prompt}],
                          "options": {"num_predict": num_predict}}).encode()
    attempts = [(f"{_BASE}/api/chat", {})]
    key = os.environ.get("OLLAMA_API_KEY", "")
    if key:
        attempts.append((f"{_CLOUD_BASE}/api/chat", {"Authorization": f"Bearer {key}"}))
    last_err = ""
    for url, extra in attempts:
        try:
            req = urllib.request.Request(url, data=payload,
                                         headers={"Content-Type": "application/json", **extra})
            with urllib.request.urlopen(req, timeout=_TIMEOUT_S) as resp:  # noqa: S310 — opt-in lane
                data = json.loads(resp.read())
            return {"ok": True, "tokens_in": int(data.get("prompt_eval_count") or 0),
                    "tokens_out": int(data.get("eval_count") or 0), "endpoint": url}
        except Exception as exc:  # noqa: BLE001 — try the next transport; report the failure honestly
            last_err = f"{type(exc).__name__}: {exc}"
    return {"ok": False, "tokens_in": 0, "tokens_out": 0, "error": last_err[:200]}


def _gen_prompt(requirement: dict[str, Any]) -> str:
    return (f"Implement this SaaS requirement as a production-quality component "
            f"({requirement['category']}): {requirement['query']}. "
            f"Output the complete code with brief usage notes.")


def sample_requirements(suite: list[dict[str, Any]], uncovered: list[dict[str, Any]],
                        *, n_hits: int = _SAMPLE_HITS, n_misses: int = _SAMPLE_MISSES) -> list[dict[str, Any]]:
    """Deterministic sample: the first n covered + first n uncovered requirements (suite order, no RNG)."""
    uncovered_keys = {(m["category"], m["query"]) for m in uncovered}
    hits = [r for r in suite if (r["category"], r["query"]) not in uncovered_keys][:n_hits]
    misses = [r for r in suite if (r["category"], r["query"]) in uncovered_keys][:n_misses]
    return ([{**r, "hit": True} for r in hits] + [{**r, "hit": False} for r in misses])


def measure_real(sample: list[dict[str, Any]], models: list[str],
                 *, transport: Optional[Callable[..., dict[str, Any]]] = None,
                 workers: int = 1) -> dict[str, Any]:
    """REAL token accounting over the sample: PURE generates everything; OURS generates only the misses.
    ``transport`` is injectable (the self-test uses a deterministic stub; --run uses the real API).
    ``workers`` > 1 fans the real calls out concurrently (result ORDER is preserved, so the receipt shape is
    stable; the token counts themselves are the API's own)."""
    call = transport or _ollama_chat
    per_model: dict[str, Any] = {}
    for model in models:
        calls: list[dict[str, Any]] = []
        pure_total = ours_total = failed = 0
        out_sizes: list[int] = []
        prompts = [_gen_prompt(req) for req in sample]
        if workers > 1:
            from concurrent.futures import ThreadPoolExecutor  # noqa: PLC0415
            with ThreadPoolExecutor(max_workers=workers) as ex:
                results = list(ex.map(lambda p, m=model: call(m, p), prompts))
        else:
            results = [call(model, p) for p in prompts]
        for req, r in zip(sample, results):
            calls.append({"category": req["category"], "hit": req["hit"], **r})
            if not r["ok"]:
                failed += 1
                continue
            spent = r["tokens_in"] + r["tokens_out"]
            out_sizes.append(r["tokens_out"])
            pure_total += spent               # pure generation pays for EVERY requirement
            if not req["hit"]:
                ours_total += spent           # our system pays only for corpus-gap misses
        ok_n = len(sample) - failed
        per_model[model] = {
            "calls": calls, "failed_calls": failed, "measured_requirements": ok_n,
            "real_tokens_pure_generation": pure_total,
            "real_tokens_our_system": ours_total,
            "real_savings_on_sample": round(1.0 - ours_total / pure_total, 4) if pure_total else None,
            "mean_generated_tokens_per_component": round(sum(out_sizes) / len(out_sizes), 1) if out_sizes else None,
        }
    return {"record_type": "real_generation_token_benchmark", "models": models,
            "sample": [{"category": r["category"], "hit": r["hit"]} for r in sample],
            "per_model": per_model, "num_predict_cap": _NUM_PREDICT,
            "note": "REAL prompt_eval_count/eval_count from the Ollama API (never estimated). OUR-system hits "
                    "cost 0 generation tokens (the measured deterministic retrieve+compose lane); misses pay "
                    "full generation (once fleet-wide under the flywheel). num_predict caps each call, so "
                    "real components may run LONGER — the savings ratio is conservative in ours' favor only "
                    "through the measured hit rate, never through generation size.", **BOUNDARY}


def _self_test() -> int:
    checks: list[tuple[str, bool]] = []
    sample = [{"category": "auth", "query": "login with google", "expected_tokens": ["oauth"], "hit": True},
              {"category": "billing", "query": "monthly charges", "expected_tokens": ["stripe"], "hit": True},
              {"category": "search", "query": "find my documents", "expected_tokens": ["fulltext"], "hit": False}]

    def _stub(model: str, prompt: str, **_kw: Any) -> dict[str, Any]:  # deterministic, no network
        return {"ok": True, "tokens_in": len(prompt) // 4, "tokens_out": 100 + len(model)}

    rec = measure_real(sample, ["stub-model-a", "stub-model-b"], transport=_stub)
    a = rec["per_model"]["stub-model-a"]
    per_call = [c["tokens_in"] + c["tokens_out"] for c in a["calls"]]
    checks.append(("pure generation pays for every requirement (real accounting, stub transport)",
                   a["real_tokens_pure_generation"] == sum(per_call)))
    checks.append(("our system pays ONLY for the corpus-gap miss",
                   a["real_tokens_our_system"] == per_call[2]
                   and a["real_tokens_our_system"] < a["real_tokens_pure_generation"]))
    checks.append(("the savings ratio and mean generated size are computed from the measured calls",
                   0.0 < a["real_savings_on_sample"] < 1.0
                   and a["mean_generated_tokens_per_component"] is not None))
    # a failing transport is RECORDED, never fabricated into the totals
    def _flaky(model: str, prompt: str, **_kw: Any) -> dict[str, Any]:
        return {"ok": False, "tokens_in": 0, "tokens_out": 0, "error": "unreachable"}
    frec = measure_real(sample, ["down-model"], transport=_flaky)
    checks.append(("transport failures are counted as failed_calls with zero fabricated tokens",
                   frec["per_model"]["down-model"]["failed_calls"] == 3
                   and frec["per_model"]["down-model"]["real_tokens_pure_generation"] == 0
                   and frec["per_model"]["down-model"]["real_savings_on_sample"] is None))
    checks.append(("the receipt is deterministic (byte-identical twice, stub transport)",
                   json.dumps(measure_real(sample, ["stub-model-a"], transport=_stub), sort_keys=True)
                   == json.dumps(measure_real(sample, ["stub-model-a"], transport=_stub), sort_keys=True)))
    checks.append(("receipt is candidate/serves_truth=false", rec["serves_truth"] is False))

    failed = [name for name, ok in checks if not ok]
    for name, ok in checks:
        print(f"  [{'ok' if ok else 'FAIL'}] {name}")
    if failed:
        print(f"\n{len(failed)} FAILURES: {failed}")
        return 1
    print("\nPASS - real_generation_token_bench: REAL Ollama token counts (prompt_eval_count/eval_count) "
          "compared across PURE-generation vs OUR-system lanes on a deterministic requirement sample — "
          "hits cost 0, only corpus-gap misses generate, failures recorded never fabricated, hermetic via "
          "an injected stub transport. serves_truth=false.")
    return 0


def _run(models_csv: str, n_hits: int, n_misses: int, workers: int = 1) -> int:
    suite = _saas.load_suite()
    receipt_path = resource("data") / "dev-intel" / "session_emulation" / "saas_requirements_receipt.json"
    if not suite or not receipt_path.exists():
        print("need the suite + a saas_requirements_receipt.json (run saas_requirements_bench --run first)")
        return 1
    uncovered = json.loads(receipt_path.read_text())["uncovered_requirements"]
    sample = sample_requirements(suite, uncovered, n_hits=n_hits, n_misses=n_misses)
    models = [m.strip() for m in models_csv.split(",") if m.strip()]
    print(f"REAL generations: {len(sample)} requirements x {len(models)} models "
          f"(num_predict cap {_NUM_PREDICT}, workers {workers}) ...")
    rec = measure_real(sample, models, workers=workers)
    out = resource("data") / "dev-intel" / "session_emulation" / "real_generation_token_receipt.json"
    out.write_text(json.dumps(rec, indent=2, sort_keys=True))
    slim = {m: {k: v for k, v in d.items() if k != "calls"} for m, d in rec["per_model"].items()}
    print(json.dumps(slim, indent=2, sort_keys=True))
    print(f"\nwritten: {out}")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--run", action="store_true", help="REAL generations via Ollama (local daemon or cloud)")
    ap.add_argument("--models", default=_DEFAULT_MODELS)
    ap.add_argument("--sample-hits", type=int, default=_SAMPLE_HITS)
    ap.add_argument("--sample-misses", type=int, default=_SAMPLE_MISSES)
    ap.add_argument("--workers", type=int, default=1, help="concurrent real calls (order preserved)")
    args = ap.parse_args(argv)
    if args.self_test:
        return _self_test()
    if args.run:
        return _run(args.models, args.sample_hits, args.sample_misses, args.workers)
    ap.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
