#!/usr/bin/env python3
"""scripts.run_primitive_generation_campaign — run a bounded, candidate-only primitive-generation CAMPAIGN over
real-world/esoteric technology-stack situations, drafting through the provider-agnostic router.

Flow (primitive_campaigns/esoteric_technology_stack_campaign.yaml is the default campaign):

    real_world_situation_primitive_specs.sample_specs   # deterministic coprime sample across the messy grid
      -> filter to the campaign families + D0/D1 no-side-effect determinism
      -> executor-enqueue ONLY specs with schema + promotable determinism (fixture-provable)
      -> spec_to_executor_synthesizer.run(chat_fn = llm_capability_router.call(draft_job_type))   # Hy3 primary
           + code fallback, quota-gated, ledgered)                                                 # + code fallback
      -> security gate -> SANDBOX-execute against fixtures -> determinism check -> promote candidate->validated
      -> candidate-only campaign report

The LLM PROPOSES (drafts a body + fixtures); the deterministic system DISPOSES (gate + sandbox + promotion).
Non-executor-ready specs are kept as candidate specs (lossless). Every row candidate=true, serves_truth=false.

    python3 scripts/run_primitive_generation_campaign.py --self-test              # offline, stub router lane
    python3 scripts/run_primitive_generation_campaign.py --run --max-jobs 10      # live, Hy3-drafted
    python3 scripts/run_primitive_generation_campaign.py --run --max-jobs 25 --start 25 --dry-run
"""
from __future__ import annotations

import sys
from pathlib import Path

_here_boot = Path(__file__).resolve()
_sbc_boot = next((q for q in _here_boot.parents if (q / "scripts" / "_repo_paths.py").exists()),
                 _here_boot.parents[1])
if str(_sbc_boot) not in sys.path:
    sys.path.insert(0, str(_sbc_boot))
from scripts._repo_paths import install as _install_code_roots, resource  # noqa: E402

_install_code_roots()

import argparse  # noqa: E402
import datetime as _dt  # noqa: E402
import json  # noqa: E402
from typing import Any, Callable, Optional  # noqa: E402

import yaml  # noqa: E402

from scripts import llm_capability_router as _router  # noqa: E402
from scripts import real_world_situation_primitive_specs as _specs  # noqa: E402
from scripts import spec_to_executor_synthesizer as _synth  # noqa: E402
from scripts.llm_quota_manager import BOUNDARY, QuotaManager  # noqa: E402

try:
    from src.teleon.experiments.ids import canonical_id  # noqa: E402
except Exception as exc:  # noqa: BLE001
    raise SystemExit(f"run_primitive_generation_campaign requires canonical_id; import failed: {exc}")

DEFAULT_CAMPAIGN_PATH = _sbc_boot / "primitive_campaigns" / "esoteric_technology_stack_campaign.yaml"
_DATA_SUBDIR = "data/dev-intel/primitive_generation_campaign"
_PROMOTABLE_DETERMINISM = frozenset({"D0_pure", "D1_seeded", "D2_bounded_external"})


def load_campaign(path: Optional[Path] = None) -> dict[str, Any]:
    return yaml.safe_load((path or DEFAULT_CAMPAIGN_PATH).read_text(encoding="utf-8"))


def _select_specs(campaign: dict[str, Any], max_jobs: int, start: int) -> list[dict[str, Any]]:
    """Sample the grid, then keep only campaign families + allowed (no-side-effect) determinism, up to max_jobs."""
    families = set(campaign.get("families", []))
    determ = set(campaign.get("determinism_allow", ["D0_pure", "D1_seeded"]))
    over = int(campaign.get("defaults", {}).get("oversample_factor", 8))
    pool_n = min(max(max_jobs * over + 32, max_jobs), _specs.grid_size())
    kept: list[dict[str, Any]] = []
    for s in _specs.sample_specs(pool_n, start=start):
        if s.get("family") in families and s.get("determinism_level") in determ:
            kept.append(s)
            if len(kept) >= max_jobs:
                break
    return kept


def executor_ready(spec: dict[str, Any], campaign: dict[str, Any]) -> bool:
    """The executor-enqueue gate: a spec may go to synthesis ONLY if it carries schema + promotable determinism
    (so the drafter can produce a fixture-provable executor). 'verifier+fixture ideas' are generated by the
    synthesizer FROM these; a spec missing a schema cannot be fixture-proven and is kept candidate-only."""
    reqs = set(campaign.get("executor_enqueue_requires", []))
    if "input_schema" in reqs and not spec.get("input_schema"):
        return False
    if "output_schema" in reqs and not spec.get("output_schema"):
        return False
    if "promotable_determinism" in reqs and spec.get("determinism_level") not in _PROMOTABLE_DETERMINISM:
        return False
    return True


def _router_synth_chat(campaign: dict[str, Any], qm: QuotaManager,
                       live_chat_fn: Optional[Callable[[dict, str, str], dict]],
                       dry_run: bool) -> Callable[[str, str], tuple[str, str]]:
    """Adapt llm_capability_router.call -> spec_to_executor_synthesizer's chat_fn(system, user) -> (text, lane).
    Drafting routes through the campaign's draft_job_type (Hy3 primary + code fallback), quota-gated + ledgered."""
    job_type = campaign.get("draft_job_type", "spec_generation")
    data_class = campaign.get("data_class", "public")
    campaign_id = campaign.get("campaign_id", "campaign")

    def chat(system: str, user: str) -> tuple[str, str]:
        res = _router.call(job_type, system, user, data_class=data_class, campaign=campaign_id,
                           quota=qm, chat_fn=live_chat_fn, dry_run=dry_run)
        if res.get("status") == "ok":
            return res.get("text") or "", res.get("lane") or "none"
        return "", res.get("status", "no_lane")

    return chat


def run_campaign(campaign: dict[str, Any], *, max_jobs: int, start: int,
                 live_chat_fn: Optional[Callable[[dict, str, str], dict]] = None,
                 quota: Optional[QuotaManager] = None, dry_run: bool = False,
                 synth_run: Optional[Callable[..., dict[str, Any]]] = None,
                 out_dir: Optional[Path] = None) -> dict[str, Any]:
    """One bounded campaign pass. Returns a candidate-only report. Deterministic given a fixed live_chat_fn."""
    campaign_id = campaign.get("campaign_id", "campaign")
    cost_cap = campaign.get("defaults", {}).get("campaign_cost_cap_usd")
    qm = quota or QuotaManager(campaign=campaign_id, dry_run=dry_run,
                               campaign_cost_cap=(cost_cap if cost_cap else None))
    out_dir = out_dir or resource(_DATA_SUBDIR)
    out_dir.mkdir(parents=True, exist_ok=True)

    kept = _select_specs(campaign, max_jobs, start)
    ready = [s for s in kept if executor_ready(s, campaign)]
    candidate_only = [s for s in kept if not executor_ready(s, campaign)]

    # persist the sampled candidate specs (lossless: even the non-enqueued ones are kept)
    specs_path = out_dir / f"{campaign_id}_candidate_specs.jsonl"
    with specs_path.open("a", encoding="utf-8") as fh:
        for s in kept:
            fh.write(json.dumps({**s, "campaign_id": campaign_id,
                                 "executor_enqueued": executor_ready(s, campaign)}, sort_keys=True) + "\n")

    synth_summary: dict[str, Any] = {"specs": 0, "note": "no executor-ready specs" if not ready else ""}
    if ready and not dry_run:
        chat = _router_synth_chat(campaign, qm, live_chat_fn, dry_run=False)
        run = synth_run or _synth.run
        synth_summary = run(ready, chat, out_path=out_dir / f"{campaign_id}_synthesis_receipts.jsonl")
    elif ready and dry_run:
        chat = _router_synth_chat(campaign, qm, live_chat_fn, dry_run=True)  # router dry-run per spec: estimate only
        for s in ready:
            chat(_synth._SYS, f"spec {s.get('name')}")  # noqa: SLF001 — reuse the drafter system prompt for the estimate
        synth_summary = {"specs": len(ready), "note": "dry_run — estimated only, nothing drafted/executed"}

    report = {
        "record_type": "primitive_generation_campaign_report", "campaign_id": campaign_id,
        "run_id": canonical_id("campaign_run", campaign_id, str(start), str(max_jobs)),
        "generated_at": _dt.datetime.now(_dt.timezone.utc).replace(microsecond=0).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "max_jobs": max_jobs, "start": start, "dry_run": dry_run,
        "sampled_kept": len(kept), "executor_enqueued": len(ready), "candidate_only_specs": len(candidate_only),
        "families": campaign.get("families"), "determinism_allow": campaign.get("determinism_allow"),
        "draft_job_type": campaign.get("draft_job_type"),
        "by_family": {f: sum(1 for s in kept if s.get("family") == f) for f in campaign.get("families", [])},
        "synthesis": {k: synth_summary.get(k) for k in ("specs", "promoted", "validated", "certified",
                                                        "candidate", "quarantined", "by_outcome", "note")
                      if k in synth_summary},
        "candidate_specs_path": str(specs_path), "usage_ledger_path": str(qm.ledger_path),
        **BOUNDARY,
    }
    (out_dir / f"{campaign_id}_report.json").write_text(json.dumps(report, indent=2, sort_keys=True))
    return report


# ── self-test (offline, deterministic, mutation-gated; NO network — a stub lane is injected into the router) ──
def _stub_live_chat() -> Callable[[dict, str, str], dict]:
    """A router-level live chat stub: returns a good, fixture-provable normalize_ws executor for ANY lane/spec
    (the synthesizer keys off draft['entry'], not the spec name), so the whole wire runs offline."""
    draft = {"python_body": "def normalize_ws(s):\n    return ' '.join(str(s).split())\n", "entry": "normalize_ws",
             "positive_fixtures": [{"input": {"s": "  a   b "}, "expected": "a b"},
                                   {"input": {"s": "x"}, "expected": "x"},
                                   {"input": {"s": "p\tq"}, "expected": "p q"}],
             "negative_fixtures": [{"input": {"s": "a b"}, "expected": "a b"}]}

    def chat(lane: dict[str, Any], system: str, user: str) -> dict[str, Any]:
        return {"text": json.dumps(draft), "usage": {"cost": 0.0}}

    return chat


def _self_test() -> int:
    import tempfile  # noqa: PLC0415
    checks: list[tuple[str, bool]] = []
    campaign = load_campaign()

    checks.append(("campaign defines D0/D1 families + a draft job type + an executor-enqueue gate",
                   set(campaign["families"]) and set(campaign["determinism_allow"]) <= {"D0_pure", "D1_seeded"}
                   and campaign.get("draft_job_type") in _router.JOB_LANES
                   and "input_schema" in campaign.get("executor_enqueue_requires", [])))

    # selection is bounded + filtered to families/determinism
    sel = _select_specs(campaign, 12, 0)
    checks.append(("selection is bounded by max_jobs and filtered to campaign families + no-side-effect determinism",
                   len(sel) <= 12 and all(s["family"] in set(campaign["families"]) for s in sel)
                   and all(s["determinism_level"] in {"D0_pure", "D1_seeded"} for s in sel)))

    # executor-enqueue gate: a spec missing input_schema is NOT enqueued
    ok_spec = dict(sel[0])
    no_schema = {**ok_spec, "input_schema": None}
    checks.append(("executor-enqueue gate: schema present -> enqueued; schema missing -> candidate-only",
                   executor_ready(ok_spec, campaign) and not executor_ready(no_schema, campaign)))

    with tempfile.TemporaryDirectory() as td:
        tp = Path(td)
        qm = QuotaManager(campaign="unit", kill_switch_path=tp / "NO_STOP", ledger_path=tp / "led.jsonl",
                          queue_path=tp / "q.jsonl")
        rep = run_campaign(campaign, max_jobs=4, start=0, live_chat_fn=_stub_live_chat(), quota=qm, out_dir=tp)
        checks.append(("campaign report is candidate-only + bounded + names the wire",
                       rep["serves_truth"] is False and rep["sampled_kept"] <= 4
                       and rep["draft_job_type"] == "spec_generation"
                       and rep["executor_enqueued"] == rep["executor_enqueued"]))
        # the wire actually reached the synthesizer and promoted at least one fixture-proven executor (offline)
        checks.append(("the router->synthesizer wire runs end-to-end and promotes a fixture-proven executor",
                       rep["executor_enqueued"] >= 1 and rep["synthesis"].get("promoted", 0) >= 1))
        # ledger written, redacted (no raw spec intent bodies leak a secret marker), candidate specs persisted
        led = (tp / "led.jsonl").read_text() if (tp / "led.jsonl").exists() else ""
        checks.append(("usage ledger recorded routed calls with prompt hashes (redacted)",
                       '"prompt_hash": "prompt-' in led and '"status": "ok"' in led))
        specs_file = tp / f"{campaign['campaign_id']}_candidate_specs.jsonl"
        rows = [json.loads(x) for x in specs_file.read_text().splitlines()] if specs_file.exists() else []
        checks.append(("all persisted candidate specs are serves_truth=false and carry the enqueue decision",
                       rows and all(r["serves_truth"] is False and "executor_enqueued" in r for r in rows)))

        # DRY RUN drafts/executes nothing but still plans + estimates
        qm2 = QuotaManager(campaign="unit2", kill_switch_path=tp / "NO_STOP", ledger_path=tp / "l2.jsonl",
                           queue_path=tp / "q2.jsonl")
        rep_dry = run_campaign(campaign, max_jobs=3, start=5, live_chat_fn=_stub_live_chat(), quota=qm2,
                               dry_run=True, out_dir=tp)
        checks.append(("dry-run plans + estimates without drafting/executing",
                       rep_dry["dry_run"] is True and "dry_run" in str(rep_dry["synthesis"].get("note", ""))))

    failed = [n for n, ok in checks if not ok]
    for n, ok in checks:
        print(f"  [{'ok' if ok else 'FAIL'}] {n}")
    if failed:
        print(f"\n{len(failed)} FAILURES: {failed}")
        return 1
    print("\nPASS - run_primitive_generation_campaign: bounded esoteric-tech-stack campaign; families+determinism "
          "filtered; executor-enqueue gated on schema+promotable-determinism; drafting routed Hy3-first with code "
          "fallback through llm_capability_router into spec_to_executor_synthesizer (security+sandbox+fixture "
          "gated); candidate-only report + redacted ledger. Offline, deterministic. serves_truth=false.")
    return 0


def main(argv: Optional[list[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--run", action="store_true", help="live campaign pass (Hy3-drafted via the router)")
    ap.add_argument("--campaign", default=None, help="path to a campaign YAML (default: esoteric tech stack)")
    ap.add_argument("--max-jobs", type=int, default=None, help="bound on specs this pass")
    ap.add_argument("--start", type=int, default=None, help="resumable grid offset")
    ap.add_argument("--dry-run", action="store_true", help="plan + estimate cost, never draft/execute")
    args = ap.parse_args(argv)

    if args.self_test:
        return _self_test()
    if args.run:
        campaign = load_campaign(Path(args.campaign) if args.campaign else None)
        defaults = campaign.get("defaults", {})
        max_jobs = args.max_jobs if args.max_jobs is not None else int(defaults.get("max_jobs", 25))
        start = args.start if args.start is not None else int(defaults.get("start", 0))
        draft_job = campaign.get("draft_job_type", "spec_generation")
        lane_order = [f"{ln['id']}:{ln['model']}" for ln in _router.route(draft_job, weights="off")]
        print(f"campaign '{campaign.get('campaign_id')}' | max_jobs={max_jobs} start={start} "
              f"dry_run={args.dry_run} | draft lane order: {lane_order}")
        rep = run_campaign(campaign, max_jobs=max_jobs, start=start, dry_run=args.dry_run)
        print(json.dumps({k: rep[k] for k in ("campaign_id", "sampled_kept", "executor_enqueued",
              "candidate_only_specs", "by_family", "synthesis", "candidate_specs_path")}, indent=2, sort_keys=True))
        return 0
    ap.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
