#!/usr/bin/env python3
"""build_portfolio_connection_map — render + prove the PORTFOLIO CONNECTION MAP: how the core products (Baltor, Teleon)
consume content from EVERY Open*Hub surface, with the Amazon strategy (internal infra -> public revenue) per hub.

Single-sourced: the hub/product names are cross-checked against the authoritative family source
(dist/sites/openharness-design/shared/products.js — the same file the surface-family check reads), so the map can
NEVER silently omit a surface. Renders docs/architecture/portfolio-connection-map.md with a Mermaid diagram + tables.
--self-test is the registered proof (coverage + counts + every hub connects to a core + Amazon stage + dependency law).
serves_truth=false.

  --build       render the markdown diagram
  --self-test   prove coverage/edges/strategy and that the render is deterministic
CLI: PYTHONPATH=. python3 scripts/build_portfolio_connection_map.py --build
"""
from __future__ import annotations

import json
import os
import re
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_MAP = os.path.join(_ROOT, "architecture", "portfolio_connection_map.json")
_PRODUCTS_JS = os.path.join(_ROOT, "dist", "sites", "openharness-design", "shared", "products.js")
_OUT = os.path.join(_ROOT, "docs", "architecture", "portfolio-connection-map.md")


def _authoritative_names() -> set:
    """The surface names products.js declares (the canonical source the family check uses): Baltor, Teleon, every Open*."""
    txt = open(_PRODUCTS_JS, encoding="utf-8").read()
    names = set(re.findall(r"name:\s*'((?:Open[A-Za-z]+|Baltor|Teleon))'", txt))
    return names


def _load() -> dict:
    return json.load(open(_MAP, encoding="utf-8"))


def _short(provides: str) -> str:
    """A Mermaid-safe short edge label (no parens/slashes/pipes)."""
    s = re.split(r"[(/|]", provides)[0].strip()
    return " ".join(s.split()[:4])


def _mermaid(m: dict) -> str:
    lines = ["flowchart LR", "  parent([AI Done Right]):::parent",
             "  baltor[Baltor]:::core", "  teleon[Teleon]:::core",
             "  parent --> baltor", "  parent --> teleon", "  baltor -. depends on .-> teleon"]
    for tier, label in (("live", "Live OpenHubForAI registries (9) — dual-use"), ("private_bench", "Private-bench OpenHubForAI registries (13) — internal-first")):
        lines.append(f"  subgraph {tier}[\"{label}\"]")
        for h in m["hubs"]:
            if h["tier"] == tier:
                lines.append(f"    {h['name']}")
        lines.append("  end")
    for h in m["hubs"]:
        targets = ["baltor", "teleon"] if h["consumed_by"] == "both" else [h["consumed_by"]]
        for t in targets:
            lines.append(f"  {h['name']} -->|{_short(h['provides'])}| {t}")
    lines += ["  classDef core fill:#1f6feb,color:#fff,stroke:#1f6feb;",
              "  classDef parent fill:#161b22,color:#fff,stroke:#58a6ff;"]
    return "\n".join(lines)


def render() -> str:
    m = _load()
    live = [h for h in m["hubs"] if h["tier"] == "live"]
    bench = [h for h in m["hubs"] if h["tier"] == "private_bench"]
    out = []
    out.append("# Portfolio connection map\n")
    out.append("> GENERATED by `scripts/build_portfolio_connection_map.py` from `architecture/portfolio_connection_map.json` "
               "(names cross-checked against `products.js`). Do not hand-edit.\n")
    out.append("**The spine:** help people use AI better — move each unit of work *unbounded & inefficient → "
               "most-bounded & most-efficient*, on context kept *true / current / provable*, defined by *capability*, "
               "getting *smarter over time*.\n")
    out.append(f"**Shape:** 2 core products (Baltor, Teleon) consume content from **{len(m['hubs'])} OpenHubForAI registries** "
               f"({len(live)} live + {len(bench)} private-bench).\n")
    out.append("**Amazon strategy:** " + m["amazon_strategy"]["principle"] + "\n")
    out.append("**Dependency law:** " + m["dependency_law"] + "\n")
    out.append("```mermaid\n" + _mermaid(m) + "\n```\n")
    for title, rows in (("Live OpenHubForAI registries (dual-use: open registry + internal infra)", live),
                        ("Private-bench OpenHubForAI registries (internal-first; public-revenue candidates)", bench)):
        out.append(f"\n## {title}\n")
        out.append("| Hub | Provides | Consumed by | Amazon stage |\n|---|---|---|---|")
        for h in rows:
            stage = m["amazon_strategy"]["stages"][h["tier"]]
            out.append(f"| {h['name']} | {h['provides']} | {h['consumed_by']} | {stage} |")
    return "\n".join(out) + "\n"


def build() -> str:
    os.makedirs(os.path.dirname(_OUT), exist_ok=True)
    txt = render()
    tmp = _OUT + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(txt)
    os.replace(tmp, _OUT)
    return _OUT


def _self_test() -> int:
    fails: list[str] = []

    def ck(name, ok, detail=""):
        print(f"  [{'ok' if ok else 'FAIL'}] {name}{(': ' + detail) if detail and not ok else ''}")
        if not ok:
            fails.append(name)

    m = _load()
    names = {h["name"] for h in m["hubs"]} | {c["name"] for c in m["core"]}
    auth = _authoritative_names()
    missing = sorted(auth - names)
    ck("EVERY surface products.js declares is in the map (no hub omitted)", not missing, f"missing {missing}")

    live = [h for h in m["hubs"] if h["tier"] == "live"]
    bench = [h for h in m["hubs"] if h["tier"] == "private_bench"]
    ck("9 live + 13 private-bench = 22 Open*Hubs (matches the computed family)",
       len(live) == 9 and len(bench) == 13 and len(m["hubs"]) == 22, f"{len(live)}+{len(bench)}")
    ck("every hub CONNECTS to a core product (consumed_by baltor|teleon|both)",
       all(h["consumed_by"] in ("baltor", "teleon", "both") for h in m["hubs"]))
    ck("both core products actually consume from the ecosystem",
       any(h["consumed_by"] in ("baltor", "both") for h in m["hubs"]) and any(h["consumed_by"] in ("teleon", "both") for h in m["hubs"]))
    ck("every hub has a 'provides' (a typed content flow, not a vague link)", all(h.get("provides") for h in m["hubs"]))
    ck("the Amazon strategy (internal infra -> public revenue) is defined for both tiers",
       set(m["amazon_strategy"]["stages"]) == {"live", "private_bench"} and "open_trigger" in m["amazon_strategy"])
    ck("the dependency law is hub->core (never reverse)",
       "never reverse" in m["dependency_law"].lower() and "consumes from hubs" in m["dependency_law"].lower())

    txt = render()
    ck("renders a Mermaid diagram + per-tier tables", "```mermaid" in txt and "Amazon stage" in txt and "flowchart" in txt)
    ck("every hub appears as a Mermaid node", all(h["name"] in txt for h in m["hubs"]))
    ck("render is deterministic", render() == txt)
    built = build()
    ck("writes the memorialized doc", os.path.exists(built) and open(built, encoding="utf-8").read() == txt)

    print("\n" + (f"PASS - build_portfolio_connection_map: all {len(m['hubs'])} Open*Hubs ({len(live)} live + {len(bench)} "
                  f"private-bench) mapped to the core products they feed (context packs / harnesses / model info / "
                  f"methods / receipts), with the Amazon internal-infra->public-revenue stage per hub; coverage "
                  f"cross-checked against products.js so nothing is omitted; Mermaid diagram rendered. serves_truth=false."
                  if not fails else f"{len(fails)} FAILURES: {fails}"))
    return 0 if not fails else 1


def _main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    if "--self-test" in argv:
        return _self_test()
    if "--build" in argv:
        print("built " + build())
        return 0
    print("usage: build_portfolio_connection_map.py --build | --self-test")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
