#!/usr/bin/env python3
"""scripts.check_fragile_context_atlas — PROOF: the Fragile Context Atlas (architecture/fragile_context_atlas.json)
is a governed registry of fragile-context packs that REUSES the repo's single sources of truth and stays honest about
what is runnable.

The atlas is the strategic wedge artifact: "companies are already feeding fragile context into RAG / chatbots / agent
memory / enterprise search / workflow agents; Baltor identifies the fragile surface, decomposes it, holds out the
unsafe/conflicting material, tracks freshness, and serves only what is supported." This proof keeps that artifact from
drifting into overclaim or duplicating existing contracts.

The validation logic lives in ONE reusable function, `find_violations(tax, atlas, refs)`, which returns a dict of
rule_code -> offending detail. This proof asserts the REAL files produce zero violations; the companion
scripts/check_fragile_context_atlas_redteam.py feeds the SAME validator deliberately-broken fixtures and asserts each
guardrail fires (positive proof here, negative proof there — one validator, no drift).

Rule codes (all must be empty for the real files):
  taxonomy:  tax_mode_count · tax_mode_fields · tax_time_mode · tax_domain_industry · tax_heldout_statuses
  per pack:  domain_unknown · mode_unknown · volatility_bad · heldout_status_bad · heldout_not_never_served ·
             no_source_authority · no_heldout · benchmark_authority · llm_authority · refresh_missing ·
             status_invalid · active_invalid · candidate_invalid
  atlas:     size_min · dup_pack_ids · dup_demo_priority · demo_bijection · candidate_missing · brand_named · oracle_language · secret_leak

Deterministic + offline. Exit 0/1.
"""
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

_REPO = Path(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

_TAXONOMY = _REPO / "architecture" / "fragile_context_taxonomy.json"
_ATLAS = _REPO / "architecture" / "fragile_context_atlas.json"
_DEMOS = _REPO / "web" / "baltor" / "guided-demos.html"
_INDUSTRIES = _REPO / "vocabularies" / "industries.yaml"
_FRAGILITY_SCHEMA = _REPO / "schemas" / "artifacts" / "FragilityMetadata.v1.schema.json"
_CANONICAL_FACT_SCHEMA = _REPO / "schemas" / "artifacts" / "CanonicalFact.v1.schema.json"

#: The 11 fragility failure modes are the canonical contract (single source = fragile_context_taxonomy.json); this count
#: is a drift guard so a mode can't be silently added/removed without intent. See the taxonomy file for the definitions.
CANONICAL_MODE_COUNT = 11
#: Minimum atlas breadth — the strategic doc calls for >= 15 seeded packs across domains.
MIN_PACKS = 15
#: Modes whose correctness decays over time and therefore MUST carry a refresh policy.
_TIME_MODES = {"TIME_FRAGILE", "FRESHNESS_FRAGILE"}

#: Vendor/brand tokens that must NOT appear anywhere in the atlas — it describes system TYPES, never names a company.
#: This structurally enforces docs/sales/public-claim-and-engagement-policy.md (no public, unauthorized claim about a
#: named system). Companies are research targets / category examples in prose, never entries in the governed registry.
_BRAND_TOKENS = [
    "Glean", "ServiceNow", "OpenEvidence", "Zendesk", "Intercom", "Forethought", "Decagon", "Kustomer",
    "Salesforce", "Atlassian", "Lucidworks", "Ironclad", "Spellbook", "LegalOn", "CoCounsel", "Abridge",
    "Ambience", "Doximity", "UpToDate", "Workday", "Harvey", "Coveo", "Algolia", "Sierra",
]
_BRAND_RE = re.compile(r"\b(" + "|".join(re.escape(t) for t in _BRAND_TOKENS) + r")\b", re.I)
_LEAK_RE = re.compile(r"sk-[A-Za-z0-9]{16,}|gsk_[A-Za-z0-9]{16,}|AIza[A-Za-z0-9]{16,}|secret://[^\s\"']+|Bearer\s+[A-Za-z0-9._-]{16,}")
#: A source AUTHORITY must be an actual source of record — never a benchmark/eval result (benchmark != promotion
#: authority) and never an unverified model/LLM output (LLM output is candidate, not truth). Scoped to source_authorities
#: ONLY — a held-out example MAY be model-derived (that is exactly what MODEL_FRAGILE captures).
_BENCHMARK_AUTH_RE = re.compile(r"benchmark|leaderboard|eval(uation)?\s+(result|score)|test\s+score", re.I)
_LLM_AUTH_RE = re.compile(r"\bLLM\b|model\s+output|model-generated|generated by .*model|\bGPT\b|\bClaude\b|chatbot answer", re.I)


def load_refs() -> dict:
    """External single sources the validator reuses (read once, passed into find_violations)."""
    return {
        "demo_keys": set(re.findall(r"\{\s*key:\s*'(\w+)'.*?status:\s*'(?:live|preview)'", _DEMOS.read_text(encoding="utf-8"), re.S)),
        "vol_enum": set(json.loads(_FRAGILITY_SCHEMA.read_text())["properties"]["volatility_class"]["enum"]),
        "fact_status_enum": set(json.loads(_CANONICAL_FACT_SCHEMA.read_text())["properties"]["status"]["enum"]),
        "industry_ids": set(re.findall(r"^  - id: (\w+)", _INDUSTRIES.read_text(encoding="utf-8"), re.M)),
    }


def find_violations(tax: dict, atlas: dict, refs: dict) -> dict[str, list]:
    """Return {rule_code: [offending detail, ...]} for a (taxonomy, atlas) pair. Empty lists everywhere == valid.
    The single source of validation truth for both the positive proof (real files) and the redteam (broken fixtures)."""
    v: dict[str, list] = {}

    def add(code: str, item) -> None:
        v.setdefault(code, []).append(item)

    modes = tax.get("fragility_modes", [])
    mode_ids = {m.get("id") for m in modes}
    domains = tax.get("domains", [])
    domain_ids = {d.get("id") for d in domains}
    held_out_statuses = set(tax.get("held_out_statuses", []))

    # ── taxonomy ──
    if len(modes) != CANONICAL_MODE_COUNT or len(mode_ids) != CANONICAL_MODE_COUNT:
        add("tax_mode_count", f"n={len(modes)} unique={len(mode_ids)} expected={CANONICAL_MODE_COUNT}")
    for m in modes:
        if not (m.get("id") and m.get("label") and m.get("definition")):
            add("tax_mode_fields", m.get("id"))
        if m.get("id") in _TIME_MODES and not (m.get("requires_refresh_policy") is True and m.get("carries") == "volatility_class"):
            add("tax_time_mode", m.get("id"))
    for d in domains:
        if d.get("industry") not in refs["industry_ids"]:
            add("tax_domain_industry", f"{d.get('id')}:{d.get('industry')}")
    if not held_out_statuses or not (held_out_statuses <= refs["fact_status_enum"]):
        add("tax_heldout_statuses", sorted(held_out_statuses - refs["fact_status_enum"]))

    # ── packs ──
    packs = atlas.get("packs", [])
    pack_ids = [p.get("pack_id") for p in packs]
    demo_priorities = [p.get("demo_priority") for p in packs]
    if len(packs) < MIN_PACKS:
        add("size_min", len(packs))
    if len(set(pack_ids)) != len(pack_ids):
        add("dup_pack_ids", [pid for pid in pack_ids if pack_ids.count(pid) > 1])
    if len(set(demo_priorities)) != len(demo_priorities):
        add("dup_demo_priority", [n for n in demo_priorities if demo_priorities.count(n) > 1])

    active, candidate = [], []
    for p in packs:
        pid = p.get("pack_id")
        status = p.get("status")
        smodes = set(p.get("fragility_modes") or [])
        auths = p.get("source_authorities") or []
        held = p.get("held_out_examples") or []

        if status not in {"active", "candidate"}:
            add("status_invalid", f"{pid}:{status}")
        if p.get("domain") not in domain_ids:
            add("domain_unknown", pid)
        if not smodes or not (smodes <= mode_ids):
            add("mode_unknown", pid)
        if p.get("volatility_class") not in refs["vol_enum"]:
            add("volatility_bad", pid)
        if not auths:
            add("no_source_authority", pid)
        if any(_BENCHMARK_AUTH_RE.search(str(a)) for a in auths):
            add("benchmark_authority", pid)
        if any(_LLM_AUTH_RE.search(str(a)) for a in auths):
            add("llm_authority", pid)
        if not held:
            add("no_heldout", pid)
        for h in held:
            if h.get("status") not in held_out_statuses:
                add("heldout_status_bad", pid)
            if h.get("never_served") is not True:
                add("heldout_not_never_served", pid)
        if _TIME_MODES & smodes:
            rp = p.get("refresh_policy") or {}
            if not rp.get("cadence") or not rp.get("trigger"):
                add("refresh_missing", pid)

        if status == "active":
            active.append(p)
            sa = p.get("served_answer")
            held_vals = {h.get("value") for h in held}
            if not p.get("demo_key") or not isinstance(sa, str) or not sa or sa in held_vals:
                add("active_invalid", pid)
        elif status == "candidate":
            candidate.append(p)
            if (p.get("demo_key") is not None or p.get("served_answer") is not None
                    or not p.get("served_answer_pattern")
                    or not all(h.get("illustrative") is True for h in held)):
                add("candidate_invalid", pid)

    # ── atlas-wide ──
    active_keys = {p.get("demo_key") for p in active}
    if active_keys != refs["demo_keys"] or len(active_keys) != len(active):
        add("demo_bijection", f"active={sorted(k for k in active_keys if k)} demos={sorted(refs['demo_keys'])}")
    if len(candidate) < 1:
        add("candidate_missing", len(candidate))

    blob = json.dumps(tax) + "\n" + json.dumps(atlas)
    for hit in sorted({m.group(0) for m in _BRAND_RE.finditer(blob)}):
        add("brand_named", hit)
    if re.search(r"\bOracle\b", blob):
        add("oracle_language", "Oracle")
    if _LEAK_RE.search(blob):
        add("secret_leak", "secret-value pattern")

    return v


def _self_test() -> int:
    fails: list[str] = []

    def check(n: str, ok: bool, d: str = "") -> None:
        print(f"  [{'ok' if ok else 'FAIL'}] {n}{(': ' + d) if d and not ok else ''}")
        if not ok:
            fails.append(n)

    tax = json.loads(_TAXONOMY.read_text(encoding="utf-8"))
    atlas = json.loads(_ATLAS.read_text(encoding="utf-8"))
    refs = load_refs()
    v = find_violations(tax, atlas, refs)

    def clean(*codes: str) -> bool:
        return all(not v.get(c) for c in codes)

    check("A: taxonomy — 11 canonical modes (fields ok), TIME/FRESHNESS carry volatility+refresh, domains map to real industries, held-out statuses reuse CanonicalFact.status",
          clean("tax_mode_count", "tax_mode_fields", "tax_time_mode", "tax_domain_industry", "tax_heldout_statuses"),
          json.dumps({k: v[k] for k in v if k.startswith("tax_")}))
    check("B: atlas >= MIN_PACKS packs, unique pack_ids, unique demo priorities",
          clean("size_min", "dup_pack_ids", "dup_demo_priority"))
    check("C: every pack.domain + fragility mode is in the taxonomy (lock-step)", clean("domain_unknown", "mode_unknown"),
          json.dumps({k: v.get(k) for k in ("domain_unknown", "mode_unknown") if v.get(k)}))
    check("D: reuse enums — volatility in FragilityMetadata; held-out status in CanonicalFact subset + never_served",
          clean("volatility_bad", "heldout_status_bad", "heldout_not_never_served"))
    check("D+: every pack has >=1 source_authority and >=1 held-out example", clean("no_source_authority", "no_heldout"),
          json.dumps({k: v.get(k) for k in ("no_source_authority", "no_heldout") if v.get(k)}))
    check("D+: source_authorities are real sources — never a benchmark result or LLM output (benchmark/LLM != authority)",
          clean("benchmark_authority", "llm_authority"))
    check("E: every TIME/FRESHNESS-fragile pack carries a refresh_policy (cadence + trigger)", clean("refresh_missing"),
          json.dumps(v.get("refresh_missing")))
    check("F: ACTIVE demo_keys are a bijection with the live guided demos (no orphans/overclaim) + >=1 candidate",
          clean("demo_bijection", "candidate_missing"), json.dumps(v.get("demo_bijection")))
    check("G: promotion boundary — status in {active,candidate}; active<=>demo+served(not held-out); candidate<=>no demo/served, illustrative-only",
          clean("status_invalid", "active_invalid", "candidate_invalid"),
          json.dumps({k: v.get(k) for k in ("status_invalid", "active_invalid", "candidate_invalid") if v.get(k)}))
    check("H: public-claim policy — no vendor named + no 'Oracle' product language", clean("brand_named", "oracle_language"),
          json.dumps(v.get("brand_named")))
    check("I: no secret-value pattern", clean("secret_leak"))

    total = sum(len(x) for x in v.values())
    packs = atlas.get("packs", [])
    n_active = sum(1 for p in packs if p.get("status") == "active")
    print("\n" + (f"PASS — check_fragile_context_atlas: {len(packs)} packs ({n_active} active bijective with the live "
                  f"guided demos, {len(packs) - n_active} candidate backlog) across {len({d['id'] for d in tax['domains']})} "
                  f"domains x {CANONICAL_MODE_COUNT} failure modes — 0 violations across all rules; modes/domains/volatility/"
                  "held-out reuse the existing single sources, source authorities are never a benchmark or LLM output, the "
                  "active set never overclaims a demo, and no vendor is named." if not fails
                  else f"{len(fails)} FAILURES (total {total} violations): {fails}"))
    return 0 if not fails else 1


if __name__ == "__main__":
    if "--self-test" in sys.argv:
        raise SystemExit(_self_test())
    print("usage: python3 scripts/check_fragile_context_atlas.py --self-test")
    raise SystemExit(0)
