#!/usr/bin/env python3
"""scripts.check_opencontext_fragile_atlas_page — PROOF: the OpenContextHub site surfaces the Fragile Context Atlas,
rendered FROM the registry (so it cannot drift), governed (reference-not-truth), and naming no vendor.

The page section is generated by scripts/portfolio_lib._fragile_atlas_section() out of architecture/
fragile_context_atlas.json + fragile_context_taxonomy.json — this proof asserts the RENDERED OpenContextHub page stays
lock-step with that registry, carries the audit CTA as a resolvable anchor, keeps the public-claim policy (no vendor
named), and that the built artifact on disk matches (no stale build).

Asserts:
  A. SECTION: render_site('opencontexthub') has a "Fragile context atlas" section (id="fragile"); the built file on
     disk (dist/sites/opencontexthub/index.html) carries it too (rebuilt, not stale).
  B. CTA + NO DEAD ANCHOR: cta_secondary is ("Run a Fragile Context Audit", "#fragile"); the page renders that button
     and a matching id="fragile" (the anchor resolves).
  C. LOCK-STEP COUNTS: the page states the domain count + failure-mode count computed from the registry.
  D. LOCK-STEP EXAMPLES: for the cfpb/sanctions/tariff ACTIVE packs, the page shows the exact served_answer AND held-out
     value from the atlas (so the surface mirrors the registry, not hand-typed copy).
  E. GOVERNANCE: the page says reference packs are candidates "not served truth", holds out contradictions
     ("never served"), and that "Baltor governs".
  F. PUBLIC-CLAIM POLICY: no vendor/company named anywhere on the page (reuses the atlas brand scanner) + no "Oracle".
  G. NO LEAK: no secret-value pattern on the page.

Deterministic + offline. Exit 0/1.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

_REPO = Path(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from scripts.portfolio_lib import SITES, dist_path, render_site
from scripts.check_fragile_context_atlas import _BRAND_RE, _LEAK_RE

_TAXONOMY = _REPO / "architecture" / "fragile_context_taxonomy.json"
_ATLAS = _REPO / "architecture" / "fragile_context_atlas.json"
_SAMPLE_KEYS = ("cfpb", "sanctions", "tariff")


def _self_test() -> int:
    fails: list[str] = []

    def check(n: str, ok: bool, d: str = "") -> None:
        print(f"  [{'ok' if ok else 'FAIL'}] {n}{(': ' + d) if d and not ok else ''}")
        if not ok:
            fails.append(n)

    page = render_site("opencontexthub")
    tax = json.loads(_TAXONOMY.read_text(encoding="utf-8"))
    atlas = json.loads(_ATLAS.read_text(encoding="utf-8"))
    n_domains = len({d["id"] for d in tax["domains"]})
    n_modes = len(tax["fragility_modes"])
    active = {p.get("demo_key"): p for p in atlas["packs"] if p.get("status") == "active"}

    # A. section present in render + in the built artifact on disk
    built = dist_path("opencontexthub")
    built_html = built.read_text(encoding="utf-8") if built.is_file() else ""
    check("A: 'Fragile context atlas' section (id=fragile) is rendered + present in the built dist file (not stale)",
          'id="fragile"' in page and "Fragile context atlas" in page
          and "Run a Fragile Context Audit" in built_html, f"built_exists={built.is_file()}")

    # B. CTA wired to a resolvable anchor
    sec = SITES["opencontexthub"]["cta_secondary"]
    check("B: cta_secondary is the audit CTA to #fragile + the anchor resolves (no dead link)",
          sec == ("Run a Fragile Context Audit", "#fragile") and 'href="#fragile"' in page and 'id="fragile"' in page,
          f"cta_secondary={sec}")

    # C. lock-step counts
    check("C: page states the registry's domain + failure-mode counts",
          f"maps {n_domains} domains across {n_modes} failure modes" in page,
          f"expected '{n_domains} domains across {n_modes} failure modes'")

    # D. lock-step examples — served + held-out come straight from the atlas
    missing = []
    for k in _SAMPLE_KEYS:
        p = active.get(k)
        if not p:
            missing.append(f"{k}:not-active")
            continue
        if p["served_answer"] not in page:
            missing.append(f"{k}:served")
        if p["held_out_examples"][0]["value"] not in page:
            missing.append(f"{k}:held")
    check("D: cfpb/sanctions/tariff served_answer + held-out value appear verbatim from the atlas (no hand-typed copy)",
          not missing, str(missing))

    # E. governance language
    check("E: reference packs are candidates 'not served truth', contradictions 'never served', and 'Baltor governs'",
          "not served truth" in page and "never served" in page and "Baltor governs" in page)

    # F. public-claim policy
    brands = sorted({m.group(0) for m in _BRAND_RE.finditer(page)})
    check("F: no vendor/company named on the page + no 'Oracle' product language", not brands and "Oracle" not in page,
          f"brands={brands}")

    # G. no secret leak
    check("G: no secret-value pattern on the page", not _LEAK_RE.search(page))

    print("\n" + ("PASS — check_opencontext_fragile_atlas_page: OpenContextHub surfaces the Fragile Context Atlas rendered "
                  f"from the registry ({n_domains} domains x {n_modes} modes), with the cfpb/sanctions/tariff served+held "
                  "examples verbatim from the atlas, the 'Run a Fragile Context Audit' CTA resolving to the section, "
                  "reference-not-truth governance language, and no vendor named — built artifact matches." if not fails
                  else f"{len(fails)} FAILURES: {fails}"))
    return 0 if not fails else 1


if __name__ == "__main__":
    if "--self-test" in sys.argv:
        raise SystemExit(_self_test())
    print("usage: python3 scripts/check_opencontext_fragile_atlas_page.py --self-test")
    raise SystemExit(0)
