#!/usr/bin/env python3
"""scripts.port_full_design_to_web — deterministic transplant of the FULL-DESIGN bundle into the
three wired product front-ends, per the design contract (transplant, don't translate).

Source (the spec, final fidelity):   dist/sites/openharness-design/
Targets (the wired apps):            web/context-is-everything/ · web/baltor/ · web/harness-hub/

What it does, per app:
  * kit/   — every `shared/<file>` the app's pages load is copied BYTE-VERBATIM
             (DESIGN-CONTRACT Rule 0; the --check mode diffs them against the bundle).
  * site code (jsx/js/css) — copied verbatim EXCEPT the explicitly recorded live-data seam
    patches below (PATCHES), which swap fixture data for real backend data with an honest
    fallback. A patch that no longer matches FAILS LOUDLY (the bundle moved → re-record).
  * HTML pages — copied with exactly three mechanical rewrites (everything else verbatim):
      1. `../shared/…` asset paths → `kit/…` (each app stays independently shippable);
      2. pinned unpkg React/Babel `<script>` tags → the local `/vendor/…` runtime;
      3. a same-origin service-seam config script is injected so the kit's identity /
         registry / analytics clients hit this origin (scripts/showcase/server.py proxies).
    Cross-surface `../<sibling>/…` links are NOT rewritten — the showcase server mounts the
    bundle's top-level folders at the origin root, so the verbatim links resolve.
  * the entry prototype HTML becomes index.html; a pre-existing, non-generated index.html is
    preserved as legacy.html (lossless — the old front-end stays reachable, never deleted).
  * a manifest (.design-port-manifest.json) records every generated file for --check.

Modes:
  (no args)     port the bundle into web/ (idempotent)
  --check       regenerate in memory and diff against web/ — exit 1 on ANY drift
  --self-test   port into a temp dir and assert the invariants

Offline, stdlib-only.
"""
from __future__ import annotations

import json
import re
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BUNDLE = REPO / "dist" / "sites" / "openharness-design"
WEB = REPO / "web"

GENERATED_MARK = "GENERATED by scripts/port_full_design_to_web.py"
_MARKER = (
    f"<!-- {GENERATED_MARK} from dist/sites/openharness-design/{{src}} — transplanted design "
    "(DESIGN-CONTRACT): do not hand-edit; edit the bundle or the port script and re-run. -->"
)

# Same-origin service seams — the kit clients' deploy overrides (kit/oh-identity.js,
# kit/oh-registry.js) pointed at the showcase server's proxies, so auth/registry/analytics
# work on 127.0.0.1 AND through a tunnel. Ports live in the architecture registries only.
_SEAM_SCRIPT = (
    "<script>/* same-origin service seams → scripts/showcase/server.py proxies "
    "(identity/registry/analytics ports live in architecture/) */\n"
    "window.OHH_IDENTITY_BASE = '';\n"
    "window.OHH_REGISTRY_BASE = '/registry';\n"
    "window.OHH_EVENTS_BASE = '/analytics';\n"
    "</script>"
)

# Pinned CDN runtime → the local vendored copy (web/vendor/README.md records the pins).
_VENDOR_REWRITES = [
    (re.compile(r'<script src="https://unpkg\.com/react@[\d.]+/umd/react\.development\.js"[^>]*></script>'),
     '<script src="/vendor/react.development.js"></script>'),
    (re.compile(r'<script src="https://unpkg\.com/react-dom@[\d.]+/umd/react-dom\.development\.js"[^>]*></script>'),
     '<script src="/vendor/react-dom.development.js"></script>'),
    (re.compile(r'<script src="https://unpkg\.com/@babel/standalone@[\d.]+/babel\.min\.js"[^>]*></script>'),
     '<script src="/vendor/babel.min.js"></script>'),
]

_SHARED_REF = re.compile(r"\.\./shared/([A-Za-z0-9._-]+)")

# Recorded live-data seam patches (the ONLY divergence from verbatim site code).
# Shape: app → file → list of (old, new). Old strings must match EXACTLY once.
PATCHES: dict[str, dict[str, list[tuple[str, str]]]] = {
    "harness-hub": {
        "proto-main.jsx": [
            # the app shell's /flow and /run breadcrumbs carry the LIVE flow name when one exists
            (
                "    else if (route === '/flow') { page = <PFlow />; crumb = 'flow/csddd-grade'; bare = true; }",
                "    else if (route === '/flow') { page = <PFlow />; crumb = (window.OHHLive && OHHLive.flowName()) || 'flow/csddd-grade'; bare = true; }",
            ),
            (
                "    else if (route === '/run') { page = <PRun />; crumb = ['flow/csddd-grade', 'Run']; }",
                "    else if (route === '/run') { page = <PRun />; crumb = [(window.OHHLive && OHHLive.flowName()) || 'flow/csddd-grade', 'Run']; }",
            ),
            # A REAL realm session (sign-in/sign-up through the identity seam) puts the app into
            # signed-in mode. The bridge only REFLECTS real state — it never fabricates a session,
            # and the prototype's own ohp-auth demo flag keeps working unchanged.
            (
                "  const setLoggedIn = (v) => { setLoggedInRaw(v); try { localStorage.setItem('ohp-auth', v ? '1' : '0'); } catch (e) {} };\n"
                "  const store = React.useMemo(() => ({ task, setTask, toast, loggedIn, setLoggedIn }), [task, toast, loggedIn]);",
                "  const setLoggedIn = (v) => { setLoggedInRaw(v); try { localStorage.setItem('ohp-auth', v ? '1' : '0'); } catch (e) {} };\n"
                "  React.useEffect(() => {  // live seam: real realm session ⇒ app mode (reflects real state only)\n"
                "    const sync = () => {\n"
                "      try {\n"
                "        const s = window.OHIdentity && OHIdentity.session(OHIdentity.realmOf(OHH_BRAND));\n"
                "        if (s && s.session_id) setLoggedIn(true);\n"
                "      } catch (e) {}\n"
                "    };\n"
                "    sync();\n"
                "    window.addEventListener('hashchange', sync);\n"
                "    return () => window.removeEventListener('hashchange', sync);\n"
                "  }, []);\n"
                "  const store = React.useMemo(() => ({ task, setTask, toast, loggedIn, setLoggedIn }), [task, toast, loggedIn]);",
            ),
        ],
        "proto-catalog.jsx": [
            # Browse re-renders when the REAL catalog (2,400+ components via /api/components)
            # hydrates the design's COMPONENTS/BY_SLUG globals (web/harness-hub/ohh-live.js).
            (
                "  const isP = kind === 'pipeline';",
                "  const [, liveTick] = React.useState(0);  // live seam: re-render when the real catalog hydrates\n"
                "  React.useEffect(() => (window.OHHLive && OHHLive.onCatalog ? OHHLive.onCatalog(() => liveTick((t) => t + 1)) : undefined), []);\n"
                "  const isP = kind === 'pipeline';",
            ),
            (
                "  const c = BY_SLUG[slug];\n  if (!c) return <PNotFound />;",
                "  const [, liveTick] = React.useState(0);  // live seam: BY_SLUG hydrates from the real catalog\n"
                "  React.useEffect(() => (window.OHHLive && OHHLive.onCatalog ? OHHLive.onCatalog(() => liveTick((t) => t + 1)) : undefined), []);\n"
                "  const c = BY_SLUG[slug];\n  if (!c) return <PNotFound />;",
            ),
            # Honesty on live data: a pipeline with NO measured lift never shows a fabricated
            # lift bar (the fixture default was `c.lift || 0.4`) — it gets the unproven state.
            (
                "          {c.kind === 'pipeline' ? <>\n"
                "            <div className=\"oh-cc-id mono\" style={{ marginBottom: 10 }}>capability lift</div>\n"
                "            <div className=\"oh-lb-row\"><div className=\"oh-lb-label\">bare model <b>0.42</b></div><div className=\"oh-lb-track\"><div className=\"oh-lb-fill bare\" style={{ width: '42%' }} /></div></div>\n"
                "            <div className=\"oh-lb-row\"><div className=\"oh-lb-label\">this pipeline <b>{(0.42 + (c.lift || 0.4)).toFixed(2)}</b></div><div className=\"oh-lb-track\"><div className=\"oh-lb-fill pipe\" style={{ width: `${(0.42 + (c.lift || 0.4)) * 100}%` }} /></div></div>\n"
                "            <div className=\"oh-lift-delta\"><span className=\"big\" style={{ fontSize: 24 }}>▲ +{(c.lift || 0.4).toFixed(2)}</span></div>\n"
                "          </> : <>",
                "          {c.kind === 'pipeline' && typeof c.lift !== 'number' ? <>\n"
                "            <div className=\"oh-cc-id mono\" style={{ marginBottom: 10 }}>capability lift</div>\n"
                "            <span className=\"oh-badge oh-badge--muted\">— unproven</span>\n"
                "            <p className=\"pt-muted\" style={{ fontSize: 13, lineHeight: 1.55, marginTop: 10 }}>Not yet measured — lift lands when the eval harness runs this pipeline against its benchmark. No number is shown until it is real.</p>\n"
                "          </> : c.kind === 'pipeline' ? <>\n"
                "            <div className=\"oh-cc-id mono\" style={{ marginBottom: 10 }}>capability lift</div>\n"
                "            <div className=\"oh-lb-row\"><div className=\"oh-lb-label\">bare model <b>0.42</b></div><div className=\"oh-lb-track\"><div className=\"oh-lb-fill bare\" style={{ width: '42%' }} /></div></div>\n"
                "            <div className=\"oh-lb-row\"><div className=\"oh-lb-label\">this pipeline <b>{(0.42 + (c.lift || 0.4)).toFixed(2)}</b></div><div className=\"oh-lb-track\"><div className=\"oh-lb-fill pipe\" style={{ width: `${(0.42 + (c.lift || 0.4)) * 100}%` }} /></div></div>\n"
                "            <div className=\"oh-lift-delta\"><span className=\"big\" style={{ fontSize: 24 }}>▲ +{(c.lift || 0.4).toFixed(2)}</span></div>\n"
                "          </> : <>",
            ),
            # Real provenance fields when the catalog records them; fixture exemplars otherwise.
            (
                "<div>source · <span className=\"mono\" style={{ color: 'var(--fg)' }}>{c.industry === 'ESG' ? 'eur-lex.europa.eu' : 'registry-verified'}</span></div>",
                "<div>source · <span className=\"mono\" style={{ color: 'var(--fg)' }}>{c.src || (c.industry === 'ESG' ? 'eur-lex.europa.eu' : 'registry-verified')}</span></div>",
            ),
            (
                "<div>last-verified · <span className=\"mono\" style={{ color: 'var(--fg)' }}>2026-05-21</span></div>",
                "<div>last-verified · <span className=\"mono\" style={{ color: 'var(--fg)' }}>{c.verifiedDate || '2026-05-21'}</span></div>",
            ),
            (
                "<span className=\"oh-badge mono\">{COST_LABEL[c.cost] || c.cost}</span>",
                "<span className=\"oh-badge mono\">{COST_LABEL[c.cost] || c.cost || '—'}</span>",
            ),
            # workspace "recent flows" = the browser's REAL build history when it exists
            (
                "  const flows = [\n"
                "    ['CSDDD supplier grading', 'flow/csddd-grade', '▲ +0.41', '6 comp · $$'],\n"
                "    ['Contract renewal-risk review', 'flow/renewal-risk', '▲ +0.33', '5 comp · $$'],\n"
                "  ];",
                "  const flows = (window.OHHLive && OHHLive.recentFlows()) || [\n"
                "    ['CSDDD supplier grading', 'flow/csddd-grade', '▲ +0.41', '6 comp · $$'],\n"
                "    ['Contract renewal-risk review', 'flow/renewal-risk', '▲ +0.33', '5 comp · $$'],\n"
                "  ];",
            ),
        ],
        "proto-pages-build.jsx": [
            # PPreview kicks the REAL /api/build (web/harness-hub/ohh-live.js) and re-renders
            # when it lands. Honest fallback: backend silent → the designed exemplar stays.
            (
                "  const done = step >= 4;\n"
                "  const STEPS = ['Parsing the task', 'Retrieving vetted components', 'Assembling the flow', 'Costing & measuring lift'];",
                "  const done = step >= 4;\n"
                "  const [, liveTick] = React.useState(0);  // live seam: re-render when the real build lands\n"
                "  React.useEffect(() => { if (window.OHHLive) OHHLive.build(task).then(() => liveTick((t) => t + 1)); }, []);\n"
                "  const STEPS = ['Parsing the task', 'Retrieving vetted components', 'Assembling the flow', 'Costing & measuring lift'];",
            ),
            (
                "  const total = PHASES.reduce((n, p) => n + p.steps.length, 0);",
                "  const LIVEPV = window.OHHLive ? OHHLive.phases() : null;  // real assembled components when the backend answered\n"
                "  const PHASES_SRC = LIVEPV || PHASES;\n"
                "  const total = PHASES_SRC.reduce((n, p) => n + p.steps.length, 0);",
            ),
            (
                "                {PHASES.map((ph, pi) => (",
                "                {PHASES_SRC.map((ph, pi) => (",
            ),
            (
                '<div className="row"><span className="k">Est. cost / run</span><span className="v">$0.01–0.10</span></div>',
                '<div className="row"><span className="k">Est. cost / run</span><span className="v">{(LIVEPV && OHHLive.costRange()) || \'$0.01–0.10\'}</span></div>',
            ),
            # Live builds never claim a fixture lift number (the wired app's established
            # honesty rule — lift figures belong to the designed sample only).
            (
                '<div className="row"><span className="k">Measured lift</span><span className="v lift">▲ +0.33</span></div>',
                '{!LIVEPV && <div className="row"><span className="k">Measured lift</span><span className="v lift">▲ +0.33</span></div>}',
            ),
            (
                '<div className="row"><span className="k">Assembly</span><span className="v">model-built</span></div>',
                '<div className="row"><span className="k">Assembly</span><span className="v">{(LIVEPV && OHHLive.assembly()) || \'model-built\'}</span></div>',
            ),
            # /results — the three tier cards become the REAL cost tiers (cheap/balanced/quality)
            # when a live build exists; live cards carry lift:null → the unproven badge renders.
            (
                "        {TIERS.map((t) => (",
                "        {((window.OHHLive && OHHLive.tiers()) || TIERS).map((t) => (",
            ),
            (
                '            <div className="oh-result-lift"><span className="big">▲ {t.lift}</span><span className="sub">capability lift vs a bare model</span></div>',
                '            <div className="oh-result-lift">{t.lift ? <span className="big">▲ {t.lift}</span> : <span className="oh-badge oh-badge--muted">— unproven</span>}<span className="sub">capability lift vs a bare model</span></div>',
            ),
            # /flow — the canvas renders the REAL build poured into the designed slots; the
            # fixture lift badge and name appear only in design mode.
            (
                "  const N = Object.fromEntries(PFLOW.nodes.map((n) => [n.id, n]));",
                "  const FLOWSRC = (window.OHHLive && OHHLive.flowSlots()) || PFLOW;  // live seam: the REAL build in the designed canvas\n"
                "  const N = Object.fromEntries(FLOWSRC.nodes.map((n) => [n.id, n]));",
            ),
            (
                "  const op = PFLOW.op, opL = { x: op.x, y: op.y + op.h / 2 }, opR = { x: op.x + op.w, y: op.y + op.h / 2 };",
                "  const op = FLOWSRC.op, opL = { x: op.x, y: op.y + op.h / 2 }, opR = { x: op.x + op.w, y: op.y + op.h / 2 };",
            ),
            (
                "            {PFLOW.nodes.map((n) => {",
                "            {FLOWSRC.nodes.map((n) => {",
            ),
            (
                '        <span className="pt-crumb"><b>flow/csddd-grade</b><span className="oh-badge oh-badge--lift" style={{ marginLeft: 6 }}>▲ +0.41</span></span>',
                '        <span className="pt-crumb"><b>{(window.OHHLive && OHHLive.flowName()) || \'flow/csddd-grade\'}</b>{!(window.OHHLive && OHHLive.flow()) && <span className="oh-badge oh-badge--lift" style={{ marginLeft: 6 }}>▲ +0.41</span>}</span>',
            ),
            (
                '            <div className="oh-fop" style={{ left: op.x, top: op.y, width: op.w, height: op.h }}>◇ OR</div>',
                '            <div className="oh-fop" style={{ left: op.x, top: op.y, width: op.w, height: op.h }}>◇ {FLOWSRC.opLabel || \'OR\'}</div>',
            ),
            # the drawer's swap list: REAL alternatives (the build's dropped candidates of the
            # same primitive kind) when live; the designed exemplar list otherwise.
            (
                "              {ALTS[sel] && <>",
                "              {(() => { const __alts = (window.OHHLive && OHHLive.flow()) ? OHHLive.alts(sel, selNode) : ALTS[sel]; return __alts && <>",
            ),
            (
                "                {ALTS[sel].map((a) => (",
                "                {__alts.map((a) => (",
            ),
            (
                "              </>}\n            </div>\n          </aside>",
                "              </>; })()}\n            </div>\n          </aside>",
            ),
            (
                "        <button className=\"oh-btn oh-btn--ghost oh-btn--sm\" onClick={() => toast('Flow saved · flow/csddd-grade')}>Save</button>",
                "        <button className=\"oh-btn oh-btn--ghost oh-btn--sm\" onClick={() => toast('Flow saved · ' + ((window.OHHLive && OHHLive.flowName()) || 'flow/csddd-grade'))}>Save</button>",
            ),
            # Deploy exports the REAL open-spec YAML bundle (/api/export) when a live build exists.
            (
                "        <button className=\"oh-btn oh-btn--primary oh-btn--sm\" onClick={() => toast('Deploy bundle generated')}>Deploy</button>",
                "        <button className=\"oh-btn oh-btn--primary oh-btn--sm\" onClick={() => { if (window.OHHLive && OHHLive.flow() && OHHLive.exportYaml()) { toast('Deploy bundle exported · open-spec YAML'); } else { toast('Deploy bundle generated'); } }}>Deploy</button>",
            ),
            # the logged-out preview CTA goes through REAL sign-up — never a faked session flag
            (
                "<button className=\"oh-btn oh-btn--primary\" onClick={() => { setLoggedIn(true); navigate('/onboarding'); }}>Sign up free →</button>",
                "<button className=\"oh-btn oh-btn--primary\" onClick={() => navigate('/signup')}>Sign up free →</button>",
            ),
        ],
    },
}

# Hand-authored (NOT generated) seam files an app's index.html must load.
EXTRA_ENTRY_SCRIPTS = {"harness-hub": ["ohh-live.js"]}

APPS: dict[str, dict] = {
    "context-is-everything": {
        "folder": "context-is-everything",
        "entry": "Context is Everything.html",
        "code": ["cie-main.jsx", "cie.css"],
        "html": ["Demo Control Tower.html"],
    },
    "baltor": {
        "folder": "context-enrichment",
        "entry": "Context Enrichment Prototype.html",
        "code": [
            "ce-store.jsx", "ce-shell.jsx", "ce-landing.jsx", "ce-docs.jsx", "ce-app.jsx",
            "ce-engine.jsx", "ce-pipeline.jsx", "ce-main.jsx", "ce.css",
            "engine-stagenav.css", "engine-stagenav.js", "guided-demo.css", "guided-demo.js",
            "track.js",
        ],
        "html": "*.html",  # every Baltor guided demo / deep dive / coverage page
        # the entry's prototype filename is gone (it became index.html) — keep logo links working
        "self_link_rewrites": [("Context Enrichment Prototype.html", "index.html")],
    },
    "harness-hub": {
        "folder": "openharnesshub",
        "entry": "OpenHarnessHub Prototype.html",
        "code": [
            "oh-artifacts.jsx", "proto-store.jsx", "proto-pages-build.jsx", "proto-catalog.jsx",
            "proto-deep.jsx", "proto-byo.jsx", "proto-admin.jsx", "proto-sdg.jsx",
            "proto-value.jsx", "proto-ops.jsx", "proto-wide.jsx", "proto-pub.jsx",
            "proto-landings.jsx", "proto-main.jsx",
            "proto.css", "proto-deep.css", "proto-byo.css", "proto-admin.css", "proto-sdg.css",
            "proto-value.css", "proto-ops.css", "proto-wide.css",
        ],
        "html": [],
    },
}


def _rewrite_html(text: str, src_rel: str, app: str, is_entry: bool, cfg: dict) -> str:
    """The three mechanical rewrites + marker. Everything else stays verbatim."""
    for pattern, repl in _VENDOR_REWRITES:
        text = pattern.sub(repl, text)
    text = text.replace("../shared/", "kit/")
    for old, new in cfg.get("self_link_rewrites", []):
        if not is_entry:
            text = text.replace(f'href="{old}"', f'href="{new}"')
    # seam config before the first script so the kit clients see the overrides at load
    first_script = text.find("<script")
    if first_script != -1:
        text = text[:first_script] + _SEAM_SCRIPT + "\n" + text[first_script:]
    if is_entry:
        for extra in EXTRA_ENTRY_SCRIPTS.get(app, []):
            anchor = '<script src="kit/oh-experiments.js"></script>'
            if anchor not in text:
                raise SystemExit(f"FATAL: {src_rel}: anchor for extra script {extra!r} not found")
            text = text.replace(anchor, anchor + f'\n<script src="{extra}"></script>', 1)
    marker = _MARKER.format(src=src_rel)
    if "<!doctype html>" in text:
        text = text.replace("<!doctype html>", "<!doctype html>\n" + marker, 1)
    else:
        text = marker + "\n" + text
    return text


def _apply_patches(text: str, app: str, name: str) -> str:
    for old, new in PATCHES.get(app, {}).get(name, []):
        if text.count(old) != 1:
            raise SystemExit(
                f"FATAL: recorded patch no longer matches exactly once in {app}/{name} "
                f"(found {text.count(old)}). The bundle moved — re-record the patch.\n--- old:\n{old}"
            )
        text = text.replace(old, new)
    return text


def generate(app: str) -> dict[str, str]:
    """All generated files for one app as {relative_path: content} (no disk writes)."""
    cfg = APPS[app]
    src_dir = BUNDLE / cfg["folder"]
    out: dict[str, str] = {}

    html_names = (sorted(p.name for p in src_dir.glob(cfg["html"])) if isinstance(cfg["html"], str)
                  else list(cfg["html"]))
    if cfg["entry"] in html_names:
        html_names.remove(cfg["entry"])

    shared_refs: set[str] = set()
    for name, is_entry in [(cfg["entry"], True)] + [(n, False) for n in html_names]:
        raw = (src_dir / name).read_text(encoding="utf-8")
        shared_refs.update(_SHARED_REF.findall(raw))
        rel_out = "index.html" if is_entry else name
        out[rel_out] = _rewrite_html(raw, f"{cfg['folder']}/{name}", app, is_entry, cfg)

    for name in cfg["code"]:
        out[name] = _apply_patches((src_dir / name).read_text(encoding="utf-8"), app, name)

    for name in sorted(shared_refs):
        out[f"kit/{name}"] = (BUNDLE / "shared" / name).read_text(encoding="utf-8")

    out[".design-port-manifest.json"] = json.dumps({
        "tool": "scripts/port_full_design_to_web.py",
        "source": f"dist/sites/openharness-design/{cfg['folder']}",
        "entry": cfg["entry"],
        "generated": sorted(k for k in out if k != ".design-port-manifest.json"),
    }, indent=1) + "\n"
    return out


def port() -> int:
    for app in APPS:
        target = WEB / app
        target.mkdir(parents=True, exist_ok=True)
        files = generate(app)
        # lossless: a pre-existing hand-built front page is preserved, never overwritten away
        index = target / "index.html"
        if index.exists() and GENERATED_MARK not in index.read_text(encoding="utf-8", errors="replace"):
            legacy = target / "legacy.html"
            if not legacy.exists():
                index.rename(legacy)
                print(f"  [lossless] {app}: previous index.html preserved as legacy.html")
        for rel, content in files.items():
            dest = target / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content, encoding="utf-8")
        kit = sum(1 for k in files if k.startswith("kit/"))
        print(f"  [ported] {app}: {len(files)} files ({kit} kit, "
              f"{sum(1 for k in files if k.endswith('.html'))} html) ← {APPS[app]['folder']}/")
    print("PASS — full-design bundle ported into web/ (run --check anytime; see web/README.md)")
    return 0


def check() -> int:
    drift: list[str] = []
    for app in APPS:
        target = WEB / app
        for rel, content in generate(app).items():
            disk = target / rel
            if not disk.exists():
                drift.append(f"{app}/{rel}: MISSING (re-run the port script)")
            elif disk.read_text(encoding="utf-8") != content:
                drift.append(f"{app}/{rel}: DRIFTED from the generated transplant")
    if drift:
        print("FAIL — web/ full-design files drifted from dist/sites/openharness-design:")
        for d in drift:
            print("  ", d)
        print("Fix: edit the BUNDLE (or the port script) and re-run "
              "`python3 scripts/port_full_design_to_web.py` — never hand-edit generated copies.")
        return 1
    print("PASS — check_port_full_design_to_web: every generated web/ file matches the bundle "
          f"transplant byte-for-byte ({sum(len(generate(a)) for a in APPS)} files across {len(APPS)} apps).")
    return 0


def self_test() -> int:
    fails: list[str] = []

    def ck(name: str, ok: bool) -> None:
        print(f"  [{'ok' if ok else 'FAIL'}] {name}")
        if not ok:
            fails.append(name)

    with tempfile.TemporaryDirectory() as tmp:
        global WEB
        real_web, WEB = WEB, Path(tmp)
        try:
            port()
            for app, cfg in APPS.items():
                files = {p.relative_to(WEB / app).as_posix(): p for p in (WEB / app).rglob("*") if p.is_file()}
                entry = files["index.html"].read_text(encoding="utf-8")
                ck(f"{app}: entry generated + marked", GENERATED_MARK in entry)
                ck(f"{app}: no ../shared/ left in entry", "../shared/" not in entry)
                ck(f"{app}: vendored runtime (no unpkg)", "unpkg.com" not in entry)
                ck(f"{app}: service seams injected", "OHH_IDENTITY_BASE" in entry and "/registry" in entry)
                kit_ok = all((BUNDLE / "shared" / Path(rel).name).read_text(encoding="utf-8")
                             == p.read_text(encoding="utf-8")
                             for rel, p in files.items() if rel.startswith("kit/"))
                ck(f"{app}: kit byte-identical to bundle shared/", kit_ok)
                for name in cfg["code"]:
                    if name not in PATCHES.get(app, {}):
                        ck_ok = files[name].read_text(encoding="utf-8") == (
                            BUNDLE / cfg["folder"] / name).read_text(encoding="utf-8")
                        if not ck_ok:
                            ck(f"{app}: {name} verbatim", False)
            ck("harness-hub: live seam patches applied",
               "OHHLive.build(task)" in (WEB / "harness-hub" / "proto-pages-build.jsx").read_text(encoding="utf-8"))
            ck("harness-hub: ohh-live.js wired into the entry",
               'src="ohh-live.js"' in (WEB / "harness-hub" / "index.html").read_text(encoding="utf-8"))
            ck("baltor: guided demos ported",
               (WEB / "baltor" / "Baltor Guided Demos.html").exists()
               and 'href="index.html"' in (WEB / "baltor" / "Baltor Guided Demos.html").read_text(encoding="utf-8"))
            ck("context-is-everything: Demo Control Tower ported",
               (WEB / "context-is-everything" / "Demo Control Tower.html").exists())
        finally:
            WEB = real_web
    print("\n" + ("PASS — port_full_design_to_web self-test: deterministic transplant with verbatim kit, "
                  "recorded-only patches, seams, and lossless legacy handling."
                  if not fails else f"{len(fails)} FAILURES: {fails}"))
    return 0 if not fails else 1


if __name__ == "__main__":
    if "--self-test" in sys.argv:
        raise SystemExit(self_test())
    if "--check" in sys.argv:
        raise SystemExit(check())
    raise SystemExit(port())
