#!/usr/bin/env python3
"""scripts.report_current_state — generate Baltor's living current-state report, opportunities, risks, and
proof inventory FROM REAL ARTIFACTS (section_maturity_matrix.json, opportunities.json, risk_register.json,
the flywheel PROOF_MODULES, the contract/ownership manifests). Not hand-wavy: every claim is read from a file.
Deterministic + offline (no wall-clock). `--self-test` generates the docs then asserts they are complete.

CLI: python3 scripts/report_current_state.py --generate | --self-test
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
_ARCH = _REPO / "architecture"
_STATUS = _REPO / "docs" / "status"
_MAIN = _STATUS / "baltor-current-state-and-opportunities.md"
_REQUIRED_HEADINGS = ("## 1. Executive summary", "## 2. Correctness invariant status", "## 3. What works now",
                      "## 21. Risks and mitigations", "## 23. Exact commands to verify current state")


def _load(name: str) -> dict:
    return json.loads((_ARCH / name).read_text())


def _proof_modules() -> list:
    import scripts.baltor_flywheel as fw
    return list(fw.PROOF_MODULES)


def generate() -> list[str]:
    _STATUS.mkdir(parents=True, exist_ok=True)
    matrix = _load("section_maturity_matrix.json")
    opps = _load("opportunities.json")
    risks = _load("risk_register.json")
    pm = _proof_modules()
    secs = matrix["sections"]
    reference = [s for s in secs if s.get("critical_path_required")]
    reference_m10 = [s for s in reference if s.get("status") == "m10_complete"]
    candidates = [s for s in secs if s.get("status") in ("candidate", "experimental")]
    pending = [s for s in secs if not s.get("critical_path_required") and s.get("status") not in ("candidate", "experimental", "m10_complete")]

    def row(s):
        proof = (s.get("proof_scripts") or ["-"])[0].replace("scripts/", "")
        doc = (s.get("docs") or ["-"])[0]
        mark = "✅ M10" if s.get("critical_path_required") and s.get("status") == "m10_complete" else s.get("status")
        return f"| {s['section_id']} | {mark} | {'yes' if s.get('critical_path_required') else 'no'} | `{proof}` | {doc} |"

    sec_table = "\n".join(["| Section | Status | Reference | Proof | Docs |", "|---|---|---|---|---|"]
                          + [row(s) for s in sorted(secs, key=lambda x: x["section_id"])])

    def opp_block(pri):
        items = [o for o in opps["opportunities"] if o["priority"] == pri]
        if not items:
            return "_none_"
        return "\n".join(f"- **{o['opportunity_id']}** ({o['owner_section']}, {o['estimated_complexity']}, risk {o['risk']}) — {o['title']}. Done when: {o['done_when'][0]}" for o in items)

    risk_rows = "\n".join(f"| {r['risk_id']} | {r['severity']} | {r['likelihood']} | {r['owner']} | `{r['detection_proof']}` | {r['status']} |"
                          for r in risks["risks"])
    verify_cmds = "\n".join("    PYTHONPATH=. python3 " + c for c in [
        "scripts/baltor_flywheel.py --once", "scripts/check_baltor_full_stack_perfect.py --self-test",
        "scripts/check_section_maturity_matrix.py --self-test", "scripts/report_current_state.py --self-test",
        "scripts/check_cfpb_to_consumption_end_to_end.py --self-test"])

    main = f"""# Baltor Current State and Opportunities

> Generated by `scripts/report_current_state.py` from `architecture/section_maturity_matrix.json`,
> `opportunities.json`, `risk_register.json`, and the flywheel proof registry. Deterministic; not hand-written.

## 1. Executive summary
Baltor's local runtime correctness invariant runs ingestion → consumption end-to-end through the approved runtime, proven
by `check_baltor_full_stack_perfect` and `check_cfpb_to_consumption_end_to_end`. **{len(reference_m10)}/{len(reference)}**
critical-path sections are M10-complete with a registered proof. **{len(pm)}** proofs are green in the flywheel.
Non-reference surfaces ({', '.join(s['section_id'] for s in candidates)}) are honestly flagged candidate/pending.

## 2. Correctness invariant status
INGEST(CFPB decompose) → Verify (gate) → Optimize (bake-off) → Consumption-readiness → ConsumptionService →
served `ContextResponse.v1`. Reference result: answer **"10 business days"**, FAQ-30 held out as a warning, every
served fact source-handled + receipt-lineaged, deterministic. Total sections inventoried: **{len(secs)}**.

## 3. What works now
{chr(10).join('- ' + s['section_id'] + ' (' + (s.get('proof_scripts') or ['-'])[0].replace('scripts/','') + ')' for s in reference_m10)}

## 4. What is partially working
{chr(10).join('- ' + s['section_id'] + ' — ' + (s.get('known_gaps') or ['(see matrix)'])[0] for s in pending) or '_none — all non-candidate sections are M10_'}

## 5. What is candidate/experimental
{chr(10).join('- ' + s['section_id'] + ' — ' + (s.get('known_gaps') or [''])[0] for s in candidates)}

## Section maturity table
{sec_table}

## 19. Top P0 opportunities
{opp_block('P0')}

## 20. Top P1 opportunities
{opp_block('P1')}

## P2 (later)
{opp_block('P2')}

## 21. Risks and mitigations
| Risk | Severity | Likelihood | Owner | Detection | Status |
|---|---|---|---|---|---|
{risk_rows}

## 22. Recommended next 5 passes
1. api_runtime → M10 (POST /api/context/serve + /api/runtime/sections) — proof check_consumption_api
2. workers → context.consume durable command — proof check_consumption_worker_command
3. ui_pages → /consume page — proof check_consumption_ui
4. fragile_fact_watchtower minimum slice — proof check_watchtower_minimum_freshness
5. vector+graph lineage in ContextResponse — proof check_vector_graph_consumption_path

## 23. Exact commands to verify current state
```
{verify_cmds}
```

## 24. Known limitations
- API/UI/worker-consume are runtime-proven but lack HTTP/UI/durable-command surfaces (sequenced, each gated by a proof).
- Fragile-fact freshness is graceful (counts=0) until the Watchtower supplies FragilityMetadata.
- Unstructured parsing + object-store payload_ref are candidate (no paid infra; wrapped + cataloged).
- The admin server is the single allowlisted monolith (split target tracked).

## 25. Definition of done for next pass
api_runtime reaches M10: POST /api/context/serve returns a schema-valid ContextResponse.v1 (projection-only, no
secrets), GET responses/<id> + receipts/<id> work, check_consumption_api is registered + green, and the matrix
status flips to m10_complete.
"""
    written = []
    for path, body in [
        (_MAIN, main),
        (_STATUS / "current-state.md", f"# Current State (summary)\n\nSee [baltor-current-state-and-opportunities.md](baltor-current-state-and-opportunities.md).\n\nReference M10: {len(reference_m10)}/{len(reference)} · proofs green: {len(pm)} · candidates: {', '.join(s['section_id'] for s in candidates)}.\n\n{sec_table}\n"),
        (_STATUS / "opportunities.md", f"# Opportunities\n\nFrom `architecture/opportunities.json`.\n\n## P0 (now)\n{opp_block('P0')}\n\n## P1 (next)\n{opp_block('P1')}\n\n## P2 (later)\n{opp_block('P2')}\n"),
        (_STATUS / "risks-and-gaps.md", f"# Risks and Gaps\n\nFrom `architecture/risk_register.json`.\n\n| Risk | Severity | Likelihood | Owner | Detection | Status |\n|---|---|---|---|---|---|\n{risk_rows}\n"),
        (_STATUS / "proof-inventory.md", f"# Proof Inventory\n\n**{len(pm)}** proofs registered in the flywheel (`scripts/baltor_flywheel.py`).\n\n" + "\n".join(f"- `{p}`" for p, _ in pm) + "\n"),
        (_STATUS / "next-implementation-plan.md", f"# Next Implementation Plan\n\n{opp_block('P0')}\n\nThen P1:\n{opp_block('P1')}\n"),
    ]:
        path.write_text(body, encoding="utf-8")
        written.append(str(path.relative_to(_REPO)))
    return written


def _self_test() -> int:
    fails: list[str] = []

    def check(name: str, ok: bool, detail: str = "") -> None:
        print(f"  [{'ok' if ok else 'FAIL'}] {name}{(': ' + detail) if detail and not ok else ''}")
        if not ok:
            fails.append(name)

    written = generate()
    check("report generator wrote the status docs", len(written) >= 6, str(written))
    text = _MAIN.read_text(encoding="utf-8")
    missing = [h for h in _REQUIRED_HEADINGS if h not in text]
    check("the current-state report has the required headings", missing == [], str(missing))

    matrix = _load("section_maturity_matrix.json")
    sec_ids = [s["section_id"] for s in matrix["sections"]]
    not_in_report = [sid for sid in sec_ids if sid not in text]
    check("every section appears in the current-state report", not_in_report == [], str(not_in_report[:6]))

    # no completion claim without a proof: every M10 section in the matrix has a proof script
    no_proof = [s["section_id"] for s in matrix["sections"] if s.get("status") == "m10_complete" and not s.get("proof_scripts")]
    check("no section claims M10 without a proof", no_proof == [], str(no_proof))

    # opportunities cover every non-M10 section; risks present
    opps = _load("opportunities.json")
    owned = {o["owner_section"] for o in opps["opportunities"]}
    uncovered = [s["section_id"] for s in matrix["sections"]
                 if s.get("status") in ("candidate", "experimental", "m6_proof", "m7_api", "m8_ui") and s["section_id"] not in owned]
    check("every non-M10 section has an opportunity", uncovered == [], str(uncovered))
    check("risk register is rendered", "RISK-consumption-serves-unsafe" in _STATUS.joinpath("risks-and-gaps.md").read_text())
    check("no raw secret marker in the report", "sk-" not in text and "OH_SHOWCASE_TOKEN=" not in text)

    print(f"\n{'PASS — report_current_state: living current-state report + opportunities + risks + proof inventory generated from real artifacts; every section covered; no unproven M10 claim; no non-M10 section without an opportunity.' if not fails else f'{len(fails)} FAILURES: {fails}'}")
    return 0 if not fails else 1


def _main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Generate Baltor current-state report.")
    p.add_argument("--generate", action="store_true")
    p.add_argument("--self-test", action="store_true")
    a = p.parse_args(argv)
    if a.self_test:
        return _self_test()
    if a.generate:
        print("\n".join(generate())); return 0
    p.print_help(); return 0


if __name__ == "__main__":
    raise SystemExit(_main())
