#!/usr/bin/env python3
"""tools/generate_repo_edges — the edge-graph-generator: turn the surface-registry into per-repo EDGE
DIGESTS + the global repo dependency graph.

The point: a Claude Code session working in repo X should load X's OWN context (its blackbox) plus a small
EDGES digest — the published interfaces of the repos X depends on and the ones that depend on X — and NOTHING
of their internals. This tool generates exactly that from the single source of truth
(contracts/surface-registry.json + each surface's published `exposes`), so cross-repo awareness stays in sync
without any repo reading through another.

Per surface S it emits:
  - <out>/<S>.edges.json  : machine digest {depends_on:[{surface,exposes,role}], consumed_by:[...], forbidden:[...]}
  - <out>/<S>.EDGES.md    : the compact agent-facing brief a session drops into repo S reads
And globally:
  - <out>/graph.json      : nodes + directed edges (may_depend_on)
  - <out>/GRAPH.md        : the dependency graph as a mermaid diagram + adjacency list

Offline, deterministic, `--self-test`-able. Reads contracts only, never any repo's source.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent


def _resolve_registry() -> Path:
    """Robust registry lookup — works whether this tool lives in edge-graph-generator/ (registry is in the
    sibling dev-rules-context/) or inside dev-rules-context/tools/. No hardcoded path that breaks on move."""
    for c in (HERE.parent / "dev-rules-context" / "contracts" / "surface-registry.json",
              HERE.parent / "contracts" / "surface-registry.json",
              HERE / "contracts" / "surface-registry.json"):
        if c.exists():
            return c
    return HERE.parent / "dev-rules-context" / "contracts" / "surface-registry.json"


DEFAULT_REGISTRY = _resolve_registry()

# Display-only truncation lengths for human/agent-facing role summaries. The FULL text always lives in the
# registry (single source) — these only bound what is echoed into a digest, so drift here is cosmetic.
ROLE_SUMMARY_CHARS = 120   # a neighbor's role, shown inline in this repo's depends_on entry
ROLE_BRIEF_CHARS = 200     # this repo's own role, shown at the top of its EDGES.md
# mermaid node ids cannot contain hyphens; surface ids may. This is the documented substitution.
_MERMAID_HYPHEN = "-"
_MERMAID_SUB = "_"


def load_registry(path: Path) -> dict:
    return json.loads(path.read_text())


def edge_digest(reg: dict, surface: str) -> dict:
    surfaces = reg.get("surfaces", {})
    spec = surfaces[surface]
    forbidden = {(e["from"], e["to"]): e.get("why", "") for e in reg.get("forbidden_edges", [])}
    depends_on = []
    for dep in spec.get("may_depend_on", []):
        d = surfaces.get(dep, {})
        depends_on.append({"surface": dep, "repo": d.get("repo"), "exposes": d.get("exposes", []),
                           "role": d.get("role", "")[:ROLE_SUMMARY_CHARS]})
    # who consumes me = anyone whose may_depend_on includes me (authoritative) unioned with my consumed_by hint.
    consumers = sorted({n for n, s in surfaces.items() if surface in s.get("may_depend_on", [])}
                       | set(spec.get("consumed_by", [])))
    forbidden_from_me = [{"to": to, "why": why} for (frm, to), why in forbidden.items() if frm == surface]
    return {
        "record_type": "repo_edge_digest",
        "surface": surface, "repo": spec.get("repo"), "role": spec.get("role", ""),
        "exposes": spec.get("exposes", []),
        "depends_on": depends_on,          # what I may consume (their PUBLISHED edges, not internals)
        "consumed_by": consumers,          # who depends on me (keep my interface stable for them)
        "forbidden_from_me": forbidden_from_me,
        "rule": "Consume a neighbor ONLY via its exposed interface listed here — never read/import its source.",
    }


def render_edges_md(dig: dict) -> str:
    lines = [f"# Edges for `{dig['surface']}` ({dig.get('repo','')})", "",
             "> Generated by the edge-graph-generator from `contracts/surface-registry.json`. This is the ONLY",
             "> cross-repo context a session in this repo needs — the neighbors' **published edges**, not their",
             "> internals. Work inside this repo's own context (its blackbox) + this file.", "",
             f"**This repo's role:** {dig['role'][:ROLE_BRIEF_CHARS]}", "",
             f"**This repo exposes:** {', '.join(dig['exposes']) or '—'}", "",
             "## You may consume (via their published interface only)"]
    if dig["depends_on"]:
        for d in dig["depends_on"]:
            lines.append(f"- **{d['surface']}** (`{d.get('repo','')}`) — exposes: {', '.join(d['exposes']) or '—'}")
    else:
        lines.append("- (nothing — this repo depends on no other surface)")
    lines += ["", "## Who consumes you (keep these interfaces stable)",
              "- " + (", ".join(dig["consumed_by"]) or "(no downstream consumers yet)"), ""]
    if dig["forbidden_from_me"]:
        lines += ["## Forbidden (never depend on these — the boundary law)"]
        for f in dig["forbidden_from_me"]:
            lines.append(f"- **{f['to']}** — {f['why']}")
        lines.append("")
    lines.append("_" + dig["rule"] + "_")
    return "\n".join(lines) + "\n"


def build_graph(reg: dict) -> dict:
    surfaces = reg.get("surfaces", {})
    nodes = [{"id": n, "kind": s.get("kind", ""), "repo": s.get("repo")} for n, s in surfaces.items()]
    edges = [{"from": n, "to": dep} for n, s in surfaces.items() for dep in s.get("may_depend_on", [])]
    return {"record_type": "repo_dependency_graph", "nodes": nodes, "edges": edges,
            "surface_count": len(nodes), "edge_count": len(edges)}


def render_graph_md(graph: dict) -> str:
    lines = ["# Repo-to-repo dependency graph", "",
             f"{graph['surface_count']} surfaces, {graph['edge_count']} dependency edges. Direction: `A --> B`",
             "means A may consume B's published interface.", "", "```mermaid", "graph TD"]
    for e in graph["edges"]:
        lines.append(f"  {e['from'].replace(_MERMAID_HYPHEN, _MERMAID_SUB)} --> "
                     f"{e['to'].replace(_MERMAID_HYPHEN, _MERMAID_SUB)}")
    lines += ["```", "", "## Adjacency (who each repo may consume)"]
    adj: dict[str, list[str]] = {}
    for e in graph["edges"]:
        adj.setdefault(e["from"], []).append(e["to"])
    for n in sorted({node["id"] for node in graph["nodes"]}):
        lines.append(f"- **{n}** → {', '.join(sorted(adj.get(n, []))) or '(none)'}")
    return "\n".join(lines) + "\n"


def generate_all(reg: dict, outdir: Path) -> dict:
    outdir.mkdir(parents=True, exist_ok=True)
    written = []
    for surface in reg.get("surfaces", {}):
        dig = edge_digest(reg, surface)
        (outdir / f"{surface}.edges.json").write_text(json.dumps(dig, indent=2))
        (outdir / f"{surface}.EDGES.md").write_text(render_edges_md(dig))
        written.append(surface)
    graph = build_graph(reg)
    (outdir / "graph.json").write_text(json.dumps(graph, indent=2))
    (outdir / "GRAPH.md").write_text(render_graph_md(graph))
    return {"surfaces": written, "graph": graph}


def propagate_to_repos(reg: dict, outdir: Path, repos_root: Path) -> list[str]:
    """Copy each surface's freshly-generated `<S>.EDGES.md` into its repo folder as `<repos_root>/<S>/EDGES.md`
    — the per-repo digest a session actually opens. The surface key IS the folder name; only folders that exist
    are written (skip-missing keeps this safe in a partial mirror). This is the mechanism behind the operating
    rule 'regenerate every repo's EDGES.md after a registry change so no digest goes stale' — single source
    (the registry) → every repo's edge brief, no hand-maintained second copy. Mirror-only: at split time each
    repo is standalone and this is a no-op (no siblings), so it stays off by default."""
    propagated = []
    for surface in reg.get("surfaces", {}):
        dest = repos_root / surface
        src = outdir / f"{surface}.EDGES.md"
        if dest.is_dir() and src.is_file():
            (dest / "EDGES.md").write_text(src.read_text())
            propagated.append(surface)
    return propagated


def self_test() -> int:
    reg = {"surfaces": {
        "rules": {"repo": "r", "role": "rules", "kind": "rules", "exposes": ["standards"], "may_depend_on": []},
        "substrate": {"repo": "s", "role": "substrate", "kind": "substrate", "exposes": ["registry"], "may_depend_on": ["rules"]},
        "teleon": {"repo": "t", "role": "runtime", "kind": "product", "exposes": ["/api/teleon"], "may_depend_on": ["rules", "substrate"]},
        "baltor": {"repo": "b", "role": "applied", "kind": "product", "exposes": ["/api/baltor"], "may_depend_on": ["rules", "substrate", "teleon"], "consumed_by": []},
    }, "forbidden_edges": [{"from": "teleon", "to": "baltor", "why": "infra not product-specific"}]}
    checks = []
    dig = edge_digest(reg, "baltor")
    checks.append(("baltor depends_on lists teleon+substrate+rules", {d["surface"] for d in dig["depends_on"]} == {"teleon", "substrate", "rules"}))
    checks.append(("baltor digest carries teleon's exposes, not internals", any(d["surface"] == "teleon" and d["exposes"] == ["/api/teleon"] for d in dig["depends_on"])))
    tdig = edge_digest(reg, "teleon")
    checks.append(("teleon consumed_by includes baltor (derived)", "baltor" in tdig["consumed_by"]))
    checks.append(("teleon forbidden_from_me lists baltor", any(f["to"] == "baltor" for f in tdig["forbidden_from_me"])))
    g = build_graph(reg)
    checks.append(("graph has baltor->teleon edge", {"from": "baltor", "to": "teleon"} in g["edges"]))
    checks.append(("edges md renders + names the rule", "published interface" in render_edges_md(dig)))
    checks.append(("graph md renders mermaid", "```mermaid" in render_graph_md(g)))
    failed = [n for n, ok in checks if not ok]
    if failed:
        print("FAIL - generate_repo_edges:\n  " + "\n  ".join(failed)); return 1
    print("PASS - generate_repo_edges: per-repo edge digests (a repo sees neighbors' EXPOSES, never internals) "
          "+ consumed_by derived from the graph + forbidden edges + the global mermaid dependency graph.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate per-repo edge digests + the repo dependency graph.")
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    ap.add_argument("--out", type=Path, default=HERE.parent / "generated-edges")
    ap.add_argument("--write", action="store_true", help="write the digests + graph to --out")
    ap.add_argument("--propagate", action="store_true",
                    help="also copy each <S>.EDGES.md into its sibling repo folder <_repos>/<S>/EDGES.md "
                         "(the local monorepo mirror; no-op once repos are split standalone)")
    args = ap.parse_args()
    if args.self_test:
        return self_test()
    reg = load_registry(args.registry)
    if args.write:
        res = generate_all(reg, args.out)
        print(f"generated edge digests for {len(res['surfaces'])} surfaces + graph "
              f"({res['graph']['edge_count']} edges) -> {args.out}")
        if args.propagate:
            # repos_root = the dir holding every surface folder = registry's <_repos>/dev-rules-context/contracts → up 2
            repos_root = args.registry.resolve().parents[2]
            prop = propagate_to_repos(reg, args.out, repos_root)
            print(f"propagated EDGES.md into {len(prop)} repo folder(s) under {repos_root}")
    else:
        g = build_graph(reg)
        print(f"{g['surface_count']} surfaces, {g['edge_count']} edges (dry run — pass --write)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
