"""Compatibility entrypoint for default Context Fidelity workers.

The worker implementations live in ``scripts.context_workers.workers`` so hosted
deployments can replace, containerize, or selectively import lanes without
growing this file back into a registry monolith.
"""
from __future__ import annotations

import json

from scripts.context_workers.registry import registry
from scripts.context_workers.workers import (
    chunk_context,
    claim_extract,
    code_graph_build,
    dedupe_fingerprint,
    document_graph_build,
    document_tree_normalize,
    entity_extract,
    fragility_scan,
    graph_extract,
    graph_metrics,
    keyword_analysis,
    node_evidence_score,
    node_research_catalog,
    node_research_enrich,
    node_research_plan,
    nlp_signals,
    pii_detect,
    pipeline_pass,
    proper_noun_extract,
    regex_extract,
    refresh_plan,
    search_verify,
    text_normalize,
    adapter_catalog,
    ambiguity_scan,
    conflict_scan,
    fragile_fact_enrich,
    gliner_extract,
    datasketch_minhash,
    experimental_adapters_pipeline,
    ftfy_repair,
    language_detect,
    llm_audit_review,
    llm_claim_review,
    llm_conflict_review,
    llm_context_summarize,
    llm_graph_enrich,
    llm_trust_plan,
    model_cascade_catalog,
    marker_cli_extract,
    mineru_cli_extract,
    networkx_analyze,
    openosint_catalog,
    openosint_run,
    paddleocr_cli_extract,
    parse_docling,
    parse_grobid,
    parse_markitdown,
    parse_pdfplumber,
    parse_pymupdf,
    parse_tika,
    parse_unstructured,
    presidio_detect,
    rapidfuzz_alias,
    rdf_export,
    sklearn_features,
    spacy_extract,
    stanza_extract,
    textacy_extract,
)

__all__ = [
    "chunk_context",
    "claim_extract",
    "code_graph_build",
    "dedupe_fingerprint",
    "document_graph_build",
    "document_tree_normalize",
    "entity_extract",
    "ensure_registered",
    "fragility_scan",
    "graph_extract",
    "graph_metrics",
    "keyword_analysis",
    "node_evidence_score",
    "node_research_catalog",
    "node_research_enrich",
    "node_research_plan",
    "nlp_signals",
    "pii_detect",
    "pipeline_pass",
    "proper_noun_extract",
    "regex_extract",
    "refresh_plan",
    "search_verify",
    "text_normalize",
    "adapter_catalog",
    "ambiguity_scan",
    "conflict_scan",
    "fragile_fact_enrich",
    "gliner_extract",
    "datasketch_minhash",
    "experimental_adapters_pipeline",
    "ftfy_repair",
    "language_detect",
    "llm_audit_review",
    "llm_claim_review",
    "llm_conflict_review",
    "llm_context_summarize",
    "llm_graph_enrich",
    "llm_trust_plan",
    "model_cascade_catalog",
    "marker_cli_extract",
    "mineru_cli_extract",
    "networkx_analyze",
    "openosint_catalog",
    "openosint_run",
    "paddleocr_cli_extract",
    "parse_docling",
    "parse_grobid",
    "parse_markitdown",
    "parse_pdfplumber",
    "parse_pymupdf",
    "parse_tika",
    "parse_unstructured",
    "presidio_detect",
    "rapidfuzz_alias",
    "rdf_export",
    "sklearn_features",
    "spacy_extract",
    "stanza_extract",
    "textacy_extract",
]


def ensure_registered() -> None:
    """Import hook used by CLIs before reading the registry manifest."""
    return None


if __name__ == "__main__":
    print(json.dumps(registry.manifest(), indent=2))
